# Larger heap and default file encoding to keep builds more stable
org.gradle.jvmargs=-Xmx4G -Dfile.encoding=UTF-8

# Enable build cache to reuse outputs from unchanged tasks
org.gradle.caching=true

minecraft_version_range=[1.20.1,1.21)
minecraft_version=1.20.1
forge_version=47.2.0
forge_version_range=[47,)
loader_version_range=[47,)

mod_id=caerula_arbor
mod_name=Caerula Arbor
mod_license=GNU General Public License v3.0
mod_description=From game Arknights
mod_version=0.10.7+demcr
mod_authors="Apocalypse"
# dependencies
jei_version=15.20.0.106
cloth_config_version=11.1.106
jade_version=4681833
configured_version=5180900
bobs_originium_dream_version=1.0.16