package com.susen36.caerulaarbor.capability.player;

import com.susen36.caerulaarbor.init.CAConfigs;
import com.susen36.caerulaarbor.network.receive.PlayerVariablesSyncMessage;
import net.minecraft.core.HolderLookup;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.Tag;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.item.ItemStack;
import net.neoforged.neoforge.common.util.INBTSerializable;
import net.neoforged.neoforge.network.PacketDistributor;

public class PlayerVariable implements INBTSerializable<CompoundTag> {

    public double player_light = 100.0;
    public double player_lives = CAConfigs.LP_INIT.get();
    public double player_maxlive = CAConfigs.LP_LIMIT.get();
    public double player_shield = 0;
    public double disoclusion = 0;
    public boolean show_stats = true;
    public boolean relic_cursed_EMELIGHT = false;
    public boolean relic_cursed_GLOWBODY = false;
    public boolean relic_cursed_RESEARCH = false;
    public boolean relic_king_CROWN = false;
    public boolean relic_king_ARMOR = false;
    public boolean relic_king_SPEAR = false;
    public boolean relic_king_EXTENSION = false;
    public boolean kingShowPtc = true;
    public boolean relic_king_CRYSTAL = false;
    public boolean relic_hand_THORNS = false;
    public boolean relic_hand_STRANGLE = false;
    public boolean relic_hand_FERTILITY = false;
    public boolean relic_hand_SPEED = false;
    public boolean relic_hand_BARREN = false;
    public boolean relic_hand_SWIPE = false;
    public boolean relic_archfi_ARTIFACT = false;
    public boolean relic_hand_FIREWORK = false;
    public boolean relic_archfi_FLAG = false;
    public double relic_hand_ENGRAVE = -1.0;
    public boolean relic_archfi_BED = false;
    public double relic_SURVIVOR = -1.0;
    public boolean relic_TREATY = false;
    public boolean relic_archifi_RYLFATE = false;
    public boolean relic_util_MEATCAN = false;
    public boolean relic_util_SEAGRASS = false;
    public boolean relic_util_ORANGE = false;
    public boolean relic_util_COFFEE = false;
    public boolean relic_util_BERRIES = false;
    public boolean player_util_RAINBOW = false;
    public boolean player_util_AROMATIC = false;
    public boolean relic_util_MUSICBOX = false;
    public boolean relic_util_IRIS = false;
    public boolean relic_util_FLUTE = false;
    public boolean relic_util_VOYGOLD = false;
    public boolean relic_util_DURIN = false;
    public boolean relic_util_TOPONYM = false;
    public boolean relic_util_KETTLE = false;
    public boolean relic_legend_CHITIN = false;
    public ItemStack chitin_knife_selected = ItemStack.EMPTY;
    public boolean relic_util_ALLEY = false;
    public boolean relic_util_BATBED = false;
    public boolean relic_util_LONGEVITY = false;
    public boolean relic_util_OMNIKEY = false;
    public boolean relic_util_score = false;
    public boolean relic_util_RESCISSION = false;
    public boolean relic_util_STARE = false;
    public boolean relic_hand_SWORD = false;
    public boolean relic_util_ALLAY = false;
    public boolean relic_util_RAINBOW = false;
    public boolean relic_diso = false;
    public boolean relic_diso_FLESH = false;
    public boolean relic_diso_BLOOD = false;
    public boolean relic_diso_NEURO = false;
    public boolean relic_ahnd_SWIPE = false;
    public boolean relic_diso_ATTENTION = false;
    public boolean relic_hanshand_SPIKE = false;
    public boolean relic_royalfate = false;
    public double player_king_suit = 0;
    public double player_demon_suit = 0;
    public double player_oceanization = 0;
    public boolean relic_cursed_HEART = false;
    public boolean relic_HEMOST = false;
    public boolean relic_YEARNING = false;
    public double plauyer_balance = 0;
    public boolean can_player_evo = false;
    public double reserve_quantity = 0;
    public double reserve_quality = 0;
    public boolean PEVO_NEXUS_no_rejection = false;
    public boolean PEVO_NEXUS_reg_sanity = false;
    public double PEVO_NODE_add_def = 0;
    public double PEVO_NODE_add_resis = 0;
    public double PEVO_NODE_add_speed = 0;
    public double PEVO_NODE_add_sanity = 0;
    public boolean PEVO_NEXUS_reg_lights = false;
    public double PEVO_NODE_add_damage = 0;
    public double PEVO_NODE_less_damage = 0;
    public double PEVO_NODE_living_barrier = 0;
    public double PEVO_NODE_add_miss = 0;
    public boolean PEVO_NEXUS_perc_damage = false;
    public double PEVO_NODE_real_damage = 0;
    public double PEVO_NODE_heal_damage = 0;
    public double PEVO_NODE_worse_break = 0;
    public boolean PEVO_NEXUS_expo_shield = false;
    public double PEVO_NODE_eunectes = 0;
    public double PEVO_NODE_less_armor = 0;

    public void syncPlayerVariables(Entity entity) {
        if (entity instanceof ServerPlayer serverPlayer) {
            PacketDistributor.sendToPlayer(serverPlayer, new PlayerVariablesSyncMessage(this));
        }
    }

    public Tag writeNBT() {
        CompoundTag nbt = new CompoundTag();
        nbt.putDouble("player_light", player_light);
        nbt.putDouble("player_lives", player_lives);
        nbt.putDouble("player_maxlive", player_maxlive);
        nbt.putDouble("player_shield", player_shield);
        nbt.putDouble("disoclusion", disoclusion);
        nbt.putBoolean("show_stats", show_stats);
        nbt.putBoolean("relic_cursed_EMELIGHT", relic_cursed_EMELIGHT);
        nbt.putBoolean("relic_cursed_GLOWBODY", relic_cursed_GLOWBODY);
        nbt.putBoolean("relic_cursed_RESEARCH", relic_cursed_RESEARCH);
        nbt.putBoolean("relic_king_CROWN", relic_king_CROWN);
        nbt.putBoolean("relic_king_ARMOR", relic_king_ARMOR);
        nbt.putBoolean("relic_king_SPEAR", relic_king_SPEAR);
        nbt.putBoolean("relic_king_EXTENSION", relic_king_EXTENSION);
        nbt.putBoolean("kingShowPtc", kingShowPtc);
        nbt.putBoolean("relic_king_CRYSTAL", relic_king_CRYSTAL);
        nbt.putBoolean("relic_hand_THORNS", relic_hand_THORNS);
        nbt.putBoolean("relic_hand_STRANGLE", relic_hand_STRANGLE);
        nbt.putBoolean("relic_hand_FERTILITY", relic_hand_FERTILITY);
        nbt.putBoolean("relic_hand_SPEED", relic_hand_SPEED);
        nbt.putBoolean("relic_hand_BARREN", relic_hand_BARREN);
        nbt.putBoolean("relic_hand_SWIPE", relic_hand_SWIPE);
        nbt.putBoolean("relic_archfi_ARTIFACT", relic_archfi_ARTIFACT);
        nbt.putBoolean("relic_hand_FIREWORK", relic_hand_FIREWORK);
        nbt.putBoolean("relic_archfi_FLAG", relic_archfi_FLAG);
        nbt.putDouble("relic_hand_ENGRAVE", relic_hand_ENGRAVE);
        nbt.putBoolean("relic_archfi_BED", relic_archfi_BED);
        nbt.putDouble("relic_SURVIVOR", relic_SURVIVOR);
        nbt.putBoolean("relic_TREATY", relic_TREATY);
        nbt.putBoolean("relic_archifi_RYLFATE", relic_archifi_RYLFATE);
        nbt.putBoolean("relic_util_MEATCAN", relic_util_MEATCAN);
        nbt.putBoolean("relic_util_SEAGRASS", relic_util_SEAGRASS);
        nbt.putBoolean("relic_util_ORANGE", relic_util_ORANGE);
        nbt.putBoolean("relic_util_COFFEE", relic_util_COFFEE);
        nbt.putBoolean("relic_util_BERRIES", relic_util_BERRIES);
        nbt.putBoolean("player_util_RAINBOW", player_util_RAINBOW);
        nbt.putBoolean("player_util_AROMATIC", player_util_AROMATIC);
        nbt.putBoolean("relic_util_MUSICBOX", relic_util_MUSICBOX);
        nbt.putBoolean("relic_util_IRIS", relic_util_IRIS);
        nbt.putBoolean("relic_util_FLUTE", relic_util_FLUTE);
        nbt.putBoolean("relic_util_VOYGOLD", relic_util_VOYGOLD);
        nbt.putBoolean("relic_util_DURIN", relic_util_DURIN);
        nbt.putBoolean("relic_util_TOPONYM", relic_util_TOPONYM);
        nbt.putBoolean("relic_util_KETTLE", relic_util_KETTLE);
        nbt.putBoolean("relic_legend_CHITIN", relic_legend_CHITIN);
        nbt.put("chitin_knife_selected", chitin_knife_selected.save(new CompoundTag()));
        nbt.putBoolean("relic_util_ALLEY", relic_util_ALLEY);
        nbt.putBoolean("relic_util_BATBED", relic_util_BATBED);
        nbt.putBoolean("relic_util_LONGEVITY", relic_util_LONGEVITY);
        nbt.putBoolean("relic_util_OMNIKEY", relic_util_OMNIKEY);
        nbt.putBoolean("relic_util_score", relic_util_score);
        nbt.putBoolean("relic_util_RESCISSION", relic_util_RESCISSION);
        nbt.putBoolean("relic_util_STARE", relic_util_STARE);
        nbt.putBoolean("relic_hand_SWORD", relic_hand_SWORD);
        nbt.putBoolean("relic_util_ALLAY", relic_util_ALLAY);
        nbt.putBoolean("relic_util_RAINBOW", relic_util_RAINBOW);
        nbt.putBoolean("relic_diso", relic_diso);
        nbt.putBoolean("relic_diso_FLESH", relic_diso_FLESH);
        nbt.putBoolean("relic_diso_BLOOD", relic_diso_BLOOD);
        nbt.putBoolean("relic_diso_NEURO", relic_diso_NEURO);
        nbt.putBoolean("relic_ahnd_SWIPE", relic_ahnd_SWIPE);
        nbt.putBoolean("relic_diso_ATTENTION", relic_diso_ATTENTION);
        nbt.putBoolean("relic_hanshand_SPIKE", relic_hanshand_SPIKE);
        nbt.putBoolean("relic_royalfate", relic_royalfate);
        nbt.putDouble("player_king_suit", player_king_suit);
        nbt.putDouble("player_demon_suit", player_demon_suit);
        nbt.putDouble("player_oceanization", player_oceanization);
        nbt.putBoolean("relic_cursed_HEART", relic_cursed_HEART);
        nbt.putBoolean("relic_HEMOST", relic_HEMOST);
        nbt.putBoolean("relic_YEARNING", relic_YEARNING);
        nbt.putDouble("plauyer_balance", plauyer_balance);
        nbt.putBoolean("can_player_evo", can_player_evo);
        nbt.putDouble("reserve_quantity", reserve_quantity);
        nbt.putDouble("reserve_quality", reserve_quality);
        nbt.putBoolean("PEVO_NEXUS_no_rejection", PEVO_NEXUS_no_rejection);
        nbt.putBoolean("PEVO_NEXUS_reg_sanity", PEVO_NEXUS_reg_sanity);
        nbt.putDouble("PEVO_NODE_add_def", PEVO_NODE_add_def);
        nbt.putDouble("PEVO_NODE_add_resis", PEVO_NODE_add_resis);
        nbt.putDouble("PEVO_NODE_add_speed", PEVO_NODE_add_speed);
        nbt.putDouble("PEVO_NODE_add_sanity", PEVO_NODE_add_sanity);
        nbt.putBoolean("PEVO_NEXUS_reg_lights", PEVO_NEXUS_reg_lights);
        nbt.putDouble("PEVO_NODE_add_damage", PEVO_NODE_add_damage);
        nbt.putDouble("PEVO_NODE_less_damage", PEVO_NODE_less_damage);
        nbt.putDouble("PEVO_NODE_living_barrier", PEVO_NODE_living_barrier);
        nbt.putDouble("PEVO_NODE_add_miss", PEVO_NODE_add_miss);
        nbt.putBoolean("PEVO_NEXUS_perc_damage", PEVO_NEXUS_perc_damage);
        nbt.putDouble("PEVO_NODE_real_damage", PEVO_NODE_real_damage);
        nbt.putDouble("PEVO_NODE_heal_damage", PEVO_NODE_heal_damage);
        nbt.putDouble("PEVO_NODE_worse_break", PEVO_NODE_worse_break);
        nbt.putBoolean("PEVO_NEXUS_expo_shield", PEVO_NEXUS_expo_shield);
        nbt.putDouble("PEVO_NODE_eunectes", PEVO_NODE_eunectes);
        nbt.putDouble("PEVO_NODE_less_armor", PEVO_NODE_less_armor);
        return nbt;
    }

    public void readNBT(Tag tag) {
        CompoundTag nbt = (CompoundTag) tag;
        player_light = nbt.getDouble("player_light");
        player_lives = nbt.getDouble("player_lives");
        player_maxlive = nbt.getDouble("player_maxlive");
        player_shield = nbt.getDouble("player_shield");
        disoclusion = nbt.getDouble("disoclusion");
        show_stats = nbt.getBoolean("show_stats");
        relic_cursed_EMELIGHT = nbt.getBoolean("relic_cursed_EMELIGHT");
        relic_cursed_GLOWBODY = nbt.getBoolean("relic_cursed_GLOWBODY");
        relic_cursed_RESEARCH = nbt.getBoolean("relic_cursed_RESEARCH");
        relic_king_CROWN = nbt.getBoolean("relic_king_CROWN");
        relic_king_ARMOR = nbt.getBoolean("relic_king_ARMOR");
        relic_king_SPEAR = nbt.getBoolean("relic_king_SPEAR");
        relic_king_EXTENSION = nbt.getBoolean("relic_king_EXTENSION");
        kingShowPtc = nbt.getBoolean("kingShowPtc");
        relic_king_CRYSTAL = nbt.getBoolean("relic_king_CRYSTAL");
        relic_hand_THORNS = nbt.getBoolean("relic_hand_THORNS");
        relic_hand_STRANGLE = nbt.getBoolean("relic_hand_STRANGLE");
        relic_hand_FERTILITY = nbt.getBoolean("relic_hand_FERTILITY");
        relic_hand_SPEED = nbt.getBoolean("relic_hand_SPEED");
        relic_hand_BARREN = nbt.getBoolean("relic_hand_BARREN");
        relic_hand_SWIPE = nbt.getBoolean("relic_hand_SWIPE");
        relic_archfi_ARTIFACT = nbt.getBoolean("relic_archfi_ARTIFACT");
        relic_hand_FIREWORK = nbt.getBoolean("relic_hand_FIREWORK");
        relic_archfi_FLAG = nbt.getBoolean("relic_archfi_FLAG");
        relic_hand_ENGRAVE = nbt.getDouble("relic_hand_ENGRAVE");
        relic_archfi_BED = nbt.getBoolean("relic_archfi_BED");
        relic_SURVIVOR = nbt.getDouble("relic_SURVIVOR");
        relic_TREATY = nbt.getBoolean("relic_TREATY");
        relic_archifi_RYLFATE = nbt.getBoolean("relic_archifi_RYLFATE");
        relic_util_MEATCAN = nbt.getBoolean("relic_util_MEATCAN");
        relic_util_SEAGRASS = nbt.getBoolean("relic_util_SEAGRASS");
        relic_util_ORANGE = nbt.getBoolean("relic_util_ORANGE");
        relic_util_COFFEE = nbt.getBoolean("relic_util_COFFEE");
        relic_util_BERRIES = nbt.getBoolean("relic_util_BERRIES");
        player_util_RAINBOW = nbt.getBoolean("player_util_RAINBOW");
        player_util_AROMATIC = nbt.getBoolean("player_util_AROMATIC");
        relic_util_MUSICBOX = nbt.getBoolean("relic_util_MUSICBOX");
        relic_util_IRIS = nbt.getBoolean("relic_util_IRIS");
        relic_util_FLUTE = nbt.getBoolean("relic_util_FLUTE");
        relic_util_VOYGOLD = nbt.getBoolean("relic_util_VOYGOLD");
        relic_util_DURIN = nbt.getBoolean("relic_util_DURIN");
        relic_util_TOPONYM = nbt.getBoolean("relic_util_TOPONYM");
        relic_util_KETTLE = nbt.getBoolean("relic_util_KETTLE");
        relic_legend_CHITIN = nbt.getBoolean("relic_legend_CHITIN");
        chitin_knife_selected = ItemStack.of(nbt.getCompound("chitin_knife_selected"));
        relic_util_ALLEY = nbt.getBoolean("relic_util_ALLEY");
        relic_util_BATBED = nbt.getBoolean("relic_util_BATBED");
        relic_util_LONGEVITY = nbt.getBoolean("relic_util_LONGEVITY");
        relic_util_OMNIKEY = nbt.getBoolean("relic_util_OMNIKEY");
        relic_util_score = nbt.getBoolean("relic_util_score");
        relic_util_RESCISSION = nbt.getBoolean("relic_util_RESCISSION");
        relic_util_STARE = nbt.getBoolean("relic_util_STARE");
        relic_hand_SWORD = nbt.getBoolean("relic_hand_SWORD");
        relic_util_ALLAY = nbt.getBoolean("relic_util_ALLAY");
        relic_util_RAINBOW = nbt.getBoolean("relic_util_RAINBOW");
        relic_diso = nbt.getBoolean("relic_diso");
        relic_diso_FLESH = nbt.getBoolean("relic_diso_FLESH");
        relic_diso_BLOOD = nbt.getBoolean("relic_diso_BLOOD");
        relic_diso_NEURO = nbt.getBoolean("relic_diso_NEURO");
        relic_ahnd_SWIPE = nbt.getBoolean("relic_ahnd_SWIPE");
        relic_diso_ATTENTION = nbt.getBoolean("relic_diso_ATTENTION");
        relic_hanshand_SPIKE = nbt.getBoolean("relic_hanshand_SPIKE");
        relic_royalfate = nbt.getBoolean("relic_royalfate");
        player_king_suit = nbt.getDouble("player_king_suit");
        player_demon_suit = nbt.getDouble("player_demon_suit");
        player_oceanization = nbt.getDouble("player_oceanization");
        relic_cursed_HEART = nbt.getBoolean("relic_cursed_HEART");
        relic_HEMOST = nbt.getBoolean("relic_HEMOST");
        relic_YEARNING = nbt.getBoolean("relic_YEARNING");
        plauyer_balance = nbt.getDouble("plauyer_balance");
        can_player_evo = nbt.getBoolean("can_player_evo");
        reserve_quantity = nbt.getDouble("reserve_quantity");
        reserve_quality = nbt.getDouble("reserve_quality");
        PEVO_NEXUS_no_rejection = nbt.getBoolean("PEVO_NEXUS_no_rejection");
        PEVO_NEXUS_reg_sanity = nbt.getBoolean("PEVO_NEXUS_reg_sanity");
        PEVO_NODE_add_def = nbt.getDouble("PEVO_NODE_add_def");
        PEVO_NODE_add_resis = nbt.getDouble("PEVO_NODE_add_resis");
        PEVO_NODE_add_speed = nbt.getDouble("PEVO_NODE_add_speed");
        PEVO_NODE_add_sanity = nbt.getDouble("PEVO_NODE_add_sanity");
        PEVO_NEXUS_reg_lights = nbt.getBoolean("PEVO_NEXUS_reg_lights");
        PEVO_NODE_add_damage = nbt.getDouble("PEVO_NODE_add_damage");
        PEVO_NODE_less_damage = nbt.getDouble("PEVO_NODE_less_damage");
        PEVO_NODE_living_barrier = nbt.getDouble("PEVO_NODE_living_barrier");
        PEVO_NODE_add_miss = nbt.getDouble("PEVO_NODE_add_miss");
        PEVO_NEXUS_perc_damage = nbt.getBoolean("PEVO_NEXUS_perc_damage");
        PEVO_NODE_real_damage = nbt.getDouble("PEVO_NODE_real_damage");
        PEVO_NODE_heal_damage = nbt.getDouble("PEVO_NODE_heal_damage");
        PEVO_NODE_worse_break = nbt.getDouble("PEVO_NODE_worse_break");
        PEVO_NEXUS_expo_shield = nbt.getBoolean("PEVO_NEXUS_expo_shield");
        PEVO_NODE_eunectes = nbt.getDouble("PEVO_NODE_eunectes");
        PEVO_NODE_less_armor = nbt.getDouble("PEVO_NODE_less_armor");
    }

    @Override
    public CompoundTag serializeNBT(HolderLookup.Provider provider) {
        return (CompoundTag) writeNBT();
    }

    @Override
    public void deserializeNBT(HolderLookup.Provider provider, CompoundTag nbt) {
        readNBT(nbt);
    }
}