package com.apocalypse.caerulaarbor.init;

/*
 *    MCreator note: This file will be REGENERATED on each build.
 */

import com.apocalypse.caerulaarbor.CaerulaArborMod;
import com.apocalypse.caerulaarbor.block.*;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class CaerulaArborModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, CaerulaArborMod.MODID);
	public static final RegistryObject<Block> EMERGENCY_LIGHT = REGISTRY.register("emergency_light", () -> new EmergencyLightBlock());
	public static final RegistryObject<Block> KINGS_ARMOR = REGISTRY.register("kings_armor", () -> new KingsArmorBlock());
	public static final RegistryObject<Block> BLOCK_CROWN = REGISTRY.register("block_crown", () -> new BlockCrownBlock());
	public static final RegistryObject<Block> BLOCK_SPEAR = REGISTRY.register("block_spear", () -> new BlockSpearBlock());
	public static final RegistryObject<Block> BLOCK_EXTENSION = REGISTRY.register("block_extension", () -> new BlockExtensionBlock());
	public static final RegistryObject<Block> BLOCK_CRYSTAL = REGISTRY.register("block_crystal", () -> new BlockCrystalBlock());
	public static final RegistryObject<Block> BLOCK_FATE = REGISTRY.register("block_fate", () -> new BlockFateBlock());
	public static final RegistryObject<Block> BERRY_CAN = REGISTRY.register("berry_can", () -> new BerryCanBlock());
	public static final RegistryObject<Block> REDSTONE_IRIS = REGISTRY.register("redstone_iris", () -> new ResdtoneIrisBlock());
	public static final RegistryObject<Block> REDSTONEIRIS_SEEDING = REGISTRY.register("redstoneiris_seeding", () -> new RedstoneirisSeedingBlock());
	public static final RegistryObject<Block> SEA_TRAIL_INIT = REGISTRY.register("sea_trail_init", () -> new SeaTrailInitBlock());
	public static final RegistryObject<Block> SEA_TRAIL_GROWING = REGISTRY.register("sea_trail_growing", () -> new SeaTrailGrowingBlock());
	public static final RegistryObject<Block> SEA_TRAIL_GROWN = REGISTRY.register("sea_trail_grown", () -> new SeaTrailGrownBlock());
	public static final RegistryObject<Block> BOMB_TRAILER = REGISTRY.register("bomb_trailer", () -> new BombTrailerBlock());
	public static final RegistryObject<Block> OCEAN_GLASS = REGISTRY.register("ocean_glass", () -> new OceanGlassBlock());
	public static final RegistryObject<Block> OCEAN_GLASSPANE = REGISTRY.register("ocean_glasspane", () -> new OceanGlasspaneBlock());
	public static final RegistryObject<Block> CHITIN_BLOCK = REGISTRY.register("chitin_block", () -> new ChitinBlockBlock());
	public static final RegistryObject<Block> BLOCK_KETTLE = REGISTRY.register("block_kettle", () -> new BlockKettleBlock());
	public static final RegistryObject<Block> OCEAN_FARMLAND = REGISTRY.register("ocean_farmland", () -> new OceanFarmlandBlock());
	public static final RegistryObject<Block> ALLAY_BLOCK = REGISTRY.register("allay_block", () -> new AllayBlockBlock());
	public static final RegistryObject<Block> BLOCK_BATBED = REGISTRY.register("block_batbed", () -> new BlockBatbedBlock());
	public static final RegistryObject<Block> BATBED_UPPER = REGISTRY.register("batbed_upper", () -> new BatbedUpperBlock());
	public static final RegistryObject<Block> TRAIL_CAKE = REGISTRY.register("trail_cake", () -> new TrailCakeBlock());
	public static final RegistryObject<Block> CARAMEL_CAKE = REGISTRY.register("caramel_cake", () -> new CaramelCakeBlock());
	public static final RegistryObject<Block> OCEAN_CRYSTAL_BLOCK = REGISTRY.register("ocean_crystal_block", () -> new OceanCrystalBlockBlock());
	public static final RegistryObject<Block> COMPLEX_CHITIN_BLOCK = REGISTRY.register("complex_chitin_block", () -> new ComplexChitinBlockBlock());
	public static final RegistryObject<Block> TIDE_OBSERVATION = REGISTRY.register("tide_observation", () -> new TideObservationBlock());
	public static final RegistryObject<Block> ANCHOR_LOWER = REGISTRY.register("anchor_lower", () -> new AnchorLowerBlock());
	public static final RegistryObject<Block> ANCHOR_MEDIUM = REGISTRY.register("anchor_medium", () -> new AnchorMediumBlock());
	public static final RegistryObject<Block> ANCHOR_UPPER = REGISTRY.register("anchor_upper", () -> new AnchorUpperBlock());
	public static final RegistryObject<Block> BLOCK_RECORDER = REGISTRY.register("block_recorder", () -> new BlockRecorderBlock());
	public static final RegistryObject<Block> SEA_TRAIL_SOLID = REGISTRY.register("sea_trail_solid", () -> new SeaTrailSolidBlock());
	public static final RegistryObject<Block> TRAIL_BRICK = REGISTRY.register("trail_brick", () -> new TrailBrickBlock());
	public static final RegistryObject<Block> TRAIL_SLAB = REGISTRY.register("trail_slab", () -> new TrailSlabBlock());
	public static final RegistryObject<Block> TRAIL_STAIR = REGISTRY.register("trail_stair", () -> new TrailStairBlock());
	public static final RegistryObject<Block> TRAIL_BUTTON = REGISTRY.register("trail_button", () -> new TrailButtonBlock());
	public static final RegistryObject<Block> TRAIL_PRESSURE_PLATE = REGISTRY.register("trail_pressure_plate", () -> new TrailPressurePlateBlock());
	public static final RegistryObject<Block> TRAIL_TILE = REGISTRY.register("trail_tile", () -> new TrailTileBlock());
	public static final RegistryObject<Block> REAPER_EGG = REGISTRY.register("reaper_egg", () -> new ReaperEggBlock());
	public static final RegistryObject<Block> OCEAN_OVARY = REGISTRY.register("ocean_ovary", () -> new OceanOvaryBlock());
	public static final RegistryObject<Block> TRAIL_PUMPKING = REGISTRY.register("trail_pumpking", () -> new TrailPumpkingBlock());
	public static final RegistryObject<Block> TRAIL_DEBRIS = REGISTRY.register("trail_debris", () -> new TrailDebrisBlock());
	public static final RegistryObject<Block> TRAILRITE_BLOCK = REGISTRY.register("trailrite_block", () -> new TrailriteBlockBlock());
	public static final RegistryObject<Block> TRAIL_WALL = REGISTRY.register("trail_wall", () -> new TrailWallBlock());
	public static final RegistryObject<Block> RED_OVARY = REGISTRY.register("red_ovary", () -> new RedOvaryBlock());
	public static final RegistryObject<Block> TIDEWAY_CRADLE = REGISTRY.register("tideway_cradle", () -> new TidewayCradleBlock());
	public static final RegistryObject<Block> SALTWIND_SANDSTONE = REGISTRY.register("saltwind_sandstone", () -> new SaltwindSandstoneBlock());
	public static final RegistryObject<Block> CHISELED_SALTWIND_SANDSTONE = REGISTRY.register("chiseled_saltwind_sandstone", () -> new ChiseledSaltwindSandstoneBlock());
	public static final RegistryObject<Block> SMOOTH_SALTWIND_SANDATONE = REGISTRY.register("smooth_saltwind_sandatone", () -> new SmoothSaltwindSandatoneBlock());
	public static final RegistryObject<Block> SALTWIND_SAND_STAIR = REGISTRY.register("saltwind_sand_stair", () -> new SaltwindSandStairBlock());
	public static final RegistryObject<Block> SALTWIND_SAND_SLAB = REGISTRY.register("saltwind_sand_slab", () -> new SaltwindSandSlabBlock());
	public static final RegistryObject<Block> SMOOTH_SALTWIND_SAND_STAIR = REGISTRY.register("smooth_saltwind_sand_stair", () -> new SmoothSaltwindSandStairBlock());
	public static final RegistryObject<Block> SMOOTH_SALTWIND_SAND_SLAB = REGISTRY.register("smooth_saltwind_sand_slab", () -> new SmoothSaltwindSandSlabBlock());
	public static final RegistryObject<Block> SALTWIND_SAND_WALL = REGISTRY.register("saltwind_sand_wall", () -> new SaltwindSandWallBlock());
	public static final RegistryObject<Block> CHIESELED_SALTWIND_SAND_WALL = REGISTRY.register("chieseled_saltwind_sand_wall", () -> new ChieseledSaltwindSandWallBlock());
	public static final RegistryObject<Block> SMOOTH_SALTWIND_SAND_WALL = REGISTRY.register("smooth_saltwind_sand_wall", () -> new SmoothSaltwindSandWallBlock());
	public static final RegistryObject<Block> TIDE_BISHOP_CORE = REGISTRY.register("tide_bishop_core", () -> new TideBishopCoreBlock());
	public static final RegistryObject<Block> HETEROPIC_BLOCK = REGISTRY.register("heteropic_block", () -> new HeteropicBlockBlock());
	public static final RegistryObject<Block> TRAIL_LOG = REGISTRY.register("trail_log", () -> new TrailLogBlock());
	public static final RegistryObject<Block> TRAIL_LEAVE = REGISTRY.register("trail_leave", () -> new TrailLeaveBlock());
	public static final RegistryObject<Block> TRAIL_PLANK = REGISTRY.register("trail_plank", () -> new TrailPlankBlock());
	public static final RegistryObject<Block> TRAIL_PLANKS_FENCE = REGISTRY.register("trail_planks_fence", () -> new TrailPlanksFenceBlock());
	public static final RegistryObject<Block> TRAIL_PLANK_FENCEDOOR = REGISTRY.register("trail_plank_fencedoor", () -> new TrailPlankFencedoorBlock());
	public static final RegistryObject<Block> TRAIL_PLANK_SLAB = REGISTRY.register("trail_plank_slab", () -> new TrailPlankSlabBlock());
	public static final RegistryObject<Block> TRAIL_PLANK_STAIR = REGISTRY.register("trail_plank_stair", () -> new TrailPlankStairBlock());
	public static final RegistryObject<Block> TRAIL_PLANK_BUTTON = REGISTRY.register("trail_plank_button", () -> new TrailPlankButtonBlock());
	public static final RegistryObject<Block> TRAIL_PLANK_PRESSURE_PLATE = REGISTRY.register("trail_plank_pressure_plate", () -> new TrailPlankPressurePlateBlock());
	public static final RegistryObject<Block> STRIPPED_TRAIL_LOG = REGISTRY.register("stripped_trail_log", () -> new StrippedTrailLogBlock());
	public static final RegistryObject<Block> TRAIL_PLANK_DOOR = REGISTRY.register("trail_plank_door", () -> new TrailPlankDoorBlock());
	public static final RegistryObject<Block> SALTSAND = REGISTRY.register("saltsand", () -> new SaltsandBlock());
	public static final RegistryObject<Block> SEA_TRAIL_BURNT = REGISTRY.register("sea_trail_burnt", () -> new SeaTrailBurntBlock());
	public static final RegistryObject<Block> SEA_TRAIL_BURNT_SOLID = REGISTRY.register("sea_trail_burnt_solid", () -> new SeaTrailBurntSolidBlock());
	public static final RegistryObject<Block> CHESTMEGA_SPAWNER = REGISTRY.register("chestmega_spawner", () -> new ChestmegaSpawnerBlock());
	public static final RegistryObject<Block> CRACKED_TRAIL_BRICK = REGISTRY.register("cracked_trail_brick", () -> new CrackedTrailBrickBlock());
	public static final RegistryObject<Block> SALTWIND_COLUMN = REGISTRY.register("saltwind_column", () -> new SaltwindColumnBlock());
	public static final RegistryObject<Block> BLOCK_CHESTFISH = REGISTRY.register("block_chestfish", () -> new BlockChestfishBlock());
	public static final RegistryObject<Block> WHITE_CHITIN_BLOCK = REGISTRY.register("white_chitin_block", () -> new WhiteChitinBlockBlock());
	public static final RegistryObject<Block> SALTWIND_BRICK = REGISTRY.register("saltwind_brick", () -> new SaltwindBrickBlock());
	public static final RegistryObject<Block> SALTWIND_SMOOTH_BRICK = REGISTRY.register("saltwind_smooth_brick", () -> new SaltwindSmoothBrickBlock());
	public static final RegistryObject<Block> SALTWIND_BRICK_SLAB = REGISTRY.register("saltwind_brick_slab", () -> new SaltwindBrickSlabBlock());
	public static final RegistryObject<Block> SALTWIND_SMOOTH_SLAB = REGISTRY.register("saltwind_smooth_slab", () -> new SaltwindSmoothSlabBlock());
	public static final RegistryObject<Block> SALTWIND_STAIR = REGISTRY.register("saltwind_stair", () -> new SaltwindStairBlock());
	public static final RegistryObject<Block> TRAIL_WOOD_TRAPDOOR = REGISTRY.register("trail_wood_trapdoor", () -> new TrailWoodTrapdoorBlock());
	public static final RegistryObject<Block> TRAIL_STONE = REGISTRY.register("trail_stone", () -> new TrailStoneBlock());
	public static final RegistryObject<Block> TRAIL_PULSE = REGISTRY.register("trail_pulse", () -> new TrailPulseBlock());
	public static final RegistryObject<Block> TRAIL_MUSHROOM = REGISTRY.register("trail_mushroom", () -> new TrailMushroomBlock());
	public static final RegistryObject<Block> VIVIPAROUS_LILY = REGISTRY.register("viviparous_lily", () -> new ViviparousLilyBlock());
	public static final RegistryObject<Block> HUGE_LILY = REGISTRY.register("huge_lily", () -> new HugeLilyBlock());
	public static final RegistryObject<Block> BOMB_COPPER = REGISTRY.register("bomb_copper", () -> new BombCopperBlock());
	public static final RegistryObject<Block> PHLOEM_BLOCK = REGISTRY.register("phloem_block", () -> new PholemBlockBlock());
	public static final RegistryObject<Block> FIBRE_BLOCK = REGISTRY.register("fibre_block", () -> new FibreBlockBlock());
	public static final RegistryObject<Block> COOKED_FIBRE_BLOCK = REGISTRY.register("cooked_fibre_block", () -> new CookedFibreBlockBlock());
	public static final RegistryObject<Block> UNDERTIDE_TABLE = REGISTRY.register("undertide_table", () -> new UndertideTableBlock());
	public static final RegistryObject<Block> UNDERTIDE_SPAWN = REGISTRY.register("undertide_spawn", () -> new UndertideSpawnBlock());
	public static final RegistryObject<Block> DEEP_SEAGRASS = REGISTRY.register("deep_seagrass", () -> new DeepSeagrassBlock());
	public static final RegistryObject<Block> SEA_TRAIL_STOP = REGISTRY.register("sea_trail_stop", () -> new SeaTrailStopBlock());
	public static final RegistryObject<Block> HIGHMORE_SPAWNBLOCK = REGISTRY.register("highmore_spawnblock", () -> new HighmoreSpawnblockBlock());
	public static final RegistryObject<Block> CRISIS_TABLE = REGISTRY.register("crisis_table", () -> new CrisisTableBlock());
	public static final RegistryObject<Block> FAX = REGISTRY.register("fax", () -> new FaxBlock());
	public static final RegistryObject<Block> HIGHMORE_SPAWNING_BLOCK = REGISTRY.register("highmore_spawning_block", () -> new HighmoreSpawningBlockBlock());
	public static final RegistryObject<Block> GOLDEN_CHALISE = REGISTRY.register("golden_chalise", () -> new GoldenChaliseBlock());
	public static final RegistryObject<Block> EMERGENCY_AID_BUILDING = REGISTRY.register("emergency_aid_building", () -> new EmergencyAidBuildingBlock());
	public static final RegistryObject<Block> EMERGENCY_AID_BUILDING_SALVIENTO = REGISTRY.register("emergency_aid_building_salviento", () -> new EmergencyAidBuildingSalvientoBlock());
	public static final RegistryObject<Block> MIZUKI_STATUE = REGISTRY.register("mizuki_statue", () -> new MizukiStatueBlock());
	public static final RegistryObject<Block> POCKET_SEA_DOLL = REGISTRY.register("pocket_sea_doll", () -> new PocketSeaDollBlock());
	public static final RegistryObject<Block> SWARMCALLER_DOLL = REGISTRY.register("swarmcaller_doll", () -> new SwarmcallerDollBlock());
	public static final RegistryObject<Block> STONECUTTER_DOLL = REGISTRY.register("stonecutter_doll", () -> new StonecutterDollBlock());
	public static final RegistryObject<Block> NETHERSEA_SOUL_SAND = REGISTRY.register("nethersea_soul_sand", () -> new NetherseaSoulSandBlock());
	public static final RegistryObject<Block> CAERULA_BOOK_SHELF = REGISTRY.register("caerula_book_shelf", () -> new CaerulaBookShelfBlock());
	public static final RegistryObject<Block> ABANDONED_SULPTURE = REGISTRY.register("abandoned_sulpture", () -> new AbandonedSulptureBlock());
	public static final RegistryObject<Block> ENDSPEAKER_NEST = REGISTRY.register("endspeaker_nest", () -> new EndspeakerNestBlock());
	public static final RegistryObject<Block> OPERATION_TABLE = REGISTRY.register("operation_table", () -> new OperationTableBlock());
	public static final RegistryObject<Block> CENTRIFUGER = REGISTRY.register("centrifuger", () -> new CentrifugerBlock());
	public static final RegistryObject<Block> INJECTOR = REGISTRY.register("injector", () -> new InjectorBlock());
	public static final RegistryObject<Block> NETHERSEA_WOOD = REGISTRY.register("nethersea_wood", () -> new NetherseaWoodBlock());
	public static final RegistryObject<Block> STRIPPED_NETHERSEA_WOOD = REGISTRY.register("stripped_nethersea_wood", () -> new StrippedNetherseaWoodBlock());
	public static final RegistryObject<Block> ISHARMLA_REMAIN = REGISTRY.register("isharmla_remain", () -> new IsharmlaRemainBlock());
	public static final RegistryObject<Block> AEGIR_GLASS_DECO = REGISTRY.register("aegir_glass_deco", () -> new AegirGlassDecoBlock());
	public static final RegistryObject<Block> AEGIR_GLASS_BAR = REGISTRY.register("aegir_glass_bar", () -> new AegirGlassBarBlock());
	public static final RegistryObject<Block> AEGIR_GLASS_ARCH = REGISTRY.register("aegir_glass_arch", () -> new AegirGlassArchBlock());
	public static final RegistryObject<Block> SALTWIND_SMOOTH_STAIR = REGISTRY.register("saltwind_smooth_stair", () -> new SaltwindSmoothStairBlock());
	public static final RegistryObject<Block> ILLUSIONER_BANNER = REGISTRY.register("illusioner_banner", () -> new IllusionerBannerBlock());
	public static final RegistryObject<Block> LIVING_ARMORSTAND = REGISTRY.register("living_armorstand", () -> new LivingArmorstandBlock());
	public static final RegistryObject<Block> TRAILRITE_ARMORSTAND = REGISTRY.register("trailrite_armorstand", () -> new TrailriteArmorstandBlock());
	public static final RegistryObject<Block> ISHARMLA_BRICK = REGISTRY.register("isharmla_brick", () -> new IsharmlaBrickBlock());
	public static final RegistryObject<Block> ISHARMLA_BRICK_PILLAR = REGISTRY.register("isharmla_brick_pillar", () -> new IsharmlaBrickPillarBlock());
	public static final RegistryObject<Block> ISHARMLA_BRICK_CHIESLED = REGISTRY.register("isharmla_brick_chiesled", () -> new IsharmlaBrickChiesledBlock());
	public static final RegistryObject<Block> ISHARMLA_BRICK_GILDED = REGISTRY.register("isharmla_brick_gilded", () -> new IsharmlaBrickGildedBlock());
	public static final RegistryObject<Block> ISHARMLA_SLAB = REGISTRY.register("isharmla_slab", () -> new IsharmlaSlabBlock());
	public static final RegistryObject<Block> ISHARMLA_STAIR = REGISTRY.register("isharmla_stair", () -> new IsharmlaStairBlock());
	public static final RegistryObject<Block> ISHARMLA_WALL = REGISTRY.register("isharmla_wall", () -> new IsharmlaWallBlock());
	public static final RegistryObject<Block> ISHARMLA_WALL_CHIESLED = REGISTRY.register("isharmla_wall_chiesled", () -> new IsharmlaWallChiesledBlock());
	public static final RegistryObject<Block> ISHARMLA_WALL_GILDED = REGISTRY.register("isharmla_wall_gilded", () -> new IsharmlaWallGildedBlock());
	public static final RegistryObject<Block> DRAGON_BRAND = REGISTRY.register("dragon_brand", () -> new DragonBrandBlock());
	public static final RegistryObject<Block> ENDERINA_CORE = REGISTRY.register("enderina_core", () -> new EnderinaCoreBlock());
	public static final RegistryObject<Block> THIRST_CORAL = REGISTRY.register("thirst_coral", () -> new ThirstCoralBlock());
	public static final RegistryObject<Block> NETHERSEA_SAMPLING = REGISTRY.register("nethersea_sampling", () -> new NetherseaSamplingBlock());
	// Start of user code block custom blocks
	// End of user code block custom blocks
}
