/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package com.apocalypse.caerulaarbor.init;

import com.apocalypse.caerulaarbor.CaerulaArborMod;
import com.apocalypse.caerulaarbor.block.display.*;
import com.apocalypse.caerulaarbor.item.*;
import com.apocalypse.caerulaarbor.utils.EntityUtils;
import net.minecraft.client.renderer.item.ItemProperties;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.food.FoodProperties;
import net.minecraft.world.item.*;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.common.ForgeSpawnEggItem;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
public class CaerulaArborModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, CaerulaArborMod.MODID);
	public static final RegistryObject<Item> CAERULA_RECORDER = REGISTRY.register("caerula_recorder", () -> new CaerulaRecorderItem());
	public static final RegistryObject<Item> RELIC_CURSE_EMELIGHT = REGISTRY.register("relic_curse_emelight", () -> new RelicCurseEMELIGHTItem());
	public static final RegistryObject<Item> EMERGENCY_LIGHT = block(CaerulaArborModBlocks.EMERGENCY_LIGHT);
	public static final RegistryObject<Item> RELIC_CURSED_GLOWBODY = REGISTRY.register("relic_cursed_glowbody", () -> new RelicCursedGLOWBODYItem());
	public static final RegistryObject<Item> RELIC_CURSED_RESEARCH = REGISTRY.register("relic_cursed_research", () -> new RelicCursedRESEARCHItem());
	public static final RegistryObject<Item> RELIC_CROWN = REGISTRY.register("relic_crown", () -> new RelicCROWNItem());
	public static final RegistryObject<Item> KINGS_ARMOUR = REGISTRY.register("kings_armour", () -> new KingsArmourItem());
	public static final RegistryObject<Item> KINGS_ARMOR = block(CaerulaArborModBlocks.KINGS_ARMOR);
	public static final RegistryObject<Item> BLOCK_CROWN = block(CaerulaArborModBlocks.BLOCK_CROWN);
	public static final RegistryObject<Item> KINGS_SPEAR = REGISTRY.register("kings_spear", () -> new KingsSpearItem());
	public static final RegistryObject<Item> BLOCK_SPEAR = block(CaerulaArborModBlocks.BLOCK_SPEAR);
	public static final RegistryObject<Item> KINGS_EXTENSION = REGISTRY.register("kings_extension", () -> new KingsExtensionItem());
	public static final RegistryObject<Item> BLOCK_EXTENSION = block(CaerulaArborModBlocks.BLOCK_EXTENSION);
	public static final RegistryObject<Item> KINGS_CRYSTAL = REGISTRY.register("kings_crystal", () -> new KingsCrystalItem());
	public static final RegistryObject<Item> BLOCK_CRYSTAL = block(CaerulaArborModBlocks.BLOCK_CRYSTAL);
	public static final RegistryObject<Item> REDSTONE_INGOT = REGISTRY.register("redstone_ingot", () -> new Item(new Item.Properties().stacksTo(64).rarity(Rarity.COMMON)));
	public static final RegistryObject<Item> THE_SPEAR = REGISTRY.register("the_spear", () -> new TheSpearItem());
	public static final RegistryObject<Item> WEARABLE_CHEST_CHESTPLATE = REGISTRY.register("wearable_chest_chestplate", () -> new WearableChestItem.Chestplate());
	public static final RegistryObject<WearableCrownItem> WEARABLE_CROWN_HELMET = REGISTRY.register("wearable_crown_helmet", () -> new WearableCrownItem(ArmorItem.Type.HELMET, new Item.Properties().fireResistant()));
	public static final RegistryObject<Item> HAND_OF_THORNS = REGISTRY.register("hand_of_thorns", () -> new HandOfThornsItem());
	public static final RegistryObject<Item> HAND_OF_STRANGLE = REGISTRY.register("hand_of_strangle", () -> new HandOfStrangleItem());
	public static final RegistryObject<Item> HAND_OF_FERTILIY = REGISTRY.register("hand_of_fertiliy", () -> new HandOfFertiliyItem());
	public static final RegistryObject<Item> HAND_OF_SPEED = REGISTRY.register("hand_of_speed", () -> new HandOfSpeedItem());
	public static final RegistryObject<Item> HAND_OF_BARREN = REGISTRY.register("hand_of_barren", () -> new HandOfBarrenItem());
	public static final RegistryObject<Item> FLUORE_BERRIES = REGISTRY.register("fluore_berries", () -> new FluoreBerriesItem());
	public static final RegistryObject<Item> RADIANT_BERRIES = REGISTRY.register("radiant_berries", () -> new RadiantBerriesItem());
	public static final RegistryObject<Item> HAND_OF_SPOTLESS = REGISTRY.register("hand_of_spotless", () -> new HandOfSwipeItem());
	public static final RegistryObject<Item> ARCHFIENDS_ARTIFACT = REGISTRY.register("archfiends_artifact", () -> new ArchfiendsArtifactItem());
	public static final RegistryObject<Item> HAND_OF_FIREWORK = REGISTRY.register("hand_of_firework", () -> new HandOfFireworkItem());
	public static final RegistryObject<Item> ARCHFIENDS_FLAG = REGISTRY.register("archfiends_flag", () -> new ArchfiendsFlagItem());
	public static final RegistryObject<Item> HAND_OF_ENGRAVE = REGISTRY.register("hand_of_engrave", () -> new HandOfEngraveItem());
	public static final RegistryObject<Item> ARCHFIENDS_BED = REGISTRY.register("archfiends_bed", () -> new ArchfiendsBedItem());
	public static final RegistryObject<Item> SURVIVOR_CONTRACT = REGISTRY.register("survivor_contract", () -> new SurvivorContractItem());
	public static final RegistryObject<Item> ROYAL_FATE = REGISTRY.register("royal_fate", () -> new RoyalFateItem());
	public static final RegistryObject<Item> BLOCK_FATE = block(CaerulaArborModBlocks.BLOCK_FATE);
	public static final RegistryObject<Item> CRIMSON_TREATY = REGISTRY.register("crimson_treaty", () -> new CrimsonTreatyItem());
	public static final RegistryObject<Item> MEAT_CAN = REGISTRY.register("meat_can", () -> new MeatCanItem());
	public static final RegistryObject<Item> EMPTY_CAN = REGISTRY.register("empty_can", () -> new EmptyCanItem());
	public static final RegistryObject<Item> BOWL_SEAGRASS = REGISTRY.register("bowl_seagrass", () -> new BowlSeagrassItem());
	public static final RegistryObject<Item> GOLDEN_STORM = REGISTRY.register("golden_storm", () -> new GoldenStormItem());
	public static final RegistryObject<Item> PAPER_BAG = REGISTRY.register("paper_bag", () -> new Item(new Item.Properties().stacksTo(64).rarity(Rarity.COMMON)));
	public static final RegistryObject<Item> COFFEE_CANDY = REGISTRY.register("coffee_candy", () -> new CoffeeCandyItem());
	public static final RegistryObject<Item> CAFFEINE = REGISTRY.register("caffeine", () -> new CaffeineItem());
	public static final RegistryObject<Item> CANNED_CHERRY = REGISTRY.register("canned_cherry", () -> new CannedCherryItem());
	public static final RegistryObject<Item> BERRY_CAN = block(CaerulaArborModBlocks.BERRY_CAN);
	public static final RegistryObject<Item> RAINBOW_CANDY = REGISTRY.register("rainbow_candy", () -> new RainbowCandyItem());
	public static final RegistryObject<Item> AROMATIC_COFFEE = REGISTRY.register("aromatic_coffee", () -> new AromaticCoffeeItem());
	public static final RegistryObject<Item> SOLO_MUSIC_BOX = REGISTRY.register("solo_music_box", () -> new SoloMusicBoxItem());
	public static final RegistryObject<Item> MUSIC_BOX_FIXED = REGISTRY.register("music_box_fixed", () -> new MusicBoxFixedItem());
	public static final RegistryObject<Item> REDSTONE_IRIS = block(CaerulaArborModBlocks.REDSTONE_IRIS);
	public static final RegistryObject<Item> REDSTONE_IRIS_FLOWER = REGISTRY.register("redstone_iris_flower", () -> new RedstoneIrisFlowerItem());
	public static final RegistryObject<Item> REDSTONEIRIS_SEEDING = block(CaerulaArborModBlocks.REDSTONEIRIS_SEEDING);
	public static final RegistryObject<Item> ODD_FLUTE = REGISTRY.register("odd_flute", () -> new OddFluteItem());
	public static final RegistryObject<Item> VOYAGE_OF_GOLD = REGISTRY.register("voyage_of_gold", () -> new VoyageOfGoldItem());
	public static final RegistryObject<Item> THERMOGRAPH = REGISTRY.register("thermograph", () -> new ThermographItem());
	public static final RegistryObject<Item> PIGLIN_DIARY = REGISTRY.register("piglin_diary", () -> new PiglinDiaryItem());
	public static final RegistryObject<Item> TOPONYM_TEXTOLOGY = REGISTRY.register("toponym_textology", () -> new ToponymTextologyItem());
	public static final RegistryObject<Item> RUN_FISH_SPAWN_EGG = REGISTRY.register("run_fish_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.RUN_FISH, -16777012, -3355444, new Item.Properties()));
	public static final RegistryObject<Item> SLIDER_FISH_SPAWN_EGG = REGISTRY.register("slider_fish_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.SLIDER_FISH, -13421569, -3355444, new Item.Properties()));
	public static final RegistryObject<Item> SUPER_SLIDER_SPAWN_EGG = REGISTRY.register("super_slider_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.SUPER_SLIDER, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> SHOOTER_FISH_SPAWN_EGG = REGISTRY.register("shooter_fish_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.SHOOTER_FISH, -13434676, -3355444, new Item.Properties()));
	public static final RegistryObject<Item> FLY_FISH_SPAWN_EGG = REGISTRY.register("fly_fish_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.FLY_FISH, -16737895, -3355444, new Item.Properties()));
	public static final RegistryObject<Item> REAPER_FISH_SPAWN_EGG = REGISTRY.register("reaper_fish_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.REAPER_FISH, -6710785, -3355444, new Item.Properties()));
	public static final RegistryObject<Item> CREEPER_FISH_SPAWN_EGG = REGISTRY.register("creeper_fish_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.CREEPER_FISH, -10092442, -3342337, new Item.Properties()));
	public static final RegistryObject<Item> PUNCTURE_FISH_SPAWN_EGG = REGISTRY.register("puncture_fish_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.PUNCTURE_FISH, -16750900, -1, new Item.Properties()));
	public static final RegistryObject<Item> SEA_TRAIL_INIT = block(CaerulaArborModBlocks.SEA_TRAIL_INIT);
	public static final RegistryObject<Item> SEA_TRAIL_GROWING = block(CaerulaArborModBlocks.SEA_TRAIL_GROWING);
	public static final RegistryObject<Item> SEA_TRAIL_GROWN = block(CaerulaArborModBlocks.SEA_TRAIL_GROWN);
	public static final RegistryObject<Item> SEA_TRAIL_MOR = REGISTRY.register("sea_trail_mor", () -> new SeaTrailMorItem());
	public static final RegistryObject<Item> BOMB_TRAILER = block(CaerulaArborModBlocks.BOMB_TRAILER);
	public static final RegistryObject<Item> CANNED_WATER = REGISTRY.register("canned_water", () -> new CannedWaterItem());
	public static final RegistryObject<Item> CANNED_LAVA = REGISTRY.register("canned_lava", () -> new CannedLavaItem());
	public static final RegistryObject<Item> BONE_SHARD = REGISTRY.register("bone_shard", () -> new BoneShardItem());
	public static final RegistryObject<Item> OCEAN_PHLOEM = REGISTRY.register("ocean_phloem", () -> new OceanPhloemItem());
	public static final RegistryObject<Item> OCEAN_FIBRE = REGISTRY.register("ocean_fibre", () -> new OceanFibreItem());
	public static final RegistryObject<Item> OCEAN_EYE = REGISTRY.register("ocean_eye", () -> new OceanEyeItem());
	public static final RegistryObject<Item> OCEAN_CRYSTAL = REGISTRY.register("ocean_crystal", () -> new OceanCrystalItem());
	public static final RegistryObject<Item> OCEAN_CUTIN = REGISTRY.register("ocean_cutin", () -> new OceanCutinItem());
	public static final RegistryObject<Item> COOKED_FIBRE = REGISTRY.register("cooked_fibre", () -> new Item(new Item.Properties().stacksTo(64).rarity(Rarity.COMMON).food((new FoodProperties.Builder()).nutrition(6).saturationMod(0.5f).meat().build())));
	public static final RegistryObject<Item> BASELAYER_ABYSSAL_SPAWN_EGG = REGISTRY.register("baselayer_abyssal_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.BASELAYER_ABYSSAL, -16776961, -2056595, new Item.Properties()));
	public static final RegistryObject<Item> OCEAN_GLASS = block(CaerulaArborModBlocks.OCEAN_GLASS);
	public static final RegistryObject<Item> OCEAN_GLASSPANE = block(CaerulaArborModBlocks.OCEAN_GLASSPANE);
	public static final RegistryObject<Item> OCEAN_CHITIN = REGISTRY.register("ocean_chitin", () -> new OceanChitinItem());
	public static final RegistryObject<Item> CHITIN_BLOCK = block(CaerulaArborModBlocks.CHITIN_BLOCK);
	public static final RegistryObject<Item> COOKED_MOR = REGISTRY.register("cooked_mor", () -> new CookedMorItem());
	public static final RegistryObject<Item> SWORD_OCEAN_CRYSTAL = REGISTRY.register("sword_ocean_crystal", () -> new SwordOceanCrystalItem());
	public static final RegistryObject<Item> CHITIN_ARMOR_HELMET = REGISTRY.register("chitin_armor_helmet", () -> new ChitinArmorItem.Helmet());
	public static final RegistryObject<Item> CHITIN_ARMOR_CHESTPLATE = REGISTRY.register("chitin_armor_chestplate", () -> new ChitinArmorItem.Chestplate());
	public static final RegistryObject<Item> CHITIN_ARMOR_LEGGINGS = REGISTRY.register("chitin_armor_leggings", () -> new ChitinArmorItem.Leggings());
	public static final RegistryObject<Item> CHITIN_ARMOR_BOOTS = REGISTRY.register("chitin_armor_boots", () -> new ChitinArmorItem.Boots());
	public static final RegistryObject<Item> CHITIN_PICKAXE = REGISTRY.register("chitin_pickaxe", () -> new ChitinPickaxeItem());
	public static final RegistryObject<Item> CHITIN_AXE = REGISTRY.register("chitin_axe", () -> new ChitinAxeItem());
	public static final RegistryObject<Item> CHITIN_SHOVEL = REGISTRY.register("chitin_shovel", () -> new ChitinShovelItem());
	public static final RegistryObject<Item> CHITIN_HOE = REGISTRY.register("chitin_hoe", () -> new ChitinHoeItem());
	public static final RegistryObject<Item> CHITIN_SWORD = REGISTRY.register("chitin_sword", () -> new ChitinSwordItem());
	public static final RegistryObject<Item> PICKAXE_OCEAN_CRYSTAL = REGISTRY.register("pickaxe_ocean_crystal", () -> new OceanthornPickaxeItem());
	public static final RegistryObject<Item> AXE_OCEAN_CRYSTAL = REGISTRY.register("axe_ocean_crystal", () -> new OceanthornAxeItem());
	public static final RegistryObject<Item> SHOVEL_OCEAN_CRYSTAL = REGISTRY.register("shovel_ocean_crystal", () -> new OceanthornShovelItem());
	public static final RegistryObject<Item> HOE_OCEAN_CRYSTAL = REGISTRY.register("hoe_ocean_crystal", () -> new OceanthornHoeItem());
	public static final RegistryObject<Item> CUTIN_STICK = REGISTRY.register("cutin_stick", () -> new Item(new Item.Properties().stacksTo(64).rarity(Rarity.COMMON)));
	public static final RegistryObject<Item> PREDATOR_ABYSSAL_SPAWN_EGG = REGISTRY.register("predator_abyssal_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.PREDATOR_ABYSSAL, -16777063, -2056595, new Item.Properties()));
	public static final RegistryObject<Item> KETTLE = REGISTRY.register("kettle", () -> new KettleItem());
	public static final RegistryObject<Item> BLOCK_KETTLE = block(CaerulaArborModBlocks.BLOCK_KETTLE);
	public static final RegistryObject<Item> INSTANT_NOODLE = REGISTRY.register("instant_noodle", () -> new Item(new Item.Properties().stacksTo(64).rarity(Rarity.COMMON).food((new FoodProperties.Builder()).nutrition(2).saturationMod(0.25f).build())));
	public static final RegistryObject<Item> CANNED_NOODLE = REGISTRY.register("canned_noodle", () -> new CannedNoodleItem());
	public static final RegistryObject<Item> CANNED_BOILED_WATER = REGISTRY.register("canned_boiled_water", () -> new CannedBoiledWaterItem());
	public static final RegistryObject<Item> OBISIDIAN_BALL = REGISTRY.register("obisidian_ball", () -> new Item(new Item.Properties().stacksTo(64).rarity(Rarity.COMMON)));
	public static final RegistryObject<Item> CHITIN_KNIFE = REGISTRY.register("chitin_knife", () -> new ChitinKnifeItem());
	public static final RegistryObject<Item> COMPLEX_CHITIN = REGISTRY.register("complex_chitin", () -> new ComplexChitinItem());
	public static final RegistryObject<Item> COMPLEX_CHITIN_SWORD = REGISTRY.register("complex_chitin_sword", () -> new ComplexChitinSwordItem());
	public static final RegistryObject<Item> OCEAN_TRIM_TEMPLATE = REGISTRY.register("ocean_trim_template", () -> new OceanTrimTemplateItem());
	public static final RegistryObject<Item> COMPLEX_CHITIN_PICKAXE = REGISTRY.register("complex_chitin_pickaxe", () -> new ComplexChitinPickaxeItem());
	public static final RegistryObject<Item> COMPLEX_CHITIN_AXE = REGISTRY.register("complex_chitin_axe", () -> new ComplexChitinAxeItem());
	public static final RegistryObject<Item> COMPLEX_CHITIN_SHOVEL = REGISTRY.register("complex_chitin_shovel", () -> new ComplexChitinShovelItem());
	public static final RegistryObject<Item> COMPLEX_CHITIN_HOE = REGISTRY.register("complex_chitin_hoe", () -> new ComplexChitinHoeItem());
	public static final RegistryObject<Item> OCEAN_FARMLAND = block(CaerulaArborModBlocks.OCEAN_FARMLAND);
	public static final RegistryObject<Item> PHLOEM_BOW = REGISTRY.register("phloem_bow", () -> new PhloemBowItem());
	public static final RegistryObject<Item> LEGENDARY_SPEAR = REGISTRY.register("legendary_spear", () -> new LegendarySpearItem());
	public static final RegistryObject<Item> ALLAY_SCULPTURE = REGISTRY.register("allay_sculpture", () -> new AlleySculptureItem());
	public static final RegistryObject<Item> ALLAY_BLOCK = block(CaerulaArborModBlocks.ALLAY_BLOCK);
	public static final RegistryObject<Item> BAT_BED = REGISTRY.register("bat_bed", () -> new BatBedItem());
	public static final RegistryObject<Item> BLOCK_BATBED = block(CaerulaArborModBlocks.BLOCK_BATBED);
	public static final RegistryObject<Item> BATBED_UPPER = block(CaerulaArborModBlocks.BATBED_UPPER);
	public static final RegistryObject<Item> PROOF_OF_LONGEVITY = REGISTRY.register("proof_of_longevity", () -> new ProofOfLongevityItem());
	public static final RegistryObject<Item> OMNI_KEY = REGISTRY.register("omni_key", () -> new OmniKeyItem());
	public static final RegistryObject<Item> SCORE = REGISTRY.register("score", () -> new ScoreItem());
	public static final RegistryObject<Item> RESCISSION = REGISTRY.register("rescission", () -> new RescissionItem());
	public static final RegistryObject<Item> LANGUAGE_KEY = REGISTRY.register("language_key", () -> new LanguageKeyItem());
	public static final RegistryObject<Item> TRAIL_CAKE = block(CaerulaArborModBlocks.TRAIL_CAKE);
	public static final RegistryObject<Item> TRAIL_CAKE_PIECE = REGISTRY.register("trail_cake_piece", () -> new TrailCakePieceItem());
	public static final RegistryObject<Item> CARAMEL_CAKE = block(CaerulaArborModBlocks.CARAMEL_CAKE);
	public static final RegistryObject<Item> CARAMEL_CAKE_PIECE = REGISTRY.register("caramel_cake_piece", () -> new CaramelCakePieceItem());
	public static final RegistryObject<Item> CARAMEL_MOR = REGISTRY.register("caramel_mor", () -> new CaramelMorItem());
	public static final RegistryObject<Item> GUIDE_ABYSSAL_SPAWN_EGG = REGISTRY.register("guide_abyssal_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.GUIDE_ABYSSAL, -13434778, -2056595, new Item.Properties()));
	public static final RegistryObject<Item> SPLASHER_ABYSSAL_SPAWN_EGG = REGISTRY.register("splasher_abyssal_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.SPLASHER_ABYSSAL, -16777012, -2056595, new Item.Properties()));
	public static final RegistryObject<Item> FAKE_EGG = REGISTRY.register("fake_egg", () -> new FakeEggItem());
	public static final RegistryObject<Item> REAL_EGG = REGISTRY.register("real_egg", () -> new Item(new Item.Properties().stacksTo(64).rarity(Rarity.COMMON).food((new FoodProperties.Builder()).nutrition(4).saturationMod(0.5f).meat().build())));
	public static final RegistryObject<Item> FERMENTED_OCEAN_EYE = REGISTRY.register("fermented_ocean_eye", () -> new FermentedOceanEyeItem());
	public static final RegistryObject<Item> OCEAN_MACHINE = REGISTRY.register("ocean_machine", () -> new Item(new Item.Properties().stacksTo(64).fireResistant().rarity(Rarity.UNCOMMON)));
	public static final RegistryObject<Item> OCEAN_CRYSTAL_BLOCK = block(CaerulaArborModBlocks.OCEAN_CRYSTAL_BLOCK);
	public static final RegistryObject<Item> COMPLEX_CHITIN_BLOCK = block(CaerulaArborModBlocks.COMPLEX_CHITIN_BLOCK);
	public static final RegistryObject<Item> GUARDIAN_STARE = REGISTRY.register("guardian_stare", () -> new GuardianStareItem());
	public static final RegistryObject<Item> HAND_SWORD = REGISTRY.register("hand_sword", () -> new HandSwordItem());
	public static final RegistryObject<Item> TIDE_OBSERVATION = block(CaerulaArborModBlocks.TIDE_OBSERVATION);
	public static final RegistryObject<Item> SAMPLE_SUBSISTING = REGISTRY.register("sample_subsisting", () -> new SampleSubsistingItem());
	public static final RegistryObject<Item> SAMPLE_GROW = REGISTRY.register("sample_grow", () -> new SampleGrowItem());
	public static final RegistryObject<Item> SAMPLE_BREED = REGISTRY.register("sample_breed", () -> new SampleBreedItem());
	public static final RegistryObject<Item> SAMPLE_MIGRATION = REGISTRY.register("sample_migration", () -> new SampleMigrationItem());
	public static final RegistryObject<Item> ANCHOR_LOWER = block(CaerulaArborModBlocks.ANCHOR_LOWER);
	public static final RegistryObject<Item> ANCHOR_MEDIUM = block(CaerulaArborModBlocks.ANCHOR_MEDIUM);
	public static final RegistryObject<Item> ANCHOR_UPPER = block(CaerulaArborModBlocks.ANCHOR_UPPER);
	public static final RegistryObject<Item> UMBRELLA_ABYSSAL_SPAWN_EGG = REGISTRY.register("umbrella_abyssal_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.UMBRELLA_ABYSSAL, -10066177, -2056595, new Item.Properties()));
	public static final RegistryObject<Item> TRAILED_WOODEN_SWORD = REGISTRY.register("trailed_wooden_sword", () -> new TrailedWoodenSwordItem());
	public static final RegistryObject<Item> TRAILED_STONE_SWORD = REGISTRY.register("trailed_stone_sword", () -> new TrailedStoneSwordItem());
	public static final RegistryObject<Item> TRAILED_IRON_SWORD = REGISTRY.register("trailed_iron_sword", () -> new TrailedIronSwordItem());
	public static final RegistryObject<Item> TRAILED_DIAMOND_SWORD = REGISTRY.register("trailed_diamond_sword", () -> new TrailedDiamondSwordItem());
	public static final RegistryObject<Item> TRAILED_NETHERITE_SWORD = REGISTRY.register("trailed_netherite_sword", () -> new TrailedNetheriteSwordItem());
	public static final RegistryObject<Item> TRAILED_GOLDEN_SWORD = REGISTRY.register("trailed_golden_sword", () -> new TrailedGoldenSwordItem());
	public static final RegistryObject<Item> TRAIL_CREAM = REGISTRY.register("trail_cream", () -> new Item(new Item.Properties().stacksTo(64).rarity(Rarity.COMMON)));
	public static final RegistryObject<Item> CRACKER_ABYSSAL_SPAWN_EGG = REGISTRY.register("cracker_abyssal_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.CRACKER_ABYSSAL, -16436298, -2056595, new Item.Properties()));
	public static final RegistryObject<Item> DISPATCH_STICK = REGISTRY.register("dispatch_stick", () -> new DispatchStickItem());
	public static final RegistryObject<Item> COLLECTOR_PROKARYOTE_SPAWN_EGG = REGISTRY.register("collector_prokaryote_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.COLLECTOR_PROKARYOTE, -16776961, -16316408, new Item.Properties()));
	public static final RegistryObject<Item> BROKEN_OCEAN_CELL = REGISTRY.register("broken_ocean_cell", () -> new BrokenOceanCellItem());
	public static final RegistryObject<Item> BROKEN_CELL_CLUSTER = REGISTRY.register("broken_cell_cluster", () -> new BrokenCellClusterItem());
	public static final RegistryObject<Item> OCEAN_CELL = REGISTRY.register("ocean_cell", () -> new OceanCellItem());
	public static final RegistryObject<Item> CELL_CLUSTER = REGISTRY.register("cell_cluster", () -> new CellClusterItem());
	public static final RegistryObject<Item> COOKED_BROKEN_CELL_CLUSTER = REGISTRY.register("cooked_broken_cell_cluster", () -> new Item(new Item.Properties().stacksTo(64).rarity(Rarity.COMMON).food((new FoodProperties.Builder()).nutrition(6).saturationMod(0.25f).meat().build())));
	public static final RegistryObject<Item> COOKED_CELL_CLUSTER = REGISTRY.register("cooked_cell_cluster", () -> new Item(new Item.Properties().stacksTo(64).rarity(Rarity.COMMON).food((new FoodProperties.Builder()).nutrition(8).saturationMod(0.3f).meat().build())));
	public static final RegistryObject<Item> TRANSFORM_CELL = REGISTRY.register("transform_cell", () -> new TransformCellItem());
	public static final RegistryObject<Item> BONE_FISH_SPAWN_EGG = REGISTRY.register("bone_fish_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.BONE_FISH, -10066177, -1, new Item.Properties()));
	public static final RegistryObject<Item> BLOCK_RECORDER = block(CaerulaArborModBlocks.BLOCK_RECORDER);
	public static final RegistryObject<Item> CHISELER_FISH_SPAWN_EGG = REGISTRY.register("chiseler_fish_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.CHISELER_FISH, -10053121, -1, new Item.Properties()));
	public static final RegistryObject<Item> PREGNANT_FISH_SPAWN_EGG = REGISTRY.register("pregnant_fish_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.PREGNANT_FISH, -10066177, -404566, new Item.Properties()));
	public static final RegistryObject<Item> FAKE_OFFSPRING_SPAWN_EGG = REGISTRY.register("fake_offspring_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.FAKE_OFFSPRING, -856596, -6711916, new Item.Properties()));
	public static final RegistryObject<Item> FLEE_FISH_SPAWN_EGG = REGISTRY.register("flee_fish_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.FLEE_FISH, -16764007, -29083, new Item.Properties()));
	public static final RegistryObject<Item> ROUTE_FRACTAL_SPAWN_EGG = REGISTRY.register("route_fractal_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.ROUTE_FRACTAL, -16711423, -15260869, new Item.Properties()));
	public static final RegistryObject<Item> SEA_TRAIL_SOLID = block(CaerulaArborModBlocks.SEA_TRAIL_SOLID);
	public static final RegistryObject<Item> TRAIL_BRICK = block(CaerulaArborModBlocks.TRAIL_BRICK);
	public static final RegistryObject<Item> TRAIL_SLAB = block(CaerulaArborModBlocks.TRAIL_SLAB);
	public static final RegistryObject<Item> TRAIL_STAIR = block(CaerulaArborModBlocks.TRAIL_STAIR);
	public static final RegistryObject<Item> TRAIL_BUTTON = block(CaerulaArborModBlocks.TRAIL_BUTTON);
	public static final RegistryObject<Item> TRAIL_PRESSURE_PLATE = block(CaerulaArborModBlocks.TRAIL_PRESSURE_PLATE);
	public static final RegistryObject<Item> TRAIL_TILE = block(CaerulaArborModBlocks.TRAIL_TILE);
	public static final RegistryObject<Item> CAERULA_HEART = REGISTRY.register("caerula_heart", () -> new CaerulaHeartItem());
	public static final RegistryObject<Item> COIN_OF_TRADE = REGISTRY.register("coin_of_trade", () -> new CoinOfTradeItem());
	public static final RegistryObject<Item> OCEAN_PEDUNCLE = REGISTRY.register("ocean_peduncle", () -> new OceanPeduncleItem());
	public static final RegistryObject<Item> ELITE_PEDUNCLE = REGISTRY.register("elite_peduncle", () -> new ElitePeduncleItem());
	public static final RegistryObject<Item> COOKED_PEDUNCLE = REGISTRY.register("cooked_peduncle", () -> new CookedPeduncleItem());
	public static final RegistryObject<Item> OCEAN_ARROW = REGISTRY.register("ocean_arrow", () -> new Item(new Item.Properties().stacksTo(64).rarity(Rarity.COMMON)));
	public static final RegistryObject<Item> FIRST_TO_TALK_SPAWN_EGG = REGISTRY.register("first_to_talk_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.FIRST_TO_TALK, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> REAPER_PET_SPAWN_EGG = REGISTRY.register("reaper_pet_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.REAPER_PET, -6750157, -3355444, new Item.Properties()));
	public static final RegistryObject<Item> OCEAN_EXTRACTOR = REGISTRY.register("ocean_extractor", () -> new OceanExtractorItem());
	public static final RegistryObject<Item> DNA_REAPER = REGISTRY.register("dna_reaper", () -> new DNAReaperItem());
	public static final RegistryObject<Item> REAPER_EGG = block(CaerulaArborModBlocks.REAPER_EGG);
	public static final RegistryObject<Item> BASE_EGG = REGISTRY.register("base_egg", () -> new BaseEggItem());
	public static final RegistryObject<Item> OCEAN_OVARY = block(CaerulaArborModBlocks.OCEAN_OVARY);
	public static final RegistryObject<Item> WHIRL_EYE = REGISTRY.register("whirl_eye", () -> new WhirlEyeItem());
	public static final RegistryObject<Item> OCARINA = REGISTRY.register("ocarina", () -> new OcarinaItem());
	public static final RegistryObject<Item> BOILED_EGG = REGISTRY.register("boiled_egg", () -> new BoiledEggItem());
	public static final RegistryObject<Item> FRIED_EGG = REGISTRY.register("fried_egg", () -> new FriedEggItem());
	public static final RegistryObject<Item> A_SECOND_KEY = REGISTRY.register("a_second_key", () -> new ASecondKeyItem());
	public static final RegistryObject<Item> SEALEATHER_HELMET = REGISTRY.register("sealeather_helmet", () -> new SealeatherItem.Helmet());
	public static final RegistryObject<Item> SEALEATHER_CHESTPLATE = REGISTRY.register("sealeather_chestplate", () -> new SealeatherItem.Chestplate());
	public static final RegistryObject<Item> SEALEATHER_LEGGINGS = REGISTRY.register("sealeather_leggings", () -> new SealeatherItem.Leggings());
	public static final RegistryObject<Item> SEALEATHER_BOOTS = REGISTRY.register("sealeather_boots", () -> new SealeatherItem.Boots());
	public static final RegistryObject<Item> SONS_SPAWN_EGG = REGISTRY.register("sons_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.SONS, -16764058, -1, new Item.Properties()));
	public static final RegistryObject<Item> FLOATER_PROKARYOTE_SPAWN_EGG = REGISTRY.register("floater_prokaryote_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.FLOATER_PROKARYOTE, -16777012, -8483352, new Item.Properties()));
	public static final RegistryObject<Item> CHITIN_GOLEM_SPAWN_EGG = REGISTRY.register("chitin_golem_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.CHITIN_GOLEM, -3629966, -12951147, new Item.Properties()));
	public static final RegistryObject<Item> TRAIL_PUMPKING = block(CaerulaArborModBlocks.TRAIL_PUMPKING);
	public static final RegistryObject<Item> MEGA_CHEST_SPAWN_EGG = REGISTRY.register("mega_chest_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.MEGA_CHEST, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> TRAILRITE = REGISTRY.register("trailrite", () -> new TrailIngotItem());
	public static final RegistryObject<Item> TRAILRITE_AXE = REGISTRY.register("trailrite_axe", () -> new TrailriteAxeItem());
	public static final RegistryObject<Item> BUCKET_RUNFISH = REGISTRY.register("bucket_runfish", () -> new BucketRunfishItem());
	public static final RegistryObject<Item> TRAILRITE_SWORD = REGISTRY.register("trailrite_sword", () -> new TrailriteSwordItem());
	public static final RegistryObject<Item> BUCKET_SLIDER = REGISTRY.register("bucket_slider", () -> new BucketSliderItem());
	public static final RegistryObject<Item> TRAIL_DEBRIS = block(CaerulaArborModBlocks.TRAIL_DEBRIS);
	public static final RegistryObject<Item> TRAIL_SHARD = REGISTRY.register("trail_shard", () -> new TrailShardItem());
	public static final RegistryObject<Item> TRAILRITE_BLOCK = block(CaerulaArborModBlocks.TRAILRITE_BLOCK);
	public static final RegistryObject<Item> APOSTLE_PROKARYOTE_SPAWN_EGG = REGISTRY.register("apostle_prokaryote_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.APOSTLE_PROKARYOTE, -15191057, -3933705, new Item.Properties()));
	public static final RegistryObject<Item> BUCKET_CHISELER = REGISTRY.register("bucket_chiseler", () -> new BucketChiselerItem());
	public static final RegistryObject<Item> BUCKET_FLOATER = REGISTRY.register("bucket_floater", () -> new BucketFloaterItem());
	public static final RegistryObject<Item> BUCKET_BONEFISH = REGISTRY.register("bucket_bonefish", () -> new BucketBonefishItem());
	public static final RegistryObject<Item> BUCKET_COLLECTOR = REGISTRY.register("bucket_collector", () -> new BucketCollectorItem());
	public static final RegistryObject<Item> WAVECLEAVER = REGISTRY.register("wavecleaver", () -> new WavecleaverItem());
	public static final RegistryObject<Item> TRAIL_WALL = block(CaerulaArborModBlocks.TRAIL_WALL);
	public static final RegistryObject<Item> RED_OVARY = block(CaerulaArborModBlocks.RED_OVARY);
	public static final RegistryObject<Item> ACCUMULATOR_PROKARYOTE_SPAWN_EGG = REGISTRY.register("accumulator_prokaryote_spawn_egg",
			() -> new ForgeSpawnEggItem(CaerulaArborModEntities.ACCUMULATOR_PROKARYOTE, -14863367, -15721602, new Item.Properties()));
	public static final RegistryObject<Item> TIDEWAY_CRADLE = REGISTRY.register(CaerulaArborModBlocks.TIDEWAY_CRADLE.getId().getPath(), () -> new TidewayCradleDisplayItem(CaerulaArborModBlocks.TIDEWAY_CRADLE.get(), new Item.Properties()));
	public static final RegistryObject<Item> SMELLY_HEMOSTATIC = REGISTRY.register("smelly_hemostatic", () -> new SmellyHemostaticItem());
	public static final RegistryObject<Item> PATH_INAUGURATOR = REGISTRY.register("path_inaugurator", () -> new PathInauguratorItem());
	public static final RegistryObject<Item> COOKED_FAKEEGG = REGISTRY.register("cooked_fakeegg", () -> new Item(new Item.Properties().stacksTo(64).rarity(Rarity.COMMON).food((new FoodProperties.Builder()).nutrition(4).saturationMod(0.7f).alwaysEat().build())));
	public static final RegistryObject<Item> COLLECTOR_MEAT = REGISTRY.register("collector_meat", () -> new CollectorMeatItem());
	public static final RegistryObject<Item> COOKED_COLLECTOR = REGISTRY.register("cooked_collector", () -> new Item(new Item.Properties().stacksTo(64).rarity(Rarity.COMMON).food((new FoodProperties.Builder()).nutrition(6).saturationMod(0.5f).meat().build())));
	public static final RegistryObject<Item> CLAW = REGISTRY.register("claw", () -> new Item(new Item.Properties().stacksTo(64).rarity(Rarity.COMMON).food((new FoodProperties.Builder()).nutrition(2).saturationMod(0f).build())));
	public static final RegistryObject<Item> COOKED_CLAW = REGISTRY.register("cooked_claw", () -> new CookedClawItem());
	public static final RegistryObject<Item> SEABORN_SOUP = REGISTRY.register("seaborn_soup", () -> new SeabornSoupItem());
	public static final RegistryObject<Item> REPELLER_SHELL = REGISTRY.register("repeller_shell", () -> new RepellerShellItem());
	public static final RegistryObject<Item> FEEDER_PROKARYOTE_SPAWN_EGG = REGISTRY.register("feeder_prokaryote_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.FEEDER_PROKARYOTE, -12698628, -6754314, new Item.Properties()));
	public static final RegistryObject<Item> CHEST_FISH_SPAWN_EGG = REGISTRY.register("chest_fish_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.CHEST_FISH, -8882056, -858389, new Item.Properties()));
	public static final RegistryObject<Item> SPIKE_CHEST_SPAWN_EGG = REGISTRY.register("spike_chest_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.SPIKE_CHEST, -9082259, -533095, new Item.Properties()));
	public static final RegistryObject<Item> HIGHMORE_SCYTHE = REGISTRY.register("highmore_scythe", () -> new HighmoreScytheItem());
	public static final RegistryObject<Item> SALTWIND_SANDSTONE = block(CaerulaArborModBlocks.SALTWIND_SANDSTONE);
	public static final RegistryObject<Item> CHISELED_SALTWIND_SANDSTONE = block(CaerulaArborModBlocks.CHISELED_SALTWIND_SANDSTONE);
	public static final RegistryObject<Item> SMOOTH_SALTWIND_SANDATONE = block(CaerulaArborModBlocks.SMOOTH_SALTWIND_SANDATONE);
	public static final RegistryObject<Item> SALTWIND_SAND_STAIR = block(CaerulaArborModBlocks.SALTWIND_SAND_STAIR);
	public static final RegistryObject<Item> SALTWIND_SAND_SLAB = block(CaerulaArborModBlocks.SALTWIND_SAND_SLAB);
	public static final RegistryObject<Item> SMOOTH_SALTWIND_SAND_STAIR = block(CaerulaArborModBlocks.SMOOTH_SALTWIND_SAND_STAIR);
	public static final RegistryObject<Item> SMOOTH_SALTWIND_SAND_SLAB = block(CaerulaArborModBlocks.SMOOTH_SALTWIND_SAND_SLAB);
	public static final RegistryObject<Item> SALTWIND_SAND_WALL = block(CaerulaArborModBlocks.SALTWIND_SAND_WALL);
	public static final RegistryObject<Item> CHIESELED_SALTWIND_SAND_WALL = block(CaerulaArborModBlocks.CHIESELED_SALTWIND_SAND_WALL);
	public static final RegistryObject<Item> SMOOTH_SALTWIND_SAND_WALL = block(CaerulaArborModBlocks.SMOOTH_SALTWIND_SAND_WALL);
	public static final RegistryObject<Item> TIDE_BISHOP_CORE = block(CaerulaArborModBlocks.TIDE_BISHOP_CORE);
	public static final RegistryObject<Item> ADV_ITEM = REGISTRY.register("adv_item", () -> new Item(new Item.Properties().stacksTo(64).rarity(Rarity.COMMON)));
	public static final RegistryObject<Item> HETEROPIC_PIECE = REGISTRY.register("heteropic_piece", () -> new HeteropicPieceItem());
	public static final RegistryObject<Item> HETEROPIC_BLOCK = block(CaerulaArborModBlocks.HETEROPIC_BLOCK);
	public static final RegistryObject<Item> TRAIL_LOG = block(CaerulaArborModBlocks.TRAIL_LOG);
	public static final RegistryObject<Item> TRAIL_LEAVE = block(CaerulaArborModBlocks.TRAIL_LEAVE);
	public static final RegistryObject<Item> TRAIL_PLANK = block(CaerulaArborModBlocks.TRAIL_PLANK);
	public static final RegistryObject<Item> TRAIL_PLANKS_FENCE = block(CaerulaArborModBlocks.TRAIL_PLANKS_FENCE);
	public static final RegistryObject<Item> TRAIL_PLANK_FENCEDOOR = block(CaerulaArborModBlocks.TRAIL_PLANK_FENCEDOOR);
	public static final RegistryObject<Item> TRAIL_PLANK_SLAB = block(CaerulaArborModBlocks.TRAIL_PLANK_SLAB);
	public static final RegistryObject<Item> TRAIL_PLANK_STAIR = block(CaerulaArborModBlocks.TRAIL_PLANK_STAIR);
	public static final RegistryObject<Item> TRAIL_PLANK_BUTTON = block(CaerulaArborModBlocks.TRAIL_PLANK_BUTTON);
	public static final RegistryObject<Item> TRAIL_PLANK_PRESSURE_PLATE = block(CaerulaArborModBlocks.TRAIL_PLANK_PRESSURE_PLATE);
	public static final RegistryObject<Item> STRIPPED_TRAIL_LOG = block(CaerulaArborModBlocks.STRIPPED_TRAIL_LOG);
	public static final RegistryObject<Item> TIDE_WAND = REGISTRY.register("tide_wand", () -> new TideWandItem());
	public static final RegistryObject<Item> TRAIL_PLANK_DOOR = doubleBlock(CaerulaArborModBlocks.TRAIL_PLANK_DOOR);
	public static final RegistryObject<Item> TRAIL_MOP = REGISTRY.register("trail_mop", () -> new TrailMopItem());
	public static final RegistryObject<Item> BLOODY_RECORD = REGISTRY.register("bloody_record", () -> new RecordItem(9, () -> ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation(CaerulaArborMod.MODID, "bloody_wolf")), new Item.Properties().stacksTo(1).rarity(Rarity.RARE), 3080));
	public static final RegistryObject<Item> SALTSAND = block(CaerulaArborModBlocks.SALTSAND);
	public static final RegistryObject<Item> SKADI_SPAWN_EGG = REGISTRY.register("skadi_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.SKADI, -13289929, -4141862, new Item.Properties()));
	public static final RegistryObject<Item> SEA_TRAIL_BURNT = block(CaerulaArborModBlocks.SEA_TRAIL_BURNT);
	public static final RegistryObject<Item> SEA_TRAIL_BURNT_SOLID = block(CaerulaArborModBlocks.SEA_TRAIL_BURNT_SOLID);
	public static final RegistryObject<Item> REDSTONIUM = REGISTRY.register("redstonium", () -> new Item(new Item.Properties().stacksTo(64).fireResistant().rarity(Rarity.RARE)));
	public static final RegistryObject<Item> TRAIL_POWDER = REGISTRY.register("trail_powder", () -> new TrailPowderItem());
	public static final RegistryObject<Item> TRAIL_POWDER_CORE = REGISTRY.register("trail_powder_core", () -> new TrailPowderCoreItem());
	public static final RegistryObject<Item> HUNTER_GENE = REGISTRY.register("hunter_gene", () -> new HunterGeneItem());
	public static final RegistryObject<Item> CHESTMEGA_SPAWNER = REGISTRY.register(CaerulaArborModBlocks.CHESTMEGA_SPAWNER.getId().getPath(),
			() -> new ChestmegaSpawnerDisplayItem(CaerulaArborModBlocks.CHESTMEGA_SPAWNER.get(), new Item.Properties()));
	public static final RegistryObject<Item> CRACKED_TRAIL_BRICK = block(CaerulaArborModBlocks.CRACKED_TRAIL_BRICK);
	public static final RegistryObject<Item> SALTWIND_COLUMN = block(CaerulaArborModBlocks.SALTWIND_COLUMN);
	public static final RegistryObject<Item> BLOCK_CHESTFISH = block(CaerulaArborModBlocks.BLOCK_CHESTFISH);
	public static final RegistryObject<Item> LANTERN_JUDGEMENT = REGISTRY.register("lantern_judgement", () -> new LanternJudgementItem());
	public static final RegistryObject<Item> WHITE_CHITIN_BLOCK = block(CaerulaArborModBlocks.WHITE_CHITIN_BLOCK);
	public static final RegistryObject<Item> DEPOSITER_PROKARYOTE_SPAWN_EGG = REGISTRY.register("depositer_prokaryote_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.DEPOSITER_PROKARYOTE, -1381662, -10523951, new Item.Properties()));
	public static final RegistryObject<Item> SALTWIND_BRICK = block(CaerulaArborModBlocks.SALTWIND_BRICK);
	public static final RegistryObject<Item> SALTWIND_SMOOTH_BRICK = block(CaerulaArborModBlocks.SALTWIND_SMOOTH_BRICK);
	public static final RegistryObject<Item> SALTWIND_BRICK_SLAB = block(CaerulaArborModBlocks.SALTWIND_BRICK_SLAB);
	public static final RegistryObject<Item> SALTWIND_SMOOTH_SLAB = block(CaerulaArborModBlocks.SALTWIND_SMOOTH_SLAB);
	public static final RegistryObject<Item> SALTWIND_STAIR = block(CaerulaArborModBlocks.SALTWIND_STAIR);
	public static final RegistryObject<Item> WHITE_CHITIN = REGISTRY.register("white_chitin", () -> new WhiteChitinItem());
	public static final RegistryObject<ChitinComplexItem> COMPLEXCHITIN_ARMOR_HELMET = REGISTRY.register("complexchitin_armor_helmet", () -> new ChitinComplexItem(ArmorItem.Type.HELMET, new Item.Properties().fireResistant()));
	public static final RegistryObject<ChitinComplexItem> COMPLEXCHITIN_ARMOR_CHESTPLATE = REGISTRY.register("complexchitin_armor_chestplate", () -> new ChitinComplexItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().fireResistant()));
	public static final RegistryObject<ChitinComplexItem> COMPLEXCHITIN_ARMOR_LEGGINGS = REGISTRY.register("complexchitin_armor_leggings", () -> new ChitinComplexItem(ArmorItem.Type.LEGGINGS, new Item.Properties().fireResistant()));
	public static final RegistryObject<ChitinComplexItem> COMPLEXCHITIN_ARMOR_BOOTS = REGISTRY.register("complexchitin_armor_boots", () -> new ChitinComplexItem(ArmorItem.Type.BOOTS, new Item.Properties().fireResistant()));
	public static final RegistryObject<Item> TRAIL_WOOD_TRAPDOOR = block(CaerulaArborModBlocks.TRAIL_WOOD_TRAPDOOR);
	public static final RegistryObject<Item> TRAIL_STONE = block(CaerulaArborModBlocks.TRAIL_STONE);
	public static final RegistryObject<Item> TRAIL_PULSE = block(CaerulaArborModBlocks.TRAIL_PULSE);
	public static final RegistryObject<Item> OCEANIZED_VILLAGER_SPAWN_EGG = REGISTRY.register("oceanized_villager_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.OCEANIZED_VILLAGER, -12431264, -5598838, new Item.Properties()));
	public static final RegistryObject<Item> OCEANIZED_VINDICATOR_SPAWN_EGG = REGISTRY.register("oceanized_vindicator_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.OCEANIZED_VINDICATOR, -6907484, -16632259, new Item.Properties()));
	public static final RegistryObject<Item> OCEANIZED_PILLAGER_SPAWN_EGG = REGISTRY.register("oceanized_pillager_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.OCEANIZED_PILLAGER, -15913406, -6907486, new Item.Properties()));
	public static final RegistryObject<Item> UNAMBIGUOUS_DIRECTION = REGISTRY.register("unambiguous_direction", () -> new UnambiguousDirectionItem());
	public static final RegistryObject<Item> OCEANIZED_PIG_SPAWN_EGG = REGISTRY.register("oceanized_pig_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.OCEANIZED_PIG, -4088402, -6327133, new Item.Properties()));
	public static final RegistryObject<Item> TRAIL_MUSHROOM = block(CaerulaArborModBlocks.TRAIL_MUSHROOM);
	public static final RegistryObject<Item> OCEANIZED_COW_SPAWN_EGG = REGISTRY.register("oceanized_cow_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.OCEANIZED_COW, -13158343, -6970193, new Item.Properties()));
	public static final RegistryObject<Item> TRAIL_APPLE = REGISTRY.register("trail_apple", () -> new TrailAppleItem());
	public static final RegistryObject<Item> OCEANIZED_SHEEP_SPAWN_EGG = REGISTRY.register("oceanized_sheep_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.OCEANIZED_SHEEP, -2432793, -3028258, new Item.Properties()));
	public static final RegistryObject<Item> VIVIPAROUS_LILY = REGISTRY.register(CaerulaArborModBlocks.VIVIPAROUS_LILY.getId().getPath(), () -> new ViviparousLilyDisplayItem(CaerulaArborModBlocks.VIVIPAROUS_LILY.get(), new Item.Properties()));
	public static final RegistryObject<Item> HUGE_LILY = REGISTRY.register(CaerulaArborModBlocks.HUGE_LILY.getId().getPath(), () -> new HugeLilyDisplayItem(CaerulaArborModBlocks.HUGE_LILY.get(), new Item.Properties()));
	public static final RegistryObject<Item> BOMB_COPPER = block(CaerulaArborModBlocks.BOMB_COPPER);
	public static final RegistryObject<Item> OCEANIZED_HORSE_SPAWN_EGG = REGISTRY.register("oceanized_horse_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.OCEANIZED_HORSE, -10197897, -8355686, new Item.Properties()));
	public static final RegistryObject<Item> PHLOEM_BLOCK = block(CaerulaArborModBlocks.PHLOEM_BLOCK);
	public static final RegistryObject<Item> FIBRE_BLOCK = block(CaerulaArborModBlocks.FIBRE_BLOCK);
	public static final RegistryObject<Item> COOKED_FIBRE_BLOCK = block(CaerulaArborModBlocks.COOKED_FIBRE_BLOCK);
	public static final RegistryObject<Item> UNRIPE_YEARNING = REGISTRY.register("unripe_yearning", () -> new UnripeYearningItem());
	public static final RegistryObject<Item> CIRCULAR_SAW = REGISTRY.register("circular_saw", () -> new CircularSawItem());
	public static final RegistryObject<Item> OCEANIZED_PIGLIN_SPAWN_EGG = REGISTRY.register("oceanized_piglin_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.OCEANIZED_PIGLIN, -10136240, -3168112, new Item.Properties()));
	public static final RegistryObject<Item> OCEANIZED_BRUTE_SPAWN_EGG = REGISTRY.register("oceanized_brute_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.OCEANIZED_BRUTE, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> UNDERTIDE_TABLE = block(CaerulaArborModBlocks.UNDERTIDE_TABLE);
	public static final RegistryObject<Item> UNDERTIDE_SPAWN = block(CaerulaArborModBlocks.UNDERTIDE_SPAWN);
	public static final RegistryObject<Item> OCEANIZED_SPIDER_SPAWN_EGG = REGISTRY.register("oceanized_spider_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.OCEANIZED_SPIDER, -13552063, -16239700, new Item.Properties()));
	public static final RegistryObject<Item> TRAIL_GOLDEN_APPLE = REGISTRY.register("trail_golden_apple", () -> new TrailGoldenAppleItem());
	public static final RegistryObject<Item> ENCHANTED_TRAIL_GOLDEN_APPLE = REGISTRY.register("enchanted_trail_golden_apple", () -> new EnchantedTrailGoldenAppleItem());
	public static final RegistryObject<Item> RULER = REGISTRY.register("ruler", () -> new RulerItem());
	public static final RegistryObject<Item> OCEANIZED_ENDERMAN_SPAWN_EGG = REGISTRY.register("oceanized_enderman_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.OCEANIZED_ENDERMAN, -13878972, -10763556, new Item.Properties()));
	public static final RegistryObject<Item> OCEANIZED_WOLF_SPAWN_EGG = REGISTRY.register("oceanized_wolf_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.OCEANIZED_WOLF, -8420214, -11250088, new Item.Properties()));
	public static final RegistryObject<Item> OCEANIZED_DOG_SPAWN_EGG = REGISTRY.register("oceanized_dog_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.OCEANIZED_DOG, -8420214, -11250088, new Item.Properties()));
	public static final RegistryObject<Item> REJECTION_KEY = REGISTRY.register("rejection_key", () -> new RejectionKeyItem());
	public static final RegistryObject<Item> TULIP_MEDCINE = REGISTRY.register("tulip_medcine", () -> new TulipMedcineItem());
	public static final RegistryObject<Item> IMMUNOSUPPRESSOR = REGISTRY.register("immunosuppressor", () -> new ImmunosuppressorItem());
	public static final RegistryObject<Item> OIL_AND_CREAM = REGISTRY.register("oil_and_cream", () -> new OilAndCreamItem());
	public static final RegistryObject<Item> OCEANIZED_RAVAGER_SPAWN_EGG = REGISTRY.register("oceanized_ravager_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.OCEANIZED_RAVAGER, -10919578, -6771789, new Item.Properties()));
	public static final RegistryObject<Item> OCEANIZED_WITCH_SPAWN_EGG = REGISTRY.register("oceanized_witch_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.OCEANIZED_WITCH, -16176318, -12024617, new Item.Properties()));
	public static final RegistryObject<Item> IZUMIK_OFFSPRING_SPAWN_EGG = REGISTRY.register("izumik_offspring_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.IZUMIK_OFFSPRING, -592138, -405009, new Item.Properties()));
	public static final RegistryObject<Item> DEEP_SEAGRASS = block(CaerulaArborModBlocks.DEEP_SEAGRASS);
	public static final RegistryObject<Item> SEA_TRAIL_STOP = block(CaerulaArborModBlocks.SEA_TRAIL_STOP);
	public static final RegistryObject<Item> WATER_LOGGED_PEARL = REGISTRY.register("water_logged_pearl", () -> new WaterLoggedPearlItem());
	public static final RegistryObject<Item> QUINTUS_SPAWNEGG = REGISTRY.register("quintus_spawnegg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.BISHOP_FISH, -1, -1, new Item.Properties().stacksTo(64).rarity(Rarity.RARE)));
	public static final RegistryObject<Item> PATH_SHAPER_SPAWNEGG = REGISTRY.register("path_shaper_spawnegg", () -> new PathShaperSpawneggItem());
	public static final RegistryObject<Item> TIDE_BISHOP_SPAWNEGG = REGISTRY.register("tide_bishop_spawnegg", () -> new TideBishopSpawneggItem());
	public static final RegistryObject<Item> DEATHREPELLER_SPAWNEGG = REGISTRY.register("deathrepeller_spawnegg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.TIDE_DEATHREPELLER, -1, -1, new Item.Properties().stacksTo(64).rarity(Rarity.UNCOMMON)));
	public static final RegistryObject<Item> HIGHMORE_SPAWNEGG = REGISTRY.register("highmore_spawnegg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.HIGHMORE, -1, -1, new Item.Properties().stacksTo(64).rarity(Rarity.RARE)));
	public static final RegistryObject<Item> IZUMIK_SPAWNEGG = REGISTRY.register("izumik_spawnegg", () -> new IzumikSpawneggItem());
	public static final RegistryObject<Item> COLOURFULL_JELLY = REGISTRY.register("colourfull_jelly", () -> new ColourfullJellyItem());
	public static final RegistryObject<Item> CHITIN_SHIELD = REGISTRY.register("chitin_shield", () -> new ChitinShieldItem());
	public static final RegistryObject<Item> COMPLEX_CHITIN_SHIELD = REGISTRY.register("complex_chitin_shield", () -> new ComplexChitinShieldItem());
	public static final RegistryObject<Item> HIGHMORE_SPAWNBLOCK = REGISTRY.register(CaerulaArborModBlocks.HIGHMORE_SPAWNBLOCK.getId().getPath(),
			() -> new HighmoreSpawnblockDisplayItem(CaerulaArborModBlocks.HIGHMORE_SPAWNBLOCK.get(), new Item.Properties()));
	public static final RegistryObject<Item> CRISIS_TABLE = REGISTRY.register(CaerulaArborModBlocks.CRISIS_TABLE.getId().getPath(), () -> new CrisisTableDisplayItem(CaerulaArborModBlocks.CRISIS_TABLE.get(), new Item.Properties()));
	public static final RegistryObject<Item> OCEANIZED_EVOKER_SPAWN_EGG = REGISTRY.register("oceanized_evoker_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.OCEANIZED_EVOKER, -6907486, -10896428, new Item.Properties()));
	public static final RegistryObject<Item> IDV_IZUMIK = REGISTRY.register("idv_izumik", () -> new Item(new Item.Properties().stacksTo(64).rarity(Rarity.COMMON)));
	public static final RegistryObject<Item> FRUIT_JELLY = REGISTRY.register("fruit_jelly", () -> new FruitJellyItem());
	public static final RegistryObject<Item> JUNIOR_WARRIOR_PRIEST_SPAWN_EGG = REGISTRY.register("junior_warrior_priest_spawn_egg",
			() -> new ForgeSpawnEggItem(CaerulaArborModEntities.JUNIOR_WARRIOR_PRIEST, -11776947, -13620166, new Item.Properties()));
	public static final RegistryObject<Item> WARRIOR_PRIEST_SPAWN_EGG = REGISTRY.register("warrior_priest_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.WARRIOR_PRIEST, -11776947, -7122553, new Item.Properties()));
	public static final RegistryObject<Item> CORRECTIONAL_PHALANXY_INFANTRY_SPAWN_EGG = REGISTRY.register("correctional_phalanxy_infantry_spawn_egg",
			() -> new ForgeSpawnEggItem(CaerulaArborModEntities.CORRECTIONAL_PHALANXY_INFANTRY, -9473918, -3028012, new Item.Properties()));
	public static final RegistryObject<Item> CORRECTIONAL_PHALAX_VANGUARD_SPAWN_EGG = REGISTRY.register("correctional_phalax_vanguard_spawn_egg",
			() -> new ForgeSpawnEggItem(CaerulaArborModEntities.CORRECTIONAL_PHALAX_VANGUARD, -9473918, -7405225, new Item.Properties()));
	public static final RegistryObject<Item> FAX = block(CaerulaArborModBlocks.FAX);
	public static final RegistryObject<Item> TREATY_COPPER = REGISTRY.register("treaty_copper", () -> new TreatyCopperItem());
	public static final RegistryObject<Item> TREATY_EMPTY = REGISTRY.register("treaty_empty", () -> new TreatyEmptyItem());
	public static final RegistryObject<Item> TREATY_IRON = REGISTRY.register("treaty_iron", () -> new TreatyIronItem());
	public static final RegistryObject<Item> TREATY_GOLD = REGISTRY.register("treaty_gold", () -> new TreatyGoldItem());
	public static final RegistryObject<Item> TREATY_DIAMOND = REGISTRY.register("treaty_diamond", () -> new TreatyDiamondItem());
	public static final RegistryObject<Item> TREATY_NETHERITE = REGISTRY.register("treaty_netherite", () -> new TreatyNetheriteItem());
	public static final RegistryObject<Item> EMERALD_TREATY = REGISTRY.register("emerald_treaty", () -> new EmeraldTreatyItem());
	public static final RegistryObject<Item> TRIBUNAL_HEALER_SPAWN_EGG = REGISTRY.register("tribunal_healer_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.TRIBUNAL_HEALER, -11776947, -5232043, new Item.Properties()));
	public static final RegistryObject<Item> INTERPHONE = REGISTRY.register("interphone", () -> new InterphoneItem());
	public static final RegistryObject<Item> BANNED_ITEM = REGISTRY.register("banned_item", () -> new BannedItemItem());
	public static final RegistryObject<Item> THE_ABANDONED_SPAWN_EGG = REGISTRY.register("the_abandoned_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.THE_ABANDONED, -15836717, -12171706, new Item.Properties()));
	public static final RegistryObject<Item> UNFINISHED_BEAUTY = REGISTRY.register("unfinished_beauty", () -> new UninishedBeautyItem());
	public static final RegistryObject<Item> OCEAN_CAVAIR = REGISTRY.register("ocean_cavair", () -> new OceanCavairItem());
	public static final RegistryObject<Item> ELITE_CAVAIR = REGISTRY.register("elite_cavair", () -> new EliteCavairItem());
	public static final RegistryObject<Item> MARTUS_SPAWNEGG = REGISTRY.register("martus_spawnegg", () -> new MartusSpawneggItem());
	public static final RegistryObject<Item> KEBAB_RAW = REGISTRY.register("kebab_raw", () -> new KebabRawItem());
	public static final RegistryObject<Item> KEBAB_COOKED = REGISTRY.register("kebab_cooked", () -> new KebabCookedItem());
	public static final RegistryObject<Item> GUNMU_SPAWN_EGG = REGISTRY.register("gunmu_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.GUNMU, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> NETHERSEA_PUMPKIN_PIE = REGISTRY.register("nethersea_pumpkin_pie", () -> new NetherseaPumpkinPieItem());
	public static final RegistryObject<Item> NETHERSEA_STEW = REGISTRY.register("nethersea_stew", () -> new NetherseaStewItem());
	public static final RegistryObject<Item> RECORD_WHISPER = REGISTRY.register("record_whisper", () -> new RecordItem(6, () -> ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation(CaerulaArborMod.MODID, "whisper_illusion")), new Item.Properties().stacksTo(1).rarity(Rarity.RARE), 4480));
	public static final RegistryObject<Item> MOIST_ECHO_SHARD = REGISTRY.register("moist_echo_shard", () -> new MoistEchoShardItem());
	public static final RegistryObject<Item> OCEANIZED_WARDEN_SPAWNEGG = REGISTRY.register("oceanized_warden_spawnegg", () -> new OceanizedWardenSpawneggItem());
	public static final RegistryObject<Item> MUTAGENISIS_CAPSULE = REGISTRY.register("mutagenisis_capsule", () -> new MutagenisisCapsuleItem());
	public static final RegistryObject<Item> ECHO_JELLY = REGISTRY.register("echo_jelly", () -> new EchoJellyItem());
	public static final RegistryObject<Item> APOCALYPSE = REGISTRY.register("apocalypse", () -> new ApocalypseItem());
	public static final RegistryObject<Item> OCEANIZED_CAT_SPAWN_EGG = REGISTRY.register("oceanized_cat_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.OCEANIZED_CAT, -3491156, -7897500, new Item.Properties()));
	public static final RegistryObject<Item> SUPER_BIG_CAT_SPAWN_EGG = REGISTRY.register("super_big_cat_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.SUPER_BIG_CAT, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> OCEANIZE_CATALYST = REGISTRY.register("oceanize_catalyst", () -> new OceanizeCatalystItem());
	public static final RegistryObject<Item> ANCHOR_SHARD = REGISTRY.register("anchor_shard", () -> new AnchorShardItem());
	public static final RegistryObject<Item> ANCHOR_FORGE_INGOT = REGISTRY.register("anchor_forge_ingot", () -> new AnchorForgeIngotItem());
	public static final RegistryObject<Item> HAND_ANCHOR = REGISTRY.register("hand_anchor", () -> new HandAnchorItem());
	public static final RegistryObject<Item> COMPLEX_CHITIN_GOLEM_SPAWN_EGG = REGISTRY.register("complex_chitin_golem_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.COMPLEX_CHITIN_GOLEM, -2631220, -9079451, new Item.Properties()));
	public static final RegistryObject<Item> HIGHMORE_SPAWNING_BLOCK = REGISTRY.register(CaerulaArborModBlocks.HIGHMORE_SPAWNING_BLOCK.getId().getPath(),
			() -> new HighmoreSpawningBlockDisplayItem(CaerulaArborModBlocks.HIGHMORE_SPAWNING_BLOCK.get(), new Item.Properties()));
	public static final RegistryObject<Item> TIDELINKED_SHIELD = REGISTRY.register("tidelinked_shield", () -> new TidelinkedShieldItem());
	public static final RegistryObject<Item> TIDELINKED_WAND = REGISTRY.register("tidelinked_wand", () -> new TidelinkedWandItem());
	public static final RegistryObject<Item> GOLDEN_CHALISE = block(CaerulaArborModBlocks.GOLDEN_CHALISE);
	public static final RegistryObject<Item> EMERGENCY_AID_BUILDING = block(CaerulaArborModBlocks.EMERGENCY_AID_BUILDING);
	public static final RegistryObject<Item> EMERGENCY_AID_BUILDING_SALVIENTO = block(CaerulaArborModBlocks.EMERGENCY_AID_BUILDING_SALVIENTO);
	public static final RegistryObject<Item> MIZUKI_STATUE = REGISTRY.register(CaerulaArborModBlocks.MIZUKI_STATUE.getId().getPath(), () -> new MizukiStatueDisplayItem(CaerulaArborModBlocks.MIZUKI_STATUE.get(), new Item.Properties()));
	public static final RegistryObject<Item> RECORD_ENDOSPORE = REGISTRY.register("record_endospore", () -> new RecordItem(0, () -> ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation(CaerulaArborMod.MODID, "endospore")), new Item.Properties().stacksTo(1).rarity(Rarity.RARE), 3940));
	public static final RegistryObject<Item> NUCLEIC_MALEFICENT_SPAWN_EGG = REGISTRY.register("nucleic_maleficent_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.NUCLEIC_MALEFICENT, -15062866, -1, new Item.Properties()));
	public static final RegistryObject<Item> SHELL_OF_STONECUTTER = REGISTRY.register("shell_of_stonecutter", () -> new Item(new Item.Properties().stacksTo(64).rarity(Rarity.COMMON)));
	public static final RegistryObject<Item> POCKET_SEA_DOLL = REGISTRY.register(CaerulaArborModBlocks.POCKET_SEA_DOLL.getId().getPath(), () -> new PocketSeaDollDisplayItem(CaerulaArborModBlocks.POCKET_SEA_DOLL.get(), new Item.Properties()));
	public static final RegistryObject<Item> SWARMCALLER_DOLL = REGISTRY.register(CaerulaArborModBlocks.SWARMCALLER_DOLL.getId().getPath(), () -> new SwarmcallerDollDisplayItem(CaerulaArborModBlocks.SWARMCALLER_DOLL.get(), new Item.Properties()));
	public static final RegistryObject<Item> STONECUTTER_DOLL = REGISTRY.register(CaerulaArborModBlocks.STONECUTTER_DOLL.getId().getPath(), () -> new StonecutterDollDisplayItem(CaerulaArborModBlocks.STONECUTTER_DOLL.get(), new Item.Properties()));
	public static final RegistryObject<Item> MOIST_STAR = REGISTRY.register("moist_star", () -> new MoistStarItem());
	public static final RegistryObject<Item> NETHERSEA_SOUL_SAND = block(CaerulaArborModBlocks.NETHERSEA_SOUL_SAND);
	public static final RegistryObject<Item> OCEANIZED_WITHER_SPAWNEGG = REGISTRY.register("oceanized_wither_spawnegg", () -> new OceanziedWitherSpawneggItem());
	public static final RegistryObject<Item> CAERULA_BOOK_SHELF = block(CaerulaArborModBlocks.CAERULA_BOOK_SHELF);
	public static final RegistryObject<Item> RECORD_PATH_AHEAD = REGISTRY.register("record_path_ahead", () -> new RecordItem(6, () -> ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation(CaerulaArborMod.MODID, "only_path_ahead")), new Item.Properties().stacksTo(1).fireResistant().rarity(Rarity.RARE), 3040));
	public static final RegistryObject<Item> ABANDONED_SULPTURE = REGISTRY.register(CaerulaArborModBlocks.ABANDONED_SULPTURE.getId().getPath(),
			() -> new AbandonedSulptureDisplayItem(CaerulaArborModBlocks.ABANDONED_SULPTURE.get(), new Item.Properties()));
	public static final RegistryObject<Item> NETHERSEA_ICECREAM = REGISTRY.register("nethersea_icecream", () -> new NetherseaIcecreamItem());
	public static final RegistryObject<Item> GOODSQUIDS_SERVERER = REGISTRY.register("goodsquids_serverer", () -> new GoodsquidsServererItem());
	public static final RegistryObject<Item> NOURISHED_APPLE_PIE = REGISTRY.register("nourished_apple_pie", () -> new NourishedApplePieItem());
	public static final RegistryObject<Item> LAST_KNIGHT_SPAWNER = REGISTRY.register("last_knight_spawner", () -> new LastKnightSpawnerItem());
	public static final RegistryObject<Item> DIORITE_SCULPTURE = REGISTRY.register("diorite_sculpture", () -> new DioriteSculptureItem());
	public static final RegistryObject<Item> ROCINANTE_SPAWN_EGG = REGISTRY.register("rocinante_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.ROCINANTE, -13027013, -9471010, new Item.Properties()));
	public static final RegistryObject<Item> APOCATA_SPAWN_EGG = REGISTRY.register("apocata_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.APOCATA, -26164, -13421773, new Item.Properties()));
	public static final RegistryObject<Item> KNIGHT_CORPSE = REGISTRY.register("knight_corpse", () -> new KnightCorpseItem());
	public static final RegistryObject<Item> IRON_SWORD_OF_KNIGHT_CORPUS = REGISTRY.register("iron_sword_of_knight_corpus", () -> new SwordOfLastKnightCorpusItem());
	public static final RegistryObject<Item> LONG_SWORD_OF_KNIGHT_CORPUS = REGISTRY.register("long_sword_of_knight_corpus", () -> new LongSwordOfKnightCorpusItem());
	public static final RegistryObject<Item> TIDE_HUNET_TEMPLATE = REGISTRY.register("tide_hunet_template", () -> new TideHunetTemplateItem());
	public static final RegistryObject<Item> DNA_HORSE = REGISTRY.register("dna_horse", () -> new DNAHorseItem());
	public static final RegistryObject<Item> ROCINANTE_INJECTOR = REGISTRY.register("rocinante_injector", () -> new RocinanteInjectorItem());
	public static final RegistryObject<Item> MARTUS_BOOK = REGISTRY.register("martus_book", () -> new MartusBookItem());
	public static final RegistryObject<Item> OCEANIZED_FOX_SPAWN_EGG = REGISTRY.register("oceanized_fox_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.OCEANIZED_FOX, -1968903, -6433566, new Item.Properties()));
	public static final RegistryObject<Item> TIDUTANT_EXCRESCENCE_SPAWN_EGG = REGISTRY.register("tidutant_excrescence_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.TIDUTANT_EXCRESCENCE, -10392431, -3177597, new Item.Properties()));
	public static final RegistryObject<Item> BREATH_OF_TIDE = REGISTRY.register("breath_of_tide", () -> new BreathOfTideItem());
	public static final RegistryObject<Item> OCEANIZED_POLAR_BEAR_SPAWN_EGG = REGISTRY.register("oceanized_polar_bear_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.OCEANIZED_POLAR_BEAR, -3614740, -12494209, new Item.Properties()));
	public static final RegistryObject<Item> FLUORE_ICECREAM = REGISTRY.register("fluore_icecream", () -> new FloureIcecreamItem());
	public static final RegistryObject<Item> OCEANGLASS_CUP = REGISTRY.register("oceanglass_cup", () -> new OceanglassCupItem());
	public static final RegistryObject<Item> A_CUP_OF_WATER = REGISTRY.register("a_cup_of_water", () -> new ACupOfWaterItem());
	public static final RegistryObject<Item> DEEP_SEAGRASS_JUICE = REGISTRY.register("deep_seagrass_juice", () -> new DeepSeagrassJuiceItem());
	public static final RegistryObject<Item> CARAMEL_SEAGRASS_JUICE = REGISTRY.register("caramel_seagrass_juice", () -> new CaramelSeagrassJuiceItem());
	public static final RegistryObject<Item> COLOURFUL_APPLE_JUICE = REGISTRY.register("colourful_apple_juice", () -> new ColourfulAppleJuiceItem());
	public static final RegistryObject<Item> NETHERSEA_COFFEE = REGISTRY.register("nethersea_coffee", () -> new NetherseaCoffeItem());
	public static final RegistryObject<Item> NETHERSEA_STIMUTANT = REGISTRY.register("nethersea_stimutant", () -> new NetherseaStimutantItem());
	public static final RegistryObject<Item> FLUORE_BERRY_JUICE = REGISTRY.register("fluore_berry_juice", () -> new FluoreBerryJuiceItem());
	public static final RegistryObject<Item> TIDUTANT_ROCK_SPIDER_SPAWN_EGG = REGISTRY.register("tidutant_rock_spider_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.TIDUTANT_ROCK_SPIDER, -10267053, -9455873, new Item.Properties()));
	public static final RegistryObject<Item> ENDSPEAKER_SPAWNEGG = REGISTRY.register("endspeaker_spawnegg", () -> new EndspeakerSpawneggItem());
	public static final RegistryObject<Item> LINGERING_FRACTAL_SPAWN_EGG = REGISTRY.register("lingering_fractal_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.LINGERING_FRACTAL, -15986675, -14861545, new Item.Properties()));
	public static final RegistryObject<Item> ENDSPEAKER_NEST = block(CaerulaArborModBlocks.ENDSPEAKER_NEST);
	public static final RegistryObject<Item> ITEM_HELPER = REGISTRY.register("item_helper", () -> new ItemHelperItem());
	public static final RegistryObject<Item> ITEM_HELPER_AL_1S = REGISTRY.register("item_helper_al_1s", () -> new ItemHelperAl1sItem());
	public static final RegistryObject<Item> DICTATIONLESS_CHAPTER = REGISTRY.register("dictationless_chapter", () -> new DictationlessChapterItem());
	public static final RegistryObject<Item> LANC_XIAO = REGISTRY.register("lanc_xiao", () -> new LancXiaoItem());
	public static final RegistryObject<Item> DAMAGE_TESTER_SPAWN_EGG = REGISTRY.register("damage_tester_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.DAMAGE_TESTER, -16777216, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> APOCATA_SWORD = REGISTRY.register("apocata_sword", () -> new ApocataSwordItem());
	public static final RegistryObject<Item> CHITIN_INGOT = REGISTRY.register("chitin_ingot", () -> new Item(new Item.Properties().stacksTo(64).rarity(Rarity.COMMON)));
	public static final RegistryObject<Item> ULPIANS_SPAWN_EGG = REGISTRY.register("ulpians_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.ULPIANS, -12958887, -1121571, new Item.Properties()));
	public static final RegistryObject<Item> GLADIIA_SPAWN_EGG = REGISTRY.register("gladiia_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.GLADIIA, -13419440, -9077307, new Item.Properties()));
	public static final RegistryObject<Item> OPERATION_TABLE = block(CaerulaArborModBlocks.OPERATION_TABLE);
	public static final RegistryObject<Item> CENTRIFUGER = REGISTRY.register(CaerulaArborModBlocks.CENTRIFUGER.getId().getPath(), () -> new CentrifugerDisplayItem(CaerulaArborModBlocks.CENTRIFUGER.get(), new Item.Properties()));
	public static final RegistryObject<Item> TARGETED_BASE = REGISTRY.register("targeted_base", () -> new TargetedBaseItem());
	public static final RegistryObject<Item> HUNTER_GENE_SKADI = REGISTRY.register("hunter_gene_skadi", () -> new HunterGeneSkadiItem());
	public static final RegistryObject<Item> HUNTER_GENE_ULPIANS = REGISTRY.register("hunter_gene_ulpians", () -> new HunterGeneUlpiansItem());
	public static final RegistryObject<Item> HUNTER_GENE_GLADIIA = REGISTRY.register("hunter_gene_gladiia", () -> new HunterGeneGladiiaItem());
	public static final RegistryObject<Item> TARGETED_TRANSMITTER_SKADI = REGISTRY.register("targeted_transmitter_skadi", () -> new TargetedTransmitterSkadiItem());
	public static final RegistryObject<Item> TARGETED_TRANSMITTER_ULPIANS = REGISTRY.register("targeted_transmitter_ulpians", () -> new TargetedTransmitterUlpiansItem());
	public static final RegistryObject<Item> TARGETED_TRANSMITTER_GLADIIA = REGISTRY.register("targeted_transmitter_gladiia", () -> new TargetedTransmitterGladiiaItem());
	public static final RegistryObject<Item> PERSONNEL_TRANSPORTER = REGISTRY.register("personnel_transporter", () -> new PersonnelTransporterItem());
	public static final RegistryObject<Item> INJECTOR = block(CaerulaArborModBlocks.INJECTOR);
	public static final RegistryObject<Item> DICTATION_CHAPTER = REGISTRY.register("dictation_chapter", () -> new DictationChapterItem());
	public static final RegistryObject<Item> BASE_OPERATION_KIT = REGISTRY.register("base_operation_kit", () -> new BaseOperationKitItem());
	public static final RegistryObject<Item> OPERATION_KIT_SKADI = REGISTRY.register("operation_kit_skadi", () -> new OperationKitSkadiItem());
	public static final RegistryObject<Item> OPERATION_KIT_ULPIANS = REGISTRY.register("operation_kit_ulpians", () -> new OperationKitUlpiansItem());
	public static final RegistryObject<Item> OPERATION_KIT_GLADIIA = REGISTRY.register("operation_kit_gladiia", () -> new OperationKitGladiiaItem());
	public static final RegistryObject<Item> SEALEATHER_CHITIN_HELMET = REGISTRY.register("sealeather_chitin_helmet", () -> new SealeatherChitinItem.Helmet());
	public static final RegistryObject<Item> SEALEATHER_CHITIN_CHESTPLATE = REGISTRY.register("sealeather_chitin_chestplate", () -> new SealeatherChitinItem.Chestplate());
	public static final RegistryObject<Item> SEALEATHER_CHITIN_LEGGINGS = REGISTRY.register("sealeather_chitin_leggings", () -> new SealeatherChitinItem.Leggings());
	public static final RegistryObject<Item> SEALEATHER_CHITIN_BOOTS = REGISTRY.register("sealeather_chitin_boots", () -> new SealeatherChitinItem.Boots());
	public static final RegistryObject<Item> NETHERSEA_WOOD = block(CaerulaArborModBlocks.NETHERSEA_WOOD);
	public static final RegistryObject<Item> STRIPPED_NETHERSEA_WOOD = block(CaerulaArborModBlocks.STRIPPED_NETHERSEA_WOOD);
	public static final RegistryObject<Item> SPECTER_SPAWN_EGG = REGISTRY.register("specter_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.SPECTER, -9340526, -5326397, new Item.Properties()));
	public static final RegistryObject<Item> HUNTER_GENE_SPECTER = REGISTRY.register("hunter_gene_specter", () -> new HunterGeneSpecterItem());
	public static final RegistryObject<Item> OPERATION_KIT_SPECTER = REGISTRY.register("operation_kit_specter", () -> new OperationKitSpecterItem());
	public static final RegistryObject<Item> TARGETED_TRANSMITTER_SPECTER = REGISTRY.register("targeted_transmitter_specter", () -> new TargetedTransmitterSpecterItem());
	public static final RegistryObject<Item> AEGIR_LANCET = REGISTRY.register("aegir_lancet", () -> new AegirLancetItem());
	public static final RegistryObject<Item> BROKEN_SEA = REGISTRY.register("broken_sea", () -> new BrokenSeaItem());
	public static final RegistryObject<Item> PALE_GOLD_PENDANT = REGISTRY.register("pale_gold_pendant", () -> new PaleGoldPendantItem());
	public static final RegistryObject<Item> IRENE_SPAWN_EGG = REGISTRY.register("irene_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.IRENE, -5065798, -4494458, new Item.Properties()));
	public static final RegistryObject<Item> TIDE_CHIMERA_SPAWN_EGG = REGISTRY.register("tide_chimera_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.TIDE_CHIMERA, -16762940, -10496001, new Item.Properties()));
	public static final RegistryObject<Item> AEGIR_SWORD = REGISTRY.register("aegir_sword", () -> new AegirSwordItem());
	public static final RegistryObject<Item> SKADI_SWORD = REGISTRY.register("skadi_sword", () -> new SkadiSwordItem());
	public static final RegistryObject<Item> MOIST_BAG = REGISTRY.register("moist_bag", () -> new MoistBagItem());
	public static final RegistryObject<Item> CORRUPTED_HEART_SPAWNER = REGISTRY.register("corrupted_heart_spawner", () -> new CorruptedHeartSpawnerItem());
	public static final RegistryObject<Item> INCANDESCENT_ANIMA = REGISTRY.register("incandescent_anima", () -> new IncandescentAnimaItem());
	public static final RegistryObject<Item> ISHARMLA_REMAIN = block(CaerulaArborModBlocks.ISHARMLA_REMAIN);
	public static final RegistryObject<Item> RECORD_UNDERTIDES = REGISTRY.register("record_undertides", () -> new RecordItem(0, () -> ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation(CaerulaArborMod.MODID, "undertides")), new Item.Properties().stacksTo(1).rarity(Rarity.RARE), 4620));
	public static final RegistryObject<Item> AEGIR_GLASS_DECO = block(CaerulaArborModBlocks.AEGIR_GLASS_DECO);
	public static final RegistryObject<Item> AEGIR_GLASS_BAR = block(CaerulaArborModBlocks.AEGIR_GLASS_BAR);
	public static final RegistryObject<Item> AEGIR_GLASS_ARCH = block(CaerulaArborModBlocks.AEGIR_GLASS_ARCH);
	public static final RegistryObject<Item> RECORD_DEEPNESS = REGISTRY.register("record_deepness", () -> new RecordItem(6, () -> ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation(CaerulaArborMod.MODID, "operation_deepness")), new Item.Properties().stacksTo(1).rarity(Rarity.RARE), 4420));
	public static final RegistryObject<Item> OCEANIZE_RABBIT_SPAWN_EGG = REGISTRY.register("oceanize_rabbit_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.OCEANIZE_RABBIT, -1802567, -4241774, new Item.Properties()));
	public static final RegistryObject<Item> CHITIN_BOW = REGISTRY.register("chitin_bow", () -> new ChitinBowItem());
	public static final RegistryObject<Item> CORAL_FEET = REGISTRY.register("coral_feet", () -> new Item(new Item.Properties().stacksTo(64).rarity(Rarity.COMMON)));
	public static final RegistryObject<Item> SAINT_CARMEN_SPAWN_EGG = REGISTRY.register("saint_carmen_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.SAINT_CARMEN, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> SALTWIND_SMOOTH_STAIR = block(CaerulaArborModBlocks.SALTWIND_SMOOTH_STAIR);
	public static final RegistryObject<Item> CARMEN_TREATY = REGISTRY.register("carmen_treaty", () -> new CarmenTreatyItem());
	public static final RegistryObject<Item> OCEANIZED_ILLUSIONER_SPAWNER = REGISTRY.register("oceanized_illusioner_spawner", () -> new OceanizedIllusionerSpawnerItem());
	public static final RegistryObject<Item> OCEAN_ILLUSION_SPAWN_EGG = REGISTRY.register("ocean_illusion_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.OCEAN_ILLUSION, -13609646, -14469579, new Item.Properties()));
	public static final RegistryObject<TrailriteArmorItem> TRAILRITE_ARMOR_HELMET = REGISTRY.register("trailrite_armor_helmet", () -> new TrailriteArmorItem(ArmorItem.Type.HELMET, new Item.Properties().fireResistant()));
	public static final RegistryObject<TrailriteArmorItem> TRAILRITE_ARMOR_CHESTPLATE = REGISTRY.register("trailrite_armor_chestplate", () -> new TrailriteArmorItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().fireResistant()));
	public static final RegistryObject<TrailriteArmorItem> TRAILRITE_ARMOR_LEGGINGS = REGISTRY.register("trailrite_armor_leggings", () -> new TrailriteArmorItem(ArmorItem.Type.LEGGINGS, new Item.Properties().fireResistant()));
	public static final RegistryObject<TrailriteArmorItem> TRAILRITE_ARMOR_BOOTS = REGISTRY.register("trailrite_armor_boots", () -> new TrailriteArmorItem(ArmorItem.Type.BOOTS, new Item.Properties().fireResistant()));
	public static final RegistryObject<Item> ILLUSIONER_BANNER = REGISTRY.register(CaerulaArborModBlocks.ILLUSIONER_BANNER.getId().getPath(),
			() -> new IllusionerBannerDisplayItem(CaerulaArborModBlocks.ILLUSIONER_BANNER.get(), new Item.Properties()));
	public static final RegistryObject<Item> FLAMARINE_STATUE_SPAWN_EGG = REGISTRY.register("flamarine_statue_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.FLAMARINE_STATUE, -12687711, -341741, new Item.Properties()));
	public static final RegistryObject<Item> LIVING_ARMORSTAND = REGISTRY.register(CaerulaArborModBlocks.LIVING_ARMORSTAND.getId().getPath(),
			() -> new LivingArmorstandDisplayItem(CaerulaArborModBlocks.LIVING_ARMORSTAND.get(), new Item.Properties()));
	public static final RegistryObject<Item> NAUTILUS_HEADHUNTER_SPAWN_EGG = REGISTRY.register("nautilus_headhunter_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.NAUTILUS_HEADHUNTER, -30360, -3593216, new Item.Properties()));
	public static final RegistryObject<Item> XANTIS_SPAWN_EGG = REGISTRY.register("xantis_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.XANTIS, -10063429, -7364642, new Item.Properties()));
	public static final RegistryObject<Item> FLAMARINE_UPGRADE_TEMPLATE = REGISTRY.register("flamarine_upgrade_template", () -> new FlamarineUpgradeTemplateItem());
	public static final RegistryObject<Item> FLAMARINE_GOLEM_SPAWN_EGG = REGISTRY.register("flamarine_golem_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.FLAMARINE_GOLEM, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> TRAILRITE_ARMORSTAND = REGISTRY.register(CaerulaArborModBlocks.TRAILRITE_ARMORSTAND.getId().getPath(),
			() -> new TrailriteArmorstandDisplayItem(CaerulaArborModBlocks.TRAILRITE_ARMORSTAND.get(), new Item.Properties()));
	public static final RegistryObject<Item> TRAILRITE_PICKAXE = REGISTRY.register("trailrite_pickaxe", () -> new TrailritePickaxeItem());
	public static final RegistryObject<Item> TRAILRITE_HOE = REGISTRY.register("trailrite_hoe", () -> new TrailriteHoeItem());
	public static final RegistryObject<Item> TRAILRITE_SHOVEL = REGISTRY.register("trailrite_shovel", () -> new TrailriteShovelItem());
	public static final RegistryObject<Item> OCEANIZED_VEX_SPAWN_EGG = REGISTRY.register("oceanized_vex_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.OCEANIZED_VEX, -11178618, -8543810, new Item.Properties()));
	public static final RegistryObject<KnightIronItem> KNIGHT_IRON_HELMET = REGISTRY.register("knight_iron_helmet", () -> new KnightIronItem(ArmorItem.Type.HELMET, new Item.Properties()));
	public static final RegistryObject<KnightIronItem> KNIGHT_IRON_CHESTPLATE = REGISTRY.register("knight_iron_chestplate", () -> new KnightIronItem(ArmorItem.Type.CHESTPLATE, new Item.Properties()));
	public static final RegistryObject<KnightIronItem> KNIGHT_IRON_LEGGINGS = REGISTRY.register("knight_iron_leggings", () -> new KnightIronItem(ArmorItem.Type.LEGGINGS, new Item.Properties()));
	public static final RegistryObject<KnightIronItem> KNIGHT_IRON_BOOTS = REGISTRY.register("knight_iron_boots", () -> new KnightIronItem(ArmorItem.Type.BOOTS, new Item.Properties()));
	public static final RegistryObject<Item> ISHARMLA_SPAWNER = REGISTRY.register("isharmla_spawner", () -> new IsharmlaSpawnerItem());
	public static final RegistryObject<Item> QUNYOU_WANTED_ISHARMLA_SPAWN_EGG = REGISTRY.register("qunyou_wanted_isharmla_spawn_egg",
			() -> new ForgeSpawnEggItem(CaerulaArborModEntities.QUNYOU_WANTED_ISHARMLA, -2499866, -10115, new Item.Properties()));
	public static final RegistryObject<Item> ISHARMLA_TEAR_SPAWN_EGG = REGISTRY.register("isharmla_tear_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.ISHARMLA_TEAR, -3034976, -328990, new Item.Properties()));
	public static final RegistryObject<Item> MIZUKI_DETERMINATION = REGISTRY.register("mizuki_determination", () -> new MizukiDeterminationItem());
	public static final RegistryObject<Item> LEVIATHAN_ANIMUS = REGISTRY.register("leviathan_animus", () -> new LeviathanAnimusItem());
	public static final RegistryObject<Item> RECORD_ISHARMLA = REGISTRY.register("record_isharmla", () -> new RecordItem(4, () -> ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation(CaerulaArborMod.MODID, "conquerer")), new Item.Properties().stacksTo(1).rarity(Rarity.RARE), 4020));
	public static final RegistryObject<Item> TEAR_ISHARMLA = REGISTRY.register("tear_isharmla", () -> new TearIsharmlaItem());
	public static final RegistryObject<Item> ISHARMLA_SCUTE = REGISTRY.register("isharmla_scute", () -> new Item(new Item.Properties().stacksTo(64).rarity(Rarity.UNCOMMON)));
	public static final RegistryObject<Item> ISHARMLA_BRICK = block(CaerulaArborModBlocks.ISHARMLA_BRICK);
	public static final RegistryObject<Item> ISHARMLA_BRICK_PILLAR = block(CaerulaArborModBlocks.ISHARMLA_BRICK_PILLAR);
	public static final RegistryObject<Item> ISHARMLA_BRICK_CHIESLED = block(CaerulaArborModBlocks.ISHARMLA_BRICK_CHIESLED);
	public static final RegistryObject<Item> ISHARMLA_BRICK_GILDED = block(CaerulaArborModBlocks.ISHARMLA_BRICK_GILDED);
	public static final RegistryObject<Item> ISHARMLA_SLAB = block(CaerulaArborModBlocks.ISHARMLA_SLAB);
	public static final RegistryObject<Item> ISHARMLA_STAIR = block(CaerulaArborModBlocks.ISHARMLA_STAIR);
	public static final RegistryObject<Item> ISHARMLA_WALL = block(CaerulaArborModBlocks.ISHARMLA_WALL);
	public static final RegistryObject<Item> ISHARMLA_WALL_CHIESLED = block(CaerulaArborModBlocks.ISHARMLA_WALL_CHIESLED);
	public static final RegistryObject<Item> ISHARMLA_WALL_GILDED = block(CaerulaArborModBlocks.ISHARMLA_WALL_GILDED);
	public static final RegistryObject<Item> COMPASSION_PRAYER_SPAWN_EGG = REGISTRY.register("compassion_prayer_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.COMPASSION_PRAYER, -11571331, -2371137, new Item.Properties()));
	public static final RegistryObject<Item> MOIST_ENDER_CRYSTAL_SPAWN_EGG = REGISTRY.register("moist_ender_crystal_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.MOIST_ENDER_CRYSTAL, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> ENDERINA_SPAWNER = REGISTRY.register("enderina_spawner", () -> new EnderinaSpawnerItem());
	public static final RegistryObject<Item> DRAGON_BRAND = block(CaerulaArborModBlocks.DRAGON_BRAND);
	public static final RegistryObject<Item> MOIST_CRYSTAL_ITEM = REGISTRY.register("moist_crystal_item", () -> new MoistCrystalItemItem());
	public static final RegistryObject<Item> ENDERINA_CORE = block(CaerulaArborModBlocks.ENDERINA_CORE);
	public static final RegistryObject<Item> MOIST_DRAGON_HEART = REGISTRY.register("moist_dragon_heart", () -> new MoistDragonHeartItem());
	public static final RegistryObject<Item> DRAGON_WAND = REGISTRY.register("dragon_wand", () -> new DragonWandItem());
	public static final RegistryObject<Item> CAERULA_BOOK_HOLDER = REGISTRY.register("caerula_book_holder", () -> new Item(new Item.Properties().stacksTo(64).rarity(Rarity.COMMON)));
	public static final RegistryObject<Item> THIRSTER_SPAWN_EGG = REGISTRY.register("thirster_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.THIRSTER, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> ABSORBER_LIMB_SPAWN_EGG = REGISTRY.register("absorber_limb_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.ABSORBER_LIMB, -16117736, -13220008, new Item.Properties()));
	public static final RegistryObject<Item> NERVOUS_REGENERATION = REGISTRY.register("nervous_regeneration", () -> new NervousRegenerationItem());
	public static final RegistryObject<Item> THIRST_CORAL = block(CaerulaArborModBlocks.THIRST_CORAL);
	public static final RegistryObject<Item> COMPLEX_CHITIN_BOW = REGISTRY.register("complex_chitin_bow", () -> new ComplexChitinBowItem());
	public static final RegistryObject<Item> TRAILRITE_BOW = REGISTRY.register("trailrite_bow", () -> new TrailriteBowItem());
	public static final RegistryObject<Item> TRAILRITE_ARROW = REGISTRY.register("trailrite_arrow", () -> new TrailriteArrowItem());
	public static final RegistryObject<Item> TRAILRITE_NUGGET = REGISTRY.register("trailrite_nugget", () -> new TrailriteNuggetItem());
	public static final RegistryObject<Item> SCREAM_CHEST_FISH_SPAWN_EGG = REGISTRY.register("scream_chest_fish_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.SCREAM_CHEST_FISH, -9079426, -12746559, new Item.Properties()));
	public static final RegistryObject<Item> OCEANIZED_CHICKEN_SPAWN_EGG = REGISTRY.register("oceanized_chicken_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.OCEANIZED_CHICKEN, -9467992, -16762940, new Item.Properties()));
	public static final RegistryObject<Item> NETHERSEA_CHICKEN_EGG = REGISTRY.register("nethersea_chicken_egg", () -> new NetherseaChickenEggItem());
	public static final RegistryObject<Item> NETHERSEA_EGG_CUSTARD = REGISTRY.register("nethersea_egg_custard", () -> new NetherseaEggCustardItem());
	public static final RegistryObject<Item> NETHERSEA_PRESERVED_EGG = REGISTRY.register("nethersea_preserved_egg", () -> new NetherseaPreservedEggItem());
	public static final RegistryObject<Item> NETHERSEA_SLIME_SPAWN_EGG = REGISTRY.register("nethersea_slime_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.NETHERSEA_SLIME, -10983573, -12426093, new Item.Properties()));
	public static final RegistryObject<Item> OCEANIZED_SHULKER_SPAWN_EGG = REGISTRY.register("oceanized_shulker_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.OCEANIZED_SHULKER, -5999788, -13398106, new Item.Properties()));
	public static final RegistryObject<Item> NURTURE_GENE_SET = REGISTRY.register("nurture_gene_set", () -> new NurtureGeneSetItem());
	public static final RegistryObject<Item> GENE_SAMPLE_NORMAL = REGISTRY.register("gene_sample_normal", () -> new GeneSampleNormalItem());
	public static final RegistryObject<Item> GENE_SAMPLE_UPGRADED = REGISTRY.register("gene_sample_upgraded", () -> new GeneSampleUpgradedItem());
	public static final RegistryObject<Item> GENE_SAMPLE_SUPERB = REGISTRY.register("gene_sample_superb", () -> new GeneSampleSuperbItem());
	public static final RegistryObject<Item> NETHERSEA_SAMPLING = block(CaerulaArborModBlocks.NETHERSEA_SAMPLING);
	public static final RegistryObject<Item> ARCHIVE_SAL_VIENTO = REGISTRY.register("archive_sal_viento", () -> new Item(new Item.Properties().stacksTo(64).rarity(Rarity.UNCOMMON)));
	public static final RegistryObject<Item> ARCHIVE_OF_TIDELINK = REGISTRY.register("archive_of_tidelink", () -> new Item(new Item.Properties().stacksTo(64).rarity(Rarity.UNCOMMON)));
	public static final RegistryObject<Item> ARCHIVE_OF_MARTUS = REGISTRY.register("archive_of_martus", () -> new Item(new Item.Properties().stacksTo(64).rarity(Rarity.UNCOMMON)));
	public static final RegistryObject<Item> ARCHIVE_OF_RAIDER = REGISTRY.register("archive_of_raider", () -> new Item(new Item.Properties().stacksTo(64).rarity(Rarity.UNCOMMON)));

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}

	private static RegistryObject<Item> doubleBlock(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), new Item.Properties()));
	}

	@SubscribeEvent
	public static void clientLoad(FMLClientSetupEvent event) {
		event.enqueueWork(() -> {
			ItemProperties.register(MUSIC_BOX_FIXED.get(), new ResourceLocation(CaerulaArborMod.MODID, "music_box_fixed_playing"),
					(itemStackToRender, clientWorld, entity, itemEntityId) -> {
                        double result = 0;
                        if (entity != null) {
                            if ((Entity) entity instanceof Player _plrCldCheck1 && _plrCldCheck1.getCooldowns().isOnCooldown(itemStackToRender.getItem())) {
                                result = 1;
                            }
                        }
                        return (float) result;
                    });
			ItemProperties.register(CHITIN_SHIELD.get(), new ResourceLocation("blocking"), ItemProperties.getProperty(Items.SHIELD, new ResourceLocation("blocking")));
			ItemProperties.register(COMPLEX_CHITIN_SHIELD.get(), new ResourceLocation("blocking"), ItemProperties.getProperty(Items.SHIELD, new ResourceLocation("blocking")));
			ItemProperties.register(TIDELINKED_SHIELD.get(), new ResourceLocation("blocking"), ItemProperties.getProperty(Items.SHIELD, new ResourceLocation("blocking")));
			ItemProperties.register(CHITIN_BOW.get(), new ResourceLocation(CaerulaArborMod.MODID, "chitin_bow_pulling"), (itemStackToRender, clientWorld, entity, itemEntityId) -> {
                double result = 0;
                if (entity != null) {
                    if (((Entity) entity instanceof LivingEntity _entity) ? _entity.isHolding(CHITIN_BOW.get()) : false) {
                        result = (Entity) entity instanceof LivingEntity _entUseTicks1 ? _entUseTicks1.getTicksUsingItem() : 0;
                    }
                }
                return (float) result;
            });
			ItemProperties.register(COMPLEX_CHITIN_BOW.get(), new ResourceLocation(CaerulaArborMod.MODID, "complex_chitin_bow_pulling"),
					(itemStackToRender, clientWorld, entity, itemEntityId) -> (float) EntityUtils.getComplexPulling(entity, itemStackToRender));
			ItemProperties.register(TRAILRITE_BOW.get(), new ResourceLocation(CaerulaArborMod.MODID, "trailrite_bow_pulling"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) EntityUtils.getComplexPulling(entity, itemStackToRender));
		});
	}
}
