/*
 *	MCreator note: This file will be REGENERATED on each build.
 */
package com.apocalypse.caerulaarbor.init;

import com.apocalypse.caerulaarbor.CaerulaArborMod;
import com.apocalypse.caerulaarbor.potion.*;
import net.minecraft.world.effect.MobEffect;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class CaerulaArborModMobEffects {
	public static final DeferredRegister<MobEffect> REGISTRY = DeferredRegister.create(ForgeRegistries.MOB_EFFECTS, CaerulaArborMod.MODID);
	public static final RegistryObject<MobEffect> HAEMOPHILIA = REGISTRY.register("haemophilia", () -> new HaemophiliaMobEffect());
	public static final RegistryObject<MobEffect> SANITY_IMMUE = REGISTRY.register("sanity_immue", () -> new SanityImmueMobEffect());
	public static final RegistryObject<MobEffect> DIZZY = REGISTRY.register("dizzy", () -> new DizzyMobEffect());
	public static final RegistryObject<MobEffect> KINGS_BREATH = REGISTRY.register("kings_breath", () -> new KingsBreathMobEffect());
	public static final RegistryObject<MobEffect> KINGS_BOOST = REGISTRY.register("kings_boost", () -> new KingsBoostMobEffect());
	public static final RegistryObject<MobEffect> SPEAR_FIGHT = REGISTRY.register("spear_fight", () -> new SpearFightMobEffect());
	public static final RegistryObject<MobEffect> HANDS_SPEED = REGISTRY.register("hands_speed", () -> new HandsSpeedMobEffect());
	public static final RegistryObject<MobEffect> BUTCHERS_POWER = REGISTRY.register("butchers_power", () -> new ButchersPowerMobEffect());
	public static final RegistryObject<MobEffect> WIPE_DUSTS = REGISTRY.register("wipe_dusts", () -> new WipeDustsMobEffect());
	public static final RegistryObject<MobEffect> SACREFICE = REGISTRY.register("sacrefice", () -> new SacreficeMobEffect());
	public static final RegistryObject<MobEffect> ENGRAVED_TRIUMPH = REGISTRY.register("engraved_triumph", () -> new EngravedTriumphMobEffect());
	public static final RegistryObject<MobEffect> FLAG_SWINGS = REGISTRY.register("flag_swings", () -> new FlagSwingsMobEffect());
	public static final RegistryObject<MobEffect> KEEP_BEDDING = REGISTRY.register("keep_bedding", () -> new KeepBeddingMobEffect());
	public static final RegistryObject<MobEffect> SURVIVORS_GUIDE = REGISTRY.register("survivors_guide", () -> new SurvivorsGuideMobEffect());
	public static final RegistryObject<MobEffect> ADD_REACH = REGISTRY.register("add_reach", () -> new AddReachMobEffect());
	public static final RegistryObject<MobEffect> FROZEN = REGISTRY.register("frozen", () -> new FrozenMobEffect());
	public static final RegistryObject<MobEffect> TRAIL_BUFF = REGISTRY.register("trail_buff", () -> new TrailBuffMobEffect());
	public static final RegistryObject<MobEffect> TIDE_OF_CHITIN = REGISTRY.register("tide_of_chitin", () -> new TideOfChitinMobEffect());
	public static final RegistryObject<MobEffect> SANIDY_DEFENDER = REGISTRY.register("sanidy_defender", () -> new SanidyDefenderMobEffect());
	public static final RegistryObject<MobEffect> UNTAME_CONFIRM = REGISTRY.register("untame_confirm", () -> new UntameConfirmMobEffect());
	public static final RegistryObject<MobEffect> SPLASHER_ATTACK = REGISTRY.register("splasher_attack", () -> new SplasherAttackMobEffect());
	public static final RegistryObject<MobEffect> INSTANT_SANITY = REGISTRY.register("instant_sanity", () -> new InstantSanityMobEffect());
	public static final RegistryObject<MobEffect> SANITY_HEAL = REGISTRY.register("sanity_heal", () -> new SanityHealMobEffect());
	public static final RegistryObject<MobEffect> ROCK_BREAK = REGISTRY.register("rock_break", () -> new RockBreakMobEffect());
	public static final RegistryObject<MobEffect> POWER_OF_ANCHOR = REGISTRY.register("power_of_anchor", () -> new PowerOfAnchorMobEffect());
	public static final RegistryObject<MobEffect> COOLDOWN_SINAL = REGISTRY.register("cooldown_sinal", () -> new CooldownSinalMobEffect());
	public static final RegistryObject<MobEffect> REEF_CRACKER = REGISTRY.register("reef_cracker", () -> new ReefCrackerMobEffect());
	public static final RegistryObject<MobEffect> FLESHDEFORMITY = REGISTRY.register("fleshdeformity", () -> new FleshdeformityMobEffect());
	public static final RegistryObject<MobEffect> BOOST_OF_SILENCE = REGISTRY.register("boost_of_silence", () -> new BoostOfSilenceMobEffect());
	public static final RegistryObject<MobEffect> STRENGTH_OF_CROWD = REGISTRY.register("strength_of_crowd", () -> new StrengthOfCrowdMobEffect());
	public static final RegistryObject<MobEffect> INFESTED = REGISTRY.register("infested", () -> new InfestedMobEffect());
	public static final RegistryObject<MobEffect> LESS_ARMOR = REGISTRY.register("less_armor", () -> new LessArmorMobEffect());
	public static final RegistryObject<MobEffect> INVULNERABLE = REGISTRY.register("invulnerable", () -> new InvulnerableMobEffect());
	public static final RegistryObject<MobEffect> ANGER_OF_TIDE = REGISTRY.register("anger_of_tide", () -> new AngerOfTideMobEffect());
	public static final RegistryObject<MobEffect> DEDUCT_ONE_SANITY = REGISTRY.register("deduct_one_sanity", () -> new DeductOneSanityMobEffect());
	public static final RegistryObject<MobEffect> ADD_ATTACK_PERCLY = REGISTRY.register("add_attack_percly", () -> new AddAttackPerclyMobEffect());
	public static final RegistryObject<MobEffect> FIRST_TELLER_SKILL = REGISTRY.register("first_teller_skill", () -> new FirstTellerSkillMobEffect());
	public static final RegistryObject<MobEffect> PET_REAP = REGISTRY.register("pet_reap", () -> new PetReapMobEffect());
	public static final RegistryObject<MobEffect> RUNNING_ON_TRAIL = REGISTRY.register("running_on_trail", () -> new RunningOnTrailMobEffect());
	public static final RegistryObject<MobEffect> ANGER_OF_BISHOP = REGISTRY.register("anger_of_bishop", () -> new AngerOfBishopMobEffect());
	public static final RegistryObject<MobEffect> FAKE_DEATH = REGISTRY.register("fake_death", () -> new FakeDeathMobEffect());
	public static final RegistryObject<MobEffect> SEEK_OF_FRACTAL = REGISTRY.register("seek_of_fractal", () -> new SeekOfFractalMobEffect());
	public static final RegistryObject<MobEffect> MUTE = REGISTRY.register("mute", () -> new MuteMobEffect());
	public static final RegistryObject<MobEffect> GUIDE_PATH_AHEAD = REGISTRY.register("guide_path_ahead", () -> new GuidePathAheadMobEffect());
	public static final RegistryObject<MobEffect> FADINGSHADOW = REGISTRY.register("fadingshadow", () -> new FadingshadowMobEffect());
	public static final RegistryObject<MobEffect> HEMOSTATIC = REGISTRY.register("hemostatic", () -> new HemostaticMobEffect());
	public static final RegistryObject<MobEffect> PATH_TO_UNCOVER = REGISTRY.register("path_to_uncover", () -> new PathToUncoverMobEffect());
	public static final RegistryObject<MobEffect> LESS_ATTACKSPEED = REGISTRY.register("less_attackspeed", () -> new LessAttackspeedMobEffect());
	public static final RegistryObject<MobEffect> COW_BUFF = REGISTRY.register("cow_buff", () -> new CowBuffMobEffect());
	public static final RegistryObject<MobEffect> UNRIPE_THOUGHTS = REGISTRY.register("unripe_thoughts", () -> new UnripeThoughtsMobEffect());
	public static final RegistryObject<MobEffect> IZUMIK_LEARN = REGISTRY.register("izumik_learn", () -> new IzumikLearnMobEffect());
	public static final RegistryObject<MobEffect> IZUMIK_SHOCK = REGISTRY.register("izumik_shock", () -> new IzumikShockMobEffect());
	public static final RegistryObject<MobEffect> INFANTRY = REGISTRY.register("infantry", () -> new InfantryMobEffect());
	public static final RegistryObject<MobEffect> GUIDED_EVO = REGISTRY.register("guided_evo", () -> new GuidedEvoMobEffect());
	public static final RegistryObject<MobEffect> SUB_HAEMO = REGISTRY.register("sub_haemo", () -> new SubHaemoMobEffect());
	public static final RegistryObject<MobEffect> FAST_SWIM = REGISTRY.register("fast_swim", () -> new FastSwimMobEffect());
	public static final RegistryObject<MobEffect> MARTUS_PROTECTION = REGISTRY.register("martus_protection", () -> new MartusProtectionMobEffect());
	public static final RegistryObject<MobEffect> ENDSPEAER_BRANDGUIDE_BUFF = REGISTRY.register("endspeaer_brandguide_buff", () -> new EndspeaerBrandguideBuffMobEffect());
	public static final RegistryObject<MobEffect> FLEXIBILITY_BUFF = REGISTRY.register("flexibility_buff", () -> new FlexibilityBuffMobEffect());
	public static final RegistryObject<MobEffect> MAGIC_RESIS_BUFF = REGISTRY.register("magic_resis_buff", () -> new MagicResisBuffMobEffect());
	public static final RegistryObject<MobEffect> ESSENCE_RESISTANCE = REGISTRY.register("essence_resistance", () -> new EssenceResistanceMobEffect());
	public static final RegistryObject<MobEffect> IMMORTAL = REGISTRY.register("immortal", () -> new ImmortalMobEffect());
	public static final RegistryObject<MobEffect> ADD_HEALTH_PERCLY = REGISTRY.register("add_health_percly", () -> new AddHealthPerclyMobEffect());
	public static final RegistryObject<MobEffect> ISHARMLA_CURSE = REGISTRY.register("isharmla_curse", () -> new IsharmlaCurseMobEffect());
	public static final RegistryObject<MobEffect> REGENERATION_PERCLY = REGISTRY.register("regeneration_percly", () -> new RegenerationPerclyMobEffect());
	public static final RegistryObject<MobEffect> SHULKER_BUFF = REGISTRY.register("shulker_buff", () -> new ShulkerBuffMobEffect());
	public static final RegistryObject<MobEffect> MORE_FALL_DAMAGE = REGISTRY.register("more_fall_damage", () -> new MoreFallDamageMobEffect());
	public static final RegistryObject<MobEffect> UNDER_BREAK = REGISTRY.register("under_break", () -> new UnderBreakMobEffect());
	public static final RegistryObject<MobEffect> ADD_DEF_TINY = REGISTRY.register("add_def_tiny", () -> new AddDefTinyMobEffect());
	public static final RegistryObject<MobEffect> ADD_DEF_PERCLY_TINY = REGISTRY.register("add_def_percly_tiny", () -> new AddDefPerclyTinyMobEffect());
	public static final RegistryObject<MobEffect> ADD_RESIS_TINY = REGISTRY.register("add_resis_tiny", () -> new AddResisTinyMobEffect());
	public static final RegistryObject<MobEffect> ADD_ATTACK_SPEED_TINY = REGISTRY.register("add_attack_speed_tiny", () -> new AddAttackSpeedTinyMobEffect());
	public static final RegistryObject<MobEffect> REDUCE_SANITY_MODIFIER = REGISTRY.register("reduce_sanity_modifier", () -> new ReduceSanityModifierMobEffect());
	public static final RegistryObject<MobEffect> ADD_MISS_RATE = REGISTRY.register("add_miss_rate", () -> new AddMissRateMobEffect());
	public static final RegistryObject<MobEffect> ADD_DAMAGE_TINY = REGISTRY.register("add_damage_tiny", () -> new AddDamageTinyMobEffect());
}
