package com.susen36.caerulaarbor.init;

import com.susen36.caerulaarbor.CaerulaArborMod;
import com.susen36.caerulaarbor.potion.*;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.world.effect.MobEffect;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

@SuppressWarnings("unused")
public class CAMobEffects {
    public static final DeferredRegister<MobEffect> REGISTRY = DeferredRegister.create(BuiltInRegistries.MOB_EFFECT, CaerulaArborMod.MODID);

    public static final DeferredHolder<MobEffect, ? extends MobEffect> HAEMOPHILIA = REGISTRY.register("haemophilia", HaemophiliaMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> SANITY_IMMUE = REGISTRY.register("sanity_immue", SanityImmueMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> KINGS_BREATH = REGISTRY.register("kings_breath", KingsBreathMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> KINGS_BOOST = REGISTRY.register("kings_boost", KingsBoostMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> SPEAR_FIGHT = REGISTRY.register("spear_fight", SpearFightMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> HANDS_SPEED = REGISTRY.register("hands_speed", HandsSpeedMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> BUTCHERS_POWER = REGISTRY.register("butchers_power", ButchersPowerMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> WIPE_DUSTS = REGISTRY.register("wipe_dusts", WipeDustsMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> SACREFICE = REGISTRY.register("sacrefice", SacreficeMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> ENGRAVED_TRIUMPH = REGISTRY.register("engraved_triumph", EngravedTriumphMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> FLAG_SWINGS = REGISTRY.register("flag_swings", FlagSwingsMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> KEEP_BEDDING = REGISTRY.register("keep_bedding", KeepBeddingMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> SURVIVORS_GUIDE = REGISTRY.register("survivors_guide", SurvivorsGuideMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> ADD_REACH = REGISTRY.register("add_reach", AddReachMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> FROZEN = REGISTRY.register("frozen", FrozenMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> TRAIL_BUFF = REGISTRY.register("trail_buff", TrailBuffMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> TIDE_OF_CHITIN = REGISTRY.register("tide_of_chitin", TideOfChitinMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> SANIDY_DEFENDER = REGISTRY.register("sanidy_defender", SanidyDefenderMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> UNTAME_CONFIRM = REGISTRY.register("untame_confirm", UntameConfirmMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> SPLASHER_ATTACK = REGISTRY.register("splasher_attack", SplasherAttackMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> INSTANT_SANITY = REGISTRY.register("instant_sanity", InstantSanityMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> SANITY_HEAL = REGISTRY.register("sanity_heal", SanityHealMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> ROCK_BREAK = REGISTRY.register("rock_break", RockBreakMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> POWER_OF_ANCHOR = REGISTRY.register("power_of_anchor", PowerOfAnchorMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> COOLDOWN_SINAL = REGISTRY.register("cooldown_sinal", CooldownSinalMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> REEF_CRACKER = REGISTRY.register("reef_cracker", ReefCrackerMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> FLESHDEFORMITY = REGISTRY.register("fleshdeformity", FleshdeformityMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> BOOST_OF_SILENCE = REGISTRY.register("boost_of_silence", BoostOfSilenceMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> STRENGTH_OF_CROWD = REGISTRY.register("strength_of_crowd", StrengthOfCrowdMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> INFESTED = REGISTRY.register("infested", InfestedMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> INVULNERABLE = REGISTRY.register("invulnerable", InvulnerableMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> ANGER_OF_TIDE = REGISTRY.register("anger_of_tide", AngerOfTideMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> DEDUCT_ONE_SANITY = REGISTRY.register("deduct_one_sanity", DeductOneSanityMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> ADD_ATTACK_PERCLY = REGISTRY.register("add_attack_percly", AddAttackPerclyMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> FIRST_TELLER_SKILL = REGISTRY.register("first_teller_skill", FirstTellerSkillMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> PET_REAP = REGISTRY.register("pet_reap", PetReapMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> RUNNING_ON_TRAIL = REGISTRY.register("running_on_trail", RunningOnTrailMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> ANGER_OF_BISHOP = REGISTRY.register("anger_of_bishop", AngerOfBishopMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> FAKE_DEATH = REGISTRY.register("fake_death", FakeDeathMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> SEEK_OF_FRACTAL = REGISTRY.register("seek_of_fractal", SeekOfFractalMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> MUTE = REGISTRY.register("mute", MuteMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> GUIDE_PATH_AHEAD = REGISTRY.register("guide_path_ahead", GuidePathAheadMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> FADINGSHADOW = REGISTRY.register("fadingshadow", FadingshadowMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> HEMOSTATIC = REGISTRY.register("hemostatic", HemostaticMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> PATH_TO_UNCOVER = REGISTRY.register("path_to_uncover", PathToUncoverMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> LESS_ATTACKSPEED = REGISTRY.register("less_attackspeed", LessAttackspeedMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> COW_BUFF = REGISTRY.register("cow_buff", CowBuffMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> UNRIPE_THOUGHTS = REGISTRY.register("unripe_thoughts", UnripeThoughtsMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> IZUMIK_LEARN = REGISTRY.register("izumik_learn", IzumikLearnMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> IZUMIK_SHOCK = REGISTRY.register("izumik_shock", IzumikShockMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> INFANTRY = REGISTRY.register("infantry", InfantryMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> GUIDED_EVO = REGISTRY.register("guided_evo", GuidedEvoMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> SUB_HAEMO = REGISTRY.register("sub_haemo", SubHaemoMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> FAST_SWIM = REGISTRY.register("fast_swim", FastSwimMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> MARTUS_PROTECTION = REGISTRY.register("martus_protection", MartusProtectionMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> ENDSPEAER_BRANDGUIDE_BUFF = REGISTRY.register("endspeaer_brandguide_buff", EndspeaerBrandguideBuffMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> FLEXIBILITY_BUFF = REGISTRY.register("flexibility_buff", FlexibilityBuffMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> MAGIC_RESIS_BUFF = REGISTRY.register("magic_resis_buff", MagicResisBuffMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> IMMORTAL = REGISTRY.register("immortal", ImmortalMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> ADD_HEALTH_PERCLY = REGISTRY.register("add_health_percly", AddHealthPerclyMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> ISHARMLA_CURSE = REGISTRY.register("isharmla_curse", IsharmlaCurseMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> REGENERATION_PERCLY = REGISTRY.register("regeneration_percly", RegenerationPerclyMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> SHULKER_BUFF = REGISTRY.register("shulker_buff", ShulkerBuffMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> MORE_FALL_DAMAGE = REGISTRY.register("more_fall_damage", MoreFallDamageMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> ADD_DEF_TINY = REGISTRY.register("add_def_tiny", AddDefTinyMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> ADD_DEF_PERCLY_TINY = REGISTRY.register("add_def_percly_tiny", AddDefPerclyTinyMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> ADD_RESIS_TINY = REGISTRY.register("add_resis_tiny", AddResisTinyMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> ADD_ATTACK_SPEED_TINY = REGISTRY.register("add_attack_speed_tiny", AddAttackSpeedTinyMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> REDUCE_SANITY_MODIFIER = REGISTRY.register("reduce_sanity_modifier", ReduceSanityModifierMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> ADD_MISS_RATE = REGISTRY.register("add_miss_rate", AddMissRateMobEffect::new);
    public static final DeferredHolder<MobEffect, ? extends MobEffect> ADD_DAMAGE_TINY = REGISTRY.register("add_damage_tiny", AddDamageTinyMobEffect::new);
}