package com.susen36.caerulaarbor.init;

import com.susen36.caerulaarbor.CaerulaArbor;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.CreativeModeTabs;
import net.minecraft.world.item.ItemStack;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.event.BuildCreativeModeTabContentsEvent;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

@EventBusSubscriber
public class CATabs {
    public static final DeferredRegister<CreativeModeTab> REGISTRY = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, CaerulaArbor.MODID);
    public static final DeferredHolder<CreativeModeTab, ? extends CreativeModeTab> CAERULA_ITEMS = REGISTRY.register("caerula_items",
            () -> CreativeModeTab.builder().title(Component.translatable("item_group.caerula_arbor.caerula_items")).icon(() -> new ItemStack(CAItems.CAERULA_RECORDER.get())).displayItems((parameters, tabData) -> {
                tabData.accept(CAItems.CAERULA_RECORDER.get());
                tabData.accept(CAItems.TRAIL_MOP.get());
                tabData.accept(CAItems.PICKAXE_OCEAN_CRYSTAL.get());
                tabData.accept(CAItems.AXE_OCEAN_CRYSTAL.get());
                tabData.accept(CAItems.SHOVEL_OCEAN_CRYSTAL.get());
                tabData.accept(CAItems.HOE_OCEAN_CRYSTAL.get());
                tabData.accept(CAItems.CHITIN_PICKAXE.get());
                tabData.accept(CAItems.CHITIN_AXE.get());
                tabData.accept(CAItems.CHITIN_SHOVEL.get());
                tabData.accept(CAItems.CHITIN_HOE.get());
                tabData.accept(CAItems.COMPLEX_CHITIN_PICKAXE.get());
                tabData.accept(CAItems.COMPLEX_CHITIN_AXE.get());
                tabData.accept(CAItems.COMPLEX_CHITIN_SHOVEL.get());
                tabData.accept(CAItems.COMPLEX_CHITIN_HOE.get());
                tabData.accept(CAItems.TRAILRITE_PICKAXE.get());
                tabData.accept(CAItems.TRAILRITE_HOE.get());
                tabData.accept(CAItems.TRAILRITE_SHOVEL.get());
                tabData.accept(CAItems.MARTUS_BOOK.get());
                tabData.accept(CAItems.DICTATION_CHAPTER.get());
                tabData.accept(CAItems.DICTATIONLESS_CHAPTER.get());
                tabData.accept(CAItems.ITEM_HELPER.get());
                tabData.accept(CAItems.ITEM_HELPER_AL_1S.get());
                tabData.accept(CAItems.PERSONNEL_TRANSPORTER.get());
                tabData.accept(CAItems.INTERPHONE.get());
                tabData.accept(CAItems.MUSIC_BOX_FIXED.get());
                tabData.accept(CAItems.OCARINA.get());
                tabData.accept(CAItems.BREATH_OF_TIDE.get());
                tabData.accept(CABlocks.REDSTONE_IRIS.get().asItem());
                tabData.accept(CABlocks.REDSTONEIRIS_SEEDING.get().asItem());
                tabData.accept(CABlocks.TRAIL_MUSHROOM.get().asItem());
                tabData.accept(CABlocks.VIVIPAROUS_LILY.get().asItem());
                tabData.accept(CABlocks.HUGE_LILY.get().asItem());
                tabData.accept(CABlocks.DEEP_SEAGRASS.get().asItem());
                tabData.accept(CABlocks.NETHERSEA_SAMPLING.get().asItem());
                tabData.accept(CABlocks.SEA_TRAIL_INIT.get().asItem());
                tabData.accept(CABlocks.SEA_TRAIL_GROWING.get().asItem());
                tabData.accept(CABlocks.SEA_TRAIL_GROWN.get().asItem());
                tabData.accept(CABlocks.SEA_TRAIL_BURNT.get().asItem());
                tabData.accept(CABlocks.KINGS_ARMOR.get().asItem());
                tabData.accept(CABlocks.BLOCK_CROWN.get().asItem());
                tabData.accept(CABlocks.BLOCK_SPEAR.get().asItem());
                tabData.accept(CABlocks.BLOCK_EXTENSION.get().asItem());
                tabData.accept(CABlocks.BLOCK_CRYSTAL.get().asItem());
                tabData.accept(CABlocks.BLOCK_FATE.get().asItem());
                tabData.accept(CABlocks.BERRY_CAN.get().asItem());
                tabData.accept(CABlocks.TRAIL_PUMPKING.get().asItem());
                tabData.accept(CABlocks.TRAIL_DEBRIS.get().asItem());
                tabData.accept(CABlocks.TRAIL_LOG.get().asItem());
                tabData.accept(CABlocks.NETHERSEA_WOOD.get().asItem());
                tabData.accept(CABlocks.STRIPPED_TRAIL_LOG.get().asItem());
                tabData.accept(CABlocks.STRIPPED_NETHERSEA_WOOD.get().asItem());
                tabData.accept(CABlocks.TRAIL_LEAVE.get().asItem());
                tabData.accept(CABlocks.NETHERSEA_SOUL_SAND.get().asItem());
                tabData.accept(CABlocks.TRAIL_STONE.get().asItem());
                tabData.accept(CABlocks.BLOCK_RECORDER.get().asItem());
                tabData.accept(CABlocks.SEA_PRAIRIE_BOMB.get().asItem());
                tabData.accept(CABlocks.CHEST_FISH_FOOD.get().asItem());
                tabData.accept(CABlocks.TIDE_OBSERVATION.get().asItem());
                tabData.accept(CABlocks.BOMB_TRAILER.get().asItem());
                tabData.accept(CABlocks.BOMB_COPPER.get().asItem());
                tabData.accept(CABlocks.ANCHOR_LOWER.get().asItem());
                tabData.accept(CABlocks.ANCHOR_MEDIUM.get().asItem());
                tabData.accept(CABlocks.ANCHOR_UPPER.get().asItem());
                tabData.accept(CABlocks.FAX.get().asItem());
                tabData.accept(CABlocks.CAERULA_BOOK_SHELF.get().asItem());
                tabData.accept(CABlocks.CRISIS_TABLE.get().asItem());
                tabData.accept(CABlocks.CHITIN_BLOCK.get().asItem());
                tabData.accept(CABlocks.OCEAN_CRYSTAL_BLOCK.get().asItem());
                tabData.accept(CABlocks.COMPLEX_CHITIN_BLOCK.get().asItem());
                tabData.accept(CABlocks.TRAILRITE_BLOCK.get().asItem());
                tabData.accept(CABlocks.OCEAN_GLASS.get().asItem());
                tabData.accept(CABlocks.OCEAN_GLASSPANE.get().asItem());
                tabData.accept(CABlocks.HETEROPIC_BLOCK.get().asItem());
                tabData.accept(CABlocks.PHLOEM_BLOCK.get().asItem());
                tabData.accept(CABlocks.FIBRE_BLOCK.get().asItem());
                tabData.accept(CABlocks.COOKED_FIBRE_BLOCK.get().asItem());
                tabData.accept(CABlocks.WHITE_CHITIN_BLOCK.get().asItem());
                tabData.accept(CABlocks.OCEAN_OVARY.get().asItem());
                tabData.accept(CABlocks.RED_OVARY.get().asItem());
                tabData.accept(CABlocks.ILLUSIONER_BANNER.get().asItem());
                tabData.accept(CABlocks.BLOCK_CHESTFISH.get().asItem());
                tabData.accept(CABlocks.CHESTMEGA_SPAWNER.get().asItem());
                tabData.accept(CABlocks.TIDEWAY_CRADLE.get().asItem());
                tabData.accept(CABlocks.TIDELINKED_BISHOP_CORE.get().asItem());
                tabData.accept(CABlocks.UNDERTIDE_TABLE.get().asItem());
                tabData.accept(CABlocks.ENDSPEAKER_NEST.get().asItem());
                tabData.accept(CABlocks.HIGHMORE_SPAWNBLOCK.get().asItem());
                tabData.accept(CABlocks.ISHARMLA_REMAIN.get().asItem());
                tabData.accept(CABlocks.MIZUKI_STATUE.get().asItem());
                tabData.accept(CABlocks.THIRST_CORAL.get().asItem());
                tabData.accept(CABlocks.ENDERINA_CORE.get().asItem());
                tabData.accept(CABlocks.SEA_TRAIL_SOLID.get().asItem());
                tabData.accept(CABlocks.TRAIL_PULSE.get().asItem());
                tabData.accept(CABlocks.SEA_TRAIL_BURNT_SOLID.get().asItem());
                tabData.accept(CABlocks.DRAGON_BRAND.get().asItem());
                tabData.accept(CABlocks.REAPER_EGG.get().asItem());
                tabData.accept(CAItems.BASE_OPERATION_KIT.get());
                tabData.accept(CAItems.HUNTER_GENE.get());
                tabData.accept(CAItems.OCEAN_EXTRACTOR.get());
                tabData.accept(CAItems.DNA_REAPER.get());
                tabData.accept(CAItems.DNA_HORSE.get());
                tabData.accept(CAItems.ROCINANTE_INJECTOR.get());
                tabData.accept(CAItems.TREATY_EMPTY.get());
                tabData.accept(CAItems.TREATY_COPPER.get());
                tabData.accept(CAItems.TREATY_IRON.get());
                tabData.accept(CAItems.TREATY_GOLD.get());
                tabData.accept(CAItems.TREATY_DIAMOND.get());
                tabData.accept(CAItems.EMERALD_TREATY.get());
                tabData.accept(CAItems.TREATY_NETHERITE.get());
                tabData.accept(CAItems.CARMEN_TREATY.get());
                tabData.accept(CABlocks.EMERGENCY_AID_BUILDING.get().asItem());
                tabData.accept(CABlocks.EMERGENCY_AID_BUILDING_SALVIENTO.get().asItem());
                tabData.accept(CABlocks.HIGHMORE_DOLL.get().asItem());
                tabData.accept(CABlocks.MIZUKI_DOLL.get().asItem());
                tabData.accept(CABlocks.REDSTONIUM_BLOCK.get().asItem());
                tabData.accept(CABlocks.MOTAR_BASE_BLOCK.get().asItem());
                tabData.accept(CABlocks.CHEST_FISH_COOKED.get().asItem());
                tabData.accept(CABlocks.INJECTOR.get().asItem());
                tabData.accept(CABlocks.CENTRIFUGER.get().asItem());
                tabData.accept(CABlocks.OPERATION_TABLE.get().asItem());
                tabData.accept(CABlocks.ABANDONED_SULPTURE.get().asItem());
                tabData.accept(CABlocks.LIVING_ARMORSTAND.get().asItem());
                tabData.accept(CABlocks.TRAILRITE_ARMORSTAND.get().asItem());
                tabData.accept(CABlocks.POCKET_SEA_DOLL.get().asItem());
                tabData.accept(CABlocks.SWARMCALLER_DOLL.get().asItem());
                tabData.accept(CABlocks.STONECUTTER_DOLL.get().asItem());
                tabData.accept(CABlocks.BLOCK_KETTLE.get().asItem());
                tabData.accept(CABlocks.ALLAY_BLOCK.get().asItem());
                tabData.accept(CABlocks.BLOCK_BATBED.get().asItem());
                tabData.accept(CAItems.REDSTONE_INGOT.get());
                tabData.accept(CAItems.REDSTONIUM.get());
                tabData.accept(CAItems.COIN_OF_TRADE.get());
                tabData.accept(CAItems.OCEAN_EYE.get());
                tabData.accept(CAItems.FERMENTED_OCEAN_EYE.get());
                tabData.accept(CAItems.OCEAN_MACHINE.get());
                tabData.accept(CAItems.WHIRL_EYE.get());
                tabData.accept(CAItems.OCEAN_TRIM_TEMPLATE.get());
                tabData.accept(CAItems.TIDE_HUNET_TEMPLATE.get());
                tabData.accept(CAItems.FLAMARINE_UPGRADE_TEMPLATE.get());
                tabData.accept(CAItems.TRAIL_SHARD.get());
                tabData.accept(CAItems.TRAILRITE.get());
                tabData.accept(CAItems.TRAILRITE_NUGGET.get());
                tabData.accept(CAItems.ANCHOR_SHARD.get());
                tabData.accept(CAItems.ANCHOR_FORGE_INGOT.get());
                tabData.accept(CAItems.DIORITE_SCULPTURE.get());
                tabData.accept(CAItems.PALE_GOLD_PENDANT.get());
                tabData.accept(CAItems.MOIST_BAG.get());
                tabData.accept(CAItems.TRAIL_POWDER.get());
                tabData.accept(CAItems.TRAIL_POWDER_CORE.get());
                tabData.accept(CAItems.BONE_SHARD.get());
                tabData.accept(CAItems.OCEAN_PHLOEM.get());
                tabData.accept(CAItems.OCEAN_FIBRE.get());
                tabData.accept(CAItems.OCEAN_CRYSTAL.get());
                tabData.accept(CAItems.OCEAN_CUTIN.get());
                tabData.accept(CAItems.CUTIN_STICK.get());
                tabData.accept(CAItems.WHITE_CHITIN.get());
                tabData.accept(CAItems.OCEAN_CHITIN.get());
                tabData.accept(CAItems.CHITIN_INGOT.get());
                tabData.accept(CAItems.COMPLEX_CHITIN.get());
                tabData.accept(CAItems.HETEROPIC_PIECE.get());
                tabData.accept(CAItems.SHELL_OF_STONECUTTER.get());
                tabData.accept(CAItems.CORAL_FEET.get());
                tabData.accept(CAItems.REPELLER_SHELL.get());
                tabData.accept(CAItems.KNIGHT_CORPSE.get());
                tabData.accept(CAItems.TEAR_ISHARMLA.get());
                tabData.accept(CAItems.ISHARMLA_SCUTE.get());
                tabData.accept(CAItems.WATER_LOGGED_PEARL.get());
                tabData.accept(CAItems.MOIST_ECHO_SHARD.get());
                tabData.accept(CAItems.MOIST_STAR.get());
                tabData.accept(CAItems.MOIST_CRYSTAL_ITEM.get());
                tabData.accept(CAItems.MOIST_DRAGON_HEART.get());
                tabData.accept(CAItems.INCANDESCENT_ANIMA.get());
                tabData.accept(CAItems.LEVIATHAN_ANIMUS.get());
                tabData.accept(CAItems.MIZUKI_DETERMINATION.get());
                tabData.accept(CAItems.EMPTY_CAN.get());
                tabData.accept(CAItems.CANNED_WATER.get());
                tabData.accept(CAItems.CANNED_LAVA.get());
                tabData.accept(CAItems.CANNED_BOILED_WATER.get());
                tabData.accept(CAItems.OCEANGLASS_CUP.get());
                tabData.accept(CAItems.A_CUP_OF_WATER.get());
                tabData.accept(CAItems.PAPER_BAG.get());
                tabData.accept(CAItems.CAFFEINE.get());
                tabData.accept(CAItems.IMMUNOSUPPRESSOR.get());
                tabData.accept(CAItems.OBISIDIAN_BALL.get());
                tabData.accept(CAItems.FAKE_EGG.get());
                tabData.accept(CAItems.REAL_EGG.get());
                tabData.accept(CAItems.BASE_EGG.get());
                tabData.accept(CAItems.TARGETED_BASE.get());
                tabData.accept(CAItems.TRAIL_CREAM.get());
                tabData.accept(CAItems.BROKEN_OCEAN_CELL.get());
                tabData.accept(CAItems.BROKEN_CELL_CLUSTER.get());
                tabData.accept(CAItems.OCEAN_CELL.get());
                tabData.accept(CAItems.CELL_CLUSTER.get());
                tabData.accept(CAItems.TRANSFORM_CELL.get());
                tabData.accept(CAItems.NETHERSEA_CHICKEN_EGG.get());
                tabData.accept(CAItems.MUTAGENISIS_CAPSULE.get());
                tabData.accept(CAItems.OCEANIZE_CATALYST.get());
                tabData.accept(CAItems.COLOURFULL_JELLY.get());
                tabData.accept(CAItems.GENE_SAMPLE_NORMAL.get());
                tabData.accept(CAItems.GENE_SAMPLE_UPGRADED.get());
                tabData.accept(CAItems.GENE_SAMPLE_SUPERB.get());
                tabData.accept(CAItems.ARCHIVE_SAL_VIENTO.get());
                tabData.accept(CAItems.ARCHIVE_OF_TIDELINK.get());
                tabData.accept(CAItems.ARCHIVE_OF_MARTUS.get());
                tabData.accept(CAItems.ARCHIVE_OF_RAIDER.get());
            }).build());

    public static final DeferredHolder<CreativeModeTab, ? extends CreativeModeTab> CAECULA_RELICS = REGISTRY.register("caecula_relics",
            () -> CreativeModeTab.builder().title(Component.translatable("item_group.caerula_arbor.caecula_relics")).icon(() -> new ItemStack(CACollectible.KETTLE)).displayItems((parameters, tabData) -> {
                tabData.accept(new ItemStack(CACollectible.CURSED_EMELIGHT));
                tabData.accept(new ItemStack(CACollectible.CURSED_GLOWBODY));
                tabData.accept(new ItemStack(CACollectible.CURSED_RESEARCH));
                tabData.accept(new ItemStack(CACollectible.CAERULA_HEART));
                tabData.accept(new ItemStack(CACollectible.RELIC_CROWN));
                tabData.accept(new ItemStack(CACollectible.KING_ARMOR));
                tabData.accept(new ItemStack(CACollectible.KING_SPEAR));
                tabData.accept(new ItemStack(CACollectible.KING_EXTENSION));
                tabData.accept(new ItemStack(CACollectible.KING_CRYSTAL));
                tabData.accept(new ItemStack(CACollectible.SARKAZ_KING_ARTIFACT));
                tabData.accept(new ItemStack(CACollectible.SARKAZ_KING_FLAG));
                tabData.accept(new ItemStack(CACollectible.VAMPIRES_BED));
                tabData.accept(new ItemStack(CACollectible.ROYAL_FATE));
                tabData.accept(new ItemStack(CACollectible.SURVIVOR_CONTRACT));
                tabData.accept(new ItemStack(CACollectible.NURTURE_GENE_SET));
                tabData.accept(new ItemStack(CACollectible.OIL_AND_CREAM));
                tabData.accept(new ItemStack(CACollectible.TULIP_MEDCINE));
                tabData.accept(new ItemStack(CACollectible.GOLDEN_CHALISE));
                tabData.accept(new ItemStack(CACollectible.TREATY));
                tabData.accept(new ItemStack(CACollectible.CHITIN_KNIFE));
                tabData.accept(new ItemStack(CACollectible.HAND_THORNS));
                tabData.accept(new ItemStack(CACollectible.HAND_STRANGLE));
                tabData.accept(new ItemStack(CACollectible.HAND_FERTILITY));
                tabData.accept(new ItemStack(CACollectible.HAND_SPEED));
                tabData.accept(new ItemStack(CACollectible.HAND_OF_BARREN));
                tabData.accept(new ItemStack(CACollectible.HAND_SWIPE));
                tabData.accept(new ItemStack(CACollectible.HAND_FIREWORK));
                tabData.accept(new ItemStack(CACollectible.HAND_OF_ENGRAVE));
                tabData.accept(new ItemStack(CACollectible.HAND_SWORD));
                tabData.accept(new ItemStack(CACollectible.FEATURED_CANNED_MEAT));
                tabData.accept(new ItemStack(CACollectible.BOWL_SEAGRASS));
                tabData.accept(new ItemStack(CACollectible.GOLDEN_STORM));
                tabData.accept(new ItemStack(CACollectible.CANNED_CHERRY));
                tabData.accept(new ItemStack(CACollectible.AROMATIC_COFFEE));
                tabData.accept(new ItemStack(CACollectible.COFFEE_CANDY));
                tabData.accept(new ItemStack(CACollectible.RAINBOW_CANDY));
                tabData.accept(new ItemStack(CACollectible.SOLO_MUSIC_BOX));
                tabData.accept(new ItemStack(CACollectible.ODD_FLUTE));
                tabData.accept(new ItemStack(CACollectible.REDSTONE_IRIS_FLOWER));
                tabData.accept(new ItemStack(CACollectible.UTIL_RESCISSION));
                tabData.accept(new ItemStack(CACollectible.UTIL_SCORE));
                tabData.accept(new ItemStack(CACollectible.UTIL_OMNIKEY));
                tabData.accept(new ItemStack(CACollectible.UTIL_STARE));
                tabData.accept(new ItemStack(CACollectible.VOYAGE_OF_GOLD));
                tabData.accept(new ItemStack(CACollectible.PIGLIN_DIARY));
                tabData.accept(new ItemStack(CACollectible.TOPONYM_TEXTOLOGY));
                tabData.accept(new ItemStack(CACollectible.KETTLE));
                tabData.accept(new ItemStack(CACollectible.UTIL_ALLAY));
                tabData.accept(new ItemStack(CACollectible.BAT_BED));
                tabData.accept(new ItemStack(CACollectible.PROOF_OF_LONGEVITY));
                tabData.accept(new ItemStack(CACollectible.HEMOST));
                tabData.accept(new ItemStack(CACollectible.YEARNING));
            }).withTabsBefore(CAERULA_ITEMS.getId()).build());

    public static final DeferredHolder<CreativeModeTab, ? extends CreativeModeTab> CAERULA_LIVINGS = REGISTRY.register("caerula_livings",
            () -> CreativeModeTab.builder().title(Component.translatable("item_group.caerula_arbor.caerula_livings")).icon(() -> new ItemStack(CAItems.BUCKET_FLOATER.get())).displayItems((parameters, tabData) -> {
                tabData.accept(CAItems.RUN_FISH_SPAWN_EGG.get());
                tabData.accept(CAItems.SLIDER_FISH_SPAWN_EGG.get());
                tabData.accept(CAItems.SHOOTER_FISH_SPAWN_EGG.get());
                tabData.accept(CAItems.FLY_FISH_SPAWN_EGG.get());
                tabData.accept(CAItems.REAPER_FISH_SPAWN_EGG.get());
                tabData.accept(CAItems.POCKET_SEA_CREEPER_SPAWN_EGG.get());
                tabData.accept(CAItems.POCKET_SEA_CRAWLER_SPAWN_EGG.get());
                tabData.accept(CAItems.PUNCTURE_FISH_SPAWN_EGG.get());
                tabData.accept(CAItems.BASELAYER_ABYSSAL_SPAWN_EGG.get());
                tabData.accept(CAItems.PREDATOR_ABYSSAL_SPAWN_EGG.get());
                tabData.accept(CAItems.GUIDE_ABYSSAL_SPAWN_EGG.get());
                tabData.accept(CAItems.SPLASHER_ABYSSAL_SPAWN_EGG.get());
                tabData.accept(CAItems.UMBRELLA_ABYSSAL_SPAWN_EGG.get());
                tabData.accept(CAItems.CRACKER_ABYSSAL_SPAWN_EGG.get());
                tabData.accept(CAItems.COLLECTOR_PROKARYOTE_SPAWN_EGG.get());
                tabData.accept(CAItems.DEPOSITER_PROKARYOTE_SPAWN_EGG.get());
                tabData.accept(CAItems.FLOATER_PROKARYOTE_SPAWN_EGG.get());
                tabData.accept(CAItems.ACCUMULATOR_PROKARYOTE_SPAWN_EGG.get());
                tabData.accept(CAItems.FEEDER_PROKARYOTE_SPAWN_EGG.get());
                tabData.accept(CAItems.NUCLEIC_MALEFICENT_SPAWN_EGG.get());
                tabData.accept(CAItems.APOSTLE_PROKARYOTE_SPAWN_EGG.get());
                tabData.accept(CAItems.THE_ABANDONED_SPAWN_EGG.get());
                tabData.accept(CAItems.BONE_FISH_SPAWN_EGG.get());
                tabData.accept(CAItems.OCEAN_STONECUTTE_SPAWN_EGG.get());
                tabData.accept(CAItems.PREGNANT_FISH_SPAWN_EGG.get());
                tabData.accept(CAItems.FAKE_OFFSPRING_SPAWN_EGG.get());
                tabData.accept(CAItems.FLEE_FISH_SPAWN_EGG.get());
                tabData.accept(CAItems.COMPASSION_PRAYER_SPAWN_EGG.get());
                tabData.accept(CAItems.FIRST_TO_TALK_SPAWN_EGG.get());
                tabData.accept(CAItems.THIRSTER_SPAWN_EGG.get());
                tabData.accept(CAItems.ABSORBER_LIMB_SPAWN_EGG.get());
                tabData.accept(CAItems.TIDELINKED_BISHOP_SPAWNEGG.get());
                tabData.accept(CAItems.PATH_SHAPER_SPAWNEGG.get());
                tabData.accept(CAItems.ROUTE_FRACTAL_SPAWN_EGG.get());
                tabData.accept(CAItems.LINGERING_FRACTAL_SPAWN_EGG.get());
                tabData.accept(CAItems.TIDELINKED_IMMORTAL_SPAWNEGG.get());
                tabData.accept(CAItems.TIDELINKED_ARCHON_SPAWNEGG.get());
                tabData.accept(CAItems.QUINTUS_SPAWNEGG.get());
                tabData.accept(CAItems.SONS_SPAWN_EGG.get());
                tabData.accept(CAItems.ENDSPEAKER_SPAWNEGG.get());
                tabData.accept(CAItems.MARTUS_SPAWNEGG.get());
                tabData.accept(CAItems.HIGHMORE_SPAWNEGG.get());
                tabData.accept(CAItems.LAST_KNIGHT_SPAWNER.get());
                tabData.accept(CAItems.CORRUPTED_HEART_SPAWNER.get());
                tabData.accept(CAItems.ISHARMLA_SPAWNER.get());
                tabData.accept(CAItems.ISHARMLA_TEAR_SPAWN_EGG.get());
                tabData.accept(CAItems.IZUMIK_SPAWNEGG.get());
                tabData.accept(CAItems.CHEST_FISH_SPAWN_EGG.get());
                tabData.accept(CAItems.SCREAM_CHEST_FISH_SPAWN_EGG.get());
                tabData.accept(CAItems.SPIKE_CHEST_SPAWN_EGG.get());
                tabData.accept(CAItems.MEGA_CHEST_SPAWN_EGG.get());
                tabData.accept(CAItems.IZUMIK_OFFSPRING_SPAWN_EGG.get());
                tabData.accept(CAItems.OCEANIZED_VILLAGER_SPAWN_EGG.get());
                tabData.accept(CAItems.OCEANIZED_VINDICATOR_SPAWN_EGG.get());
                tabData.accept(CAItems.OCEANIZED_PILLAGER_SPAWN_EGG.get());
                tabData.accept(CAItems.OCEANIZED_EVOKER_SPAWN_EGG.get());
                tabData.accept(CAItems.OCEANIZED_VEX_SPAWN_EGG.get());
                tabData.accept(CAItems.OCEANIZED_WITCH_SPAWN_EGG.get());
                tabData.accept(CAItems.OCEANIZED_RAVAGER_SPAWN_EGG.get());
                tabData.accept(CAItems.OCEANIZED_PIG_SPAWN_EGG.get());
                tabData.accept(CAItems.OCEANIZED_COW_SPAWN_EGG.get());
                tabData.accept(CAItems.OCEANIZED_SHEEP_SPAWN_EGG.get());
                tabData.accept(CAItems.OCEANIZED_HORSE_SPAWN_EGG.get());
                tabData.accept(CAItems.OCEANIZED_CAT_SPAWN_EGG.get());
                tabData.accept(CAItems.OCEANIZED_WOLF_SPAWN_EGG.get());
                tabData.accept(CAItems.OCEANIZED_FOX_SPAWN_EGG.get());
                tabData.accept(CAItems.OCEANIZED_POLAR_BEAR_SPAWN_EGG.get());
                tabData.accept(CAItems.OCEANIZE_RABBIT_SPAWN_EGG.get());
                tabData.accept(CAItems.OCEANIZED_CHICKEN_SPAWN_EGG.get());
                tabData.accept(CAItems.NETHERSEA_SLIME_SPAWN_EGG.get());
                tabData.accept(CAItems.FISSION_PROKARYOTE_SLIME_SPAWN_EGG.get());
                tabData.accept(CAItems.OCEANIZED_PIGLIN_SPAWN_EGG.get());
                tabData.accept(CAItems.OCEANIZED_SPIDER_SPAWN_EGG.get());
                tabData.accept(CAItems.OCEANIZED_ENDERMAN_SPAWN_EGG.get());
                tabData.accept(CAItems.OCEANIZED_SHULKER_SPAWN_EGG.get());
                tabData.accept(CAItems.OCEANIZED_ILLUSIONER_SPAWNER.get());
                tabData.accept(CAItems.OCEAN_ILLUSION_SPAWN_EGG.get());
                tabData.accept(CAItems.OCEANIZED_WITHER_SPAWNEGG.get());
                tabData.accept(CAItems.OCEANIZED_WARDEN_SPAWNEGG.get());
                tabData.accept(CAItems.OCEANIZED_ENDER_DRAGON_SPAWN_EGG.get());
                tabData.accept(CAItems.MOIST_CRYSTAL_ITEM.get());
                tabData.accept(CAItems.CHITIN_GOLEM_SPAWN_EGG.get());
                tabData.accept(CAItems.COMPLEX_CHITIN_GOLEM_SPAWN_EGG.get());
                tabData.accept(CAItems.OCEANIZED_BRUTE_SPAWN_EGG.get());
                tabData.accept(CAItems.SUPER_SLIDER_SPAWN_EGG.get());
                tabData.accept(CAItems.SUPER_BIG_CAT_SPAWN_EGG.get());
                tabData.accept(CAItems.NAUTILUS_HEADHUNTER_SPAWN_EGG.get());
                tabData.accept(CAItems.REAPER_PET_SPAWN_EGG.get());
                tabData.accept(CAItems.TIDUTANT_ROCK_SPIDER_SPAWN_EGG.get());
                tabData.accept(CAItems.TIDUTANT_EXCRESCENCE_SPAWN_EGG.get());
            }).withTabsBefore(CAECULA_RELICS.getId()).build());

    public static final DeferredHolder<CreativeModeTab, ? extends CreativeModeTab> SEA_FOOD = REGISTRY.register("sea_food",
            () -> CreativeModeTab.builder().title(Component.translatable("item_group.caerula_arbor.sea_food")).icon(() -> new ItemStack(CAItems.BOILED_EGG.get())).displayItems((parameters, tabData) -> {
                tabData.accept(CAItems.FLUORE_BERRIES.get());
                tabData.accept(CAItems.RADIANT_BERRIES.get());
                tabData.accept(CAItems.COOKED_FIBRE.get());
                tabData.accept(CAItems.SEA_TRAIL_MOR.get());
                tabData.accept(CAItems.COOKED_MOR.get());
                tabData.accept(CAItems.CARAMEL_MOR.get());
                tabData.accept(CAItems.NETHERSEA_PUMPKIN_PIE.get());
                tabData.accept(CABlocks.TRAIL_CAKE.get().asItem());
                tabData.accept(CAItems.TRAIL_CAKE_PIECE.get());
                tabData.accept(CABlocks.CARAMEL_CAKE.get().asItem());
                tabData.accept(CAItems.CARAMEL_CAKE_PIECE.get());
                tabData.accept(CAItems.INSTANT_NOODLE.get());
                tabData.accept(CAItems.CANNED_NOODLE.get());
                tabData.accept(CAItems.COOKED_BROKEN_CELL_CLUSTER.get());
                tabData.accept(CAItems.COOKED_CELL_CLUSTER.get());
                tabData.accept(CAItems.OCEAN_PEDUNCLE.get());
                tabData.accept(CAItems.ELITE_PEDUNCLE.get());
                tabData.accept(CAItems.COOKED_PEDUNCLE.get());
                tabData.accept(CAItems.KEBAB_RAW.get());
                tabData.accept(CAItems.KEBAB_COOKED.get());
                tabData.accept(CAItems.BOILED_EGG.get());
                tabData.accept(CAItems.FRIED_EGG.get());
                tabData.accept(CAItems.COOKED_FAKEEGG.get());
                tabData.accept(CAItems.COLLECTOR_MEAT.get());
                tabData.accept(CAItems.COOKED_COLLECTOR.get());
                tabData.accept(CAItems.CLAW.get());
                tabData.accept(CAItems.COOKED_CLAW.get());
                tabData.accept(CAItems.SEABORN_SOUP.get());
                tabData.accept(CAItems.NETHERSEA_STEW.get());
                tabData.accept(CAItems.TRAIL_APPLE.get());
                tabData.accept(CAItems.TRAIL_GOLDEN_APPLE.get());
                tabData.accept(CAItems.ENCHANTED_TRAIL_GOLDEN_APPLE.get());
                tabData.accept(CAItems.FRUIT_JELLY.get());
                tabData.accept(CAItems.ECHO_JELLY.get());
                tabData.accept(CAItems.OCEAN_CAVAIR.get());
                tabData.accept(CAItems.ELITE_CAVAIR.get());
                tabData.accept(CAItems.NETHERSEA_ICECREAM.get());
                tabData.accept(CAItems.FLUORE_ICECREAM.get());
                tabData.accept(CAItems.NOURISHED_APPLE_PIE.get());
                tabData.accept(CAItems.DEEP_SEAGRASS_JUICE.get());
                tabData.accept(CAItems.CARAMEL_SEAGRASS_JUICE.get());
                tabData.accept(CAItems.COLOURFUL_APPLE_JUICE.get());
                tabData.accept(CAItems.NETHERSEA_STIMUTANT.get());
                tabData.accept(CAItems.FLUORE_BERRY_JUICE.get());
                tabData.accept(CAItems.NETHERSEA_COFFEE.get());
                tabData.accept(CAItems.NERVOUS_REGENERATION.get());
                tabData.accept(CAItems.NETHERSEA_EGG_CUSTARD.get());
                tabData.accept(CAItems.NETHERSEA_PRESERVED_EGG.get());
                tabData.accept(CAItems.CHITIN_COOKIE_RAW.get());
                tabData.accept(CAItems.CHITIN_COOKIE_DONE.get());
                tabData.accept(CABlocks.CHEST_FISH_COOKED.get().asItem());
            }).withTabsBefore(CAERULA_LIVINGS.getId()).build());

    public static final DeferredHolder<CreativeModeTab, ? extends CreativeModeTab> CAERULA_WEAPONS = REGISTRY.register("caerula_weapons",
            () -> CreativeModeTab.builder().title(Component.translatable("item_group.caerula_arbor.caerula_weapons")).icon(() -> new ItemStack(CAItems.COMPLEX_CHITIN_SWORD.get())).displayItems((parameters, tabData) -> {
                tabData.accept(CAItems.SEALEATHER_HELMET.get());
                tabData.accept(CAItems.SEALEATHER_CHESTPLATE.get());
                tabData.accept(CAItems.SEALEATHER_LEGGINGS.get());
                tabData.accept(CAItems.SEALEATHER_BOOTS.get());
                tabData.accept(CAItems.SEALEATHER_CHITIN_HELMET.get());
                tabData.accept(CAItems.SEALEATHER_CHITIN_CHESTPLATE.get());
                tabData.accept(CAItems.SEALEATHER_CHITIN_LEGGINGS.get());
                tabData.accept(CAItems.SEALEATHER_CHITIN_BOOTS.get());
                tabData.accept(CAItems.CHITIN_ARMOR_HELMET.get());
                tabData.accept(CAItems.CHITIN_ARMOR_CHESTPLATE.get());
                tabData.accept(CAItems.CHITIN_ARMOR_LEGGINGS.get());
                tabData.accept(CAItems.CHITIN_ARMOR_BOOTS.get());
                tabData.accept(CAItems.COMPLEXCHITIN_ARMOR_HELMET.get());
                tabData.accept(CAItems.COMPLEXCHITIN_ARMOR_CHESTPLATE.get());
                tabData.accept(CAItems.COMPLEXCHITIN_ARMOR_LEGGINGS.get());
                tabData.accept(CAItems.COMPLEXCHITIN_ARMOR_BOOTS.get());
                tabData.accept(CAItems.TRAILRITE_ARMOR_HELMET.get());
                tabData.accept(CAItems.TRAILRITE_ARMOR_CHESTPLATE.get());
                tabData.accept(CAItems.TRAILRITE_ARMOR_LEGGINGS.get());
                tabData.accept(CAItems.TRAILRITE_ARMOR_BOOTS.get());
                tabData.accept(CAItems.KNIGHT_IRON_HELMET.get());
                tabData.accept(CAItems.KNIGHT_IRON_CHESTPLATE.get());
                tabData.accept(CAItems.KNIGHT_IRON_LEGGINGS.get());
                tabData.accept(CAItems.KNIGHT_IRON_BOOTS.get());
                tabData.accept(CAItems.WEARABLE_CROWN_HELMET.get());
                tabData.accept(CAItems.WEARABLE_CHEST_CHESTPLATE.get());
                tabData.accept(CAItems.PHLOEM_BOW.get());
                tabData.accept(CAItems.CHITIN_BOW.get());
                tabData.accept(CAItems.COMPLEX_CHITIN_BOW.get());
                tabData.accept(CAItems.TRAILRITE_BOW.get());
                tabData.accept(CAItems.OCEAN_ARROW.get());
                tabData.accept(CAItems.TRAILRITE_ARROW.get());
                tabData.accept(CAItems.SWORD_OCEAN_CRYSTAL.get());
                tabData.accept(CAItems.CHITIN_SWORD.get());
                tabData.accept(CAItems.COMPLEX_CHITIN_SWORD.get());
                tabData.accept(CAItems.TRAILRITE_AXE.get());
                tabData.accept(CAItems.TRAILRITE_SWORD.get());
                tabData.accept(CAItems.PATH_INAUGURATOR.get());
                tabData.accept(CAItems.TIDE_WAND.get());
                tabData.accept(CAItems.TIDELINKED_WAND.get());
                tabData.accept(CAItems.DRAGON_WAND.get());
                tabData.accept(CAItems.IRON_SWORD_OF_KNIGHT_CORPUS.get());
                tabData.accept(CAItems.LONG_SWORD_OF_KNIGHT_CORPUS.get());
                tabData.accept(CAItems.HIGHMORE_SCYTHE.get());
                tabData.accept(CAItems.LANC_XIAO.get());
                tabData.accept(CAItems.HAND_ANCHOR.get());
                tabData.accept(CAItems.UNAMBIGUOUS_DIRECTION.get());
                tabData.accept(CAItems.CIRCULAR_SAW.get());
                tabData.accept(CAItems.UNFINISHED_BEAUTY.get());
                tabData.accept(CAItems.AEGIR_LANCET.get());
                tabData.accept(CAItems.BROKEN_SEA.get());
                tabData.accept(CAItems.AEGIR_SWORD.get());
                tabData.accept(CAItems.SKADI_SWORD.get());
                tabData.accept(CAItems.WAVECLEAVER.get());
                tabData.accept(CAItems.THE_SPEAR.get());
                tabData.accept(CAItems.LEGENDARY_SPEAR.get());
                tabData.accept(CAItems.LANTERN_JUDGEMENT.get());
                tabData.accept(CAItems.CHITIN_SHIELD.get());
                tabData.accept(CAItems.COMPLEX_CHITIN_SHIELD.get());
                tabData.accept(CAItems.TIDELINKED_SHIELD.get());
                tabData.accept(CAItems.TRAILRITE_SHIELD.get());
            }).withTabsBefore(SEA_FOOD.getId()).build());

    @SubscribeEvent
    public static void buildTabContentsVanilla(BuildCreativeModeTabContentsEvent tabData) {
        if (tabData.getTabKey() == CreativeModeTabs.COMBAT) {
            tabData.accept(CAItems.TRAILED_WOODEN_SWORD.get());
            tabData.accept(CAItems.TRAILED_STONE_SWORD.get());
            tabData.accept(CAItems.TRAILED_IRON_SWORD.get());
            tabData.accept(CAItems.TRAILED_DIAMOND_SWORD.get());
            tabData.accept(CAItems.TRAILED_NETHERITE_SWORD.get());
            tabData.accept(CAItems.TRAILED_GOLDEN_SWORD.get());
        } else if (tabData.getTabKey() == CreativeModeTabs.REDSTONE_BLOCKS) {
            tabData.accept(CABlocks.TRAIL_BUTTON.get().asItem());
            tabData.accept(CABlocks.TRAIL_PRESSURE_PLATE.get().asItem());
            tabData.accept(CABlocks.TRAIL_PLANK_BUTTON.get().asItem());
            tabData.accept(CABlocks.TRAIL_PLANK_PRESSURE_PLATE.get().asItem());
        } else if (tabData.getTabKey() == CreativeModeTabs.NATURAL_BLOCKS) {
            tabData.accept(CABlocks.SALTSAND.get().asItem());
        } else if (tabData.getTabKey() == CreativeModeTabs.BUILDING_BLOCKS) {
            tabData.accept(CABlocks.SALTWIND_COLUMN.get().asItem());
            tabData.accept(CABlocks.SALTWIND_SANDSTONE.get().asItem());
            tabData.accept(CABlocks.SALTWIND_SAND_STAIR.get().asItem());
            tabData.accept(CABlocks.SMOOTH_SALTWIND_SAND_SLAB.get().asItem());
            tabData.accept(CABlocks.SALTWIND_SAND_WALL.get().asItem());
            tabData.accept(CABlocks.SMOOTH_SALTWIND_SANDATONE.get().asItem());
            tabData.accept(CABlocks.SMOOTH_SALTWIND_SAND_STAIR.get().asItem());
            tabData.accept(CABlocks.SALTWIND_SAND_SLAB.get().asItem());
            tabData.accept(CABlocks.SMOOTH_SALTWIND_SAND_WALL.get().asItem());
            tabData.accept(CABlocks.SALTWIND_BRICK.get().asItem());
            tabData.accept(CABlocks.SALTWIND_STAIR.get().asItem());
            tabData.accept(CABlocks.SALTWIND_BRICK_SLAB.get().asItem());
            tabData.accept(CABlocks.CHISELED_SALTWIND_SANDSTONE.get().asItem());
            tabData.accept(CABlocks.CHIESELED_SALTWIND_SAND_WALL.get().asItem());
            tabData.accept(CABlocks.SALTWIND_SMOOTH_BRICK.get().asItem());
            tabData.accept(CABlocks.SALTWIND_SMOOTH_STAIR.get().asItem());
            tabData.accept(CABlocks.SALTWIND_SMOOTH_SLAB.get().asItem());
            tabData.accept(CABlocks.ISHARMLA_BRICK.get().asItem());
            tabData.accept(CABlocks.ISHARMLA_STAIR.get().asItem());
            tabData.accept(CABlocks.ISHARMLA_SLAB.get().asItem());
            tabData.accept(CABlocks.ISHARMLA_WALL.get().asItem());
            tabData.accept(CABlocks.ISHARMLA_BRICK_PILLAR.get().asItem());
            tabData.accept(CABlocks.ISHARMLA_BRICK_CHIESLED.get().asItem());
            tabData.accept(CABlocks.ISHARMLA_WALL_CHIESLED.get().asItem());
            tabData.accept(CABlocks.ISHARMLA_BRICK_GILDED.get().asItem());
            tabData.accept(CABlocks.ISHARMLA_WALL_GILDED.get().asItem());
            tabData.accept(CABlocks.TRAIL_BRICK.get().asItem());
            tabData.accept(CABlocks.CRACKED_TRAIL_BRICK.get().asItem());
            tabData.accept(CABlocks.TRAIL_STAIR.get().asItem());
            tabData.accept(CABlocks.TRAIL_SLAB.get().asItem());
            tabData.accept(CABlocks.TRAIL_WALL.get().asItem());
            tabData.accept(CABlocks.TRAIL_TILE.get().asItem());
            tabData.accept(CABlocks.TRAIL_PLANK.get().asItem());
            tabData.accept(CABlocks.TRAIL_PLANK_STAIR.get().asItem());
            tabData.accept(CABlocks.TRAIL_PLANK_SLAB.get().asItem());
            tabData.accept(CABlocks.TRAIL_PLANK_FENCEDOOR.get().asItem());
            tabData.accept(CABlocks.TRAIL_PLANKS_FENCE.get().asItem());
            tabData.accept(CABlocks.TRAIL_PLANK_DOOR.get().asItem());
            tabData.accept(CABlocks.TRAIL_WOOD_TRAPDOOR.get().asItem());
            tabData.accept(CABlocks.AEGIR_GLASS_DECO.get().asItem());
            tabData.accept(CABlocks.AEGIR_GLASS_BAR.get().asItem());
            tabData.accept(CABlocks.AEGIR_GLASS_ARCH.get().asItem());
        } else if (tabData.getTabKey() == CreativeModeTabs.FUNCTIONAL_BLOCKS) {
            tabData.accept(CABlocks.MOTAR_BASE_BLOCK.get().asItem());
        } else if (tabData.getTabKey() == CreativeModeTabs.TOOLS_AND_UTILITIES) {
            tabData.accept(CAItems.BLOODY_RECORD.get());
            tabData.accept(CAItems.RECORD_WHISPER.get());
            tabData.accept(CAItems.RECORD_DEEPNESS.get());
            tabData.accept(CAItems.RECORD_PATH_AHEAD.get());
            tabData.accept(CAItems.RECORD_UNDERTIDES.get());
            tabData.accept(CAItems.RECORD_ISHARMLA.get());
            tabData.accept(CAItems.RECORD_ENDOSPORE.get());
            tabData.accept(CAItems.RECORD_OCEANWISH.get());
            tabData.accept(CAItems.RECORD_UNDERDAWN.get());
            tabData.accept(CAItems.RECORD_MARE_NATUS.get());
            tabData.accept(CAItems.BUCKET_RUNFISH.get());
            tabData.accept(CAItems.BUCKET_SLIDER.get());
            tabData.accept(CAItems.BUCKET_OCEAN_STONECUTTE.get());
            tabData.accept(CAItems.BUCKET_FLOATER.get());
            tabData.accept(CAItems.BUCKET_BONEFISH.get());
            tabData.accept(CAItems.BUCKET_COLLECTOR.get());
        } else if (tabData.getTabKey() == CreativeModeTabs.SPAWN_EGGS) {
            tabData.accept(CAItems.SKADI_SPAWN_EGG.get());
            tabData.accept(CAItems.ULPIANS_SPAWN_EGG.get());
            tabData.accept(CAItems.GLADIIA_SPAWN_EGG.get());
            tabData.accept(CAItems.SPECTER_SPAWN_EGG.get());
            tabData.accept(CAItems.OCEANIZED_DOG_SPAWN_EGG.get());
            tabData.accept(CAItems.ROCINANTE_SPAWN_EGG.get());
            tabData.accept(CAItems.JUNIOR_WARRIOR_PRIEST_SPAWN_EGG.get());
            tabData.accept(CAItems.WARRIOR_PRIEST_SPAWN_EGG.get());
            tabData.accept(CAItems.CORRECTIONAL_PHALANXY_INFANTRY_SPAWN_EGG.get());
            tabData.accept(CAItems.CORRECTIONAL_PHALAX_VANGUARD_SPAWN_EGG.get());
            tabData.accept(CAItems.TRIBUNAL_HEALER_SPAWN_EGG.get());
            tabData.accept(CAItems.IRENE_SPAWN_EGG.get());
            tabData.accept(CAItems.FLAMARINE_STATUE_SPAWN_EGG.get());
            tabData.accept(CAItems.APOCATA_SPAWN_EGG.get());
            tabData.accept(CAItems.TIDE_CHIMERA_SPAWN_EGG.get());
            tabData.accept(CAItems.FLAMARINE_GOLEM_SPAWN_EGG.get());
            tabData.accept(CAItems.SAINT_CARMEN_SPAWN_EGG.get());
        } else if (tabData.getTabKey() == CreativeModeTabs.OP_BLOCKS) {
            if (tabData.hasPermissions()) {
                tabData.accept(CAItems.GUNMU_SPAWN_EGG.get());
                tabData.accept(CAItems.XANTIS_SPAWN_EGG.get());
                tabData.accept(CAItems.QUNYOU_WANTED_ISHARMLA_SPAWN_EGG.get());
                tabData.accept(CAItems.BANNED_ITEM.get());
                tabData.accept(CAItems.GOODSQUIDS_SERVERER.get());
                tabData.accept(CAItems.THERMOGRAPH.get());
                tabData.accept(CAItems.RULER.get());
                tabData.accept(CAItems.APOCATA_SWORD.get());
            }
        }
    }
}