package com.apocalypse.caerulaarbor.datagen.tags;

import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.PackOutput;
import net.minecraft.world.entity.EntityType;
import net.minecraftforge.common.data.ExistingFileHelper;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.concurrent.CompletableFuture;

public class EntityTypeTagsProvider extends TagsProvider.RegistryTagsProvider<EntityType<?>> {
    public EntityTypeTagsProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider,
                                  @Nullable ExistingFileHelper existingFileHelper) {
        super(output, Registries.ENTITY_TYPE, lookupProvider, existingFileHelper);
    }

    @Override
    protected void addTags(HolderLookup.@NotNull Provider provider) {
        addValues("bossoffspring", "caerula_arbor:super_slider", "caerula_arbor:route_shaper", "caerula_arbor:bishop_fish", "caerula_arbor:tide_bishop", "caerula_arbor:tide_deathrepeller", "caerula_arbor:mega_chest", "caerula_arbor:first_to_talk", "caerula_arbor:highmore", "caerula_arbor:oceanized_brute", "caerula_arbor:izumik", "caerula_arbor:martus", "caerula_arbor:oceanized_warden", "caerula_arbor:super_big_cat", "caerula_arbor:oceanized_wardenis", "caerula_arbor:oceanized_wither", "caerula_arbor:oceanized_witheria", "caerula_arbor:endspeaker", "caerula_arbor:lingering_pathshaper", "caerula_arbor:tide_chimera", "caerula_arbor:skadi_corrupted", "caerula_arbor:oceanized_illusioner", "caerula_arbor:isharmla", "caerula_arbor:compassion_prayer", "caerula_arbor:oceanized_enderina", "caerula_arbor:thirster");
        addValues("cannot_transform", "iron_golem", "#caerula_arbor:oceanoffspring", "caerula_arbor:chitin_golem", "snow_golem", "#caerula_arbor:golems", "slime", "magma_cube", "strider", "#caerula_arbor:hunters", "#caerula_arbor:sea_friend", "vex");
        addValues("endspeaker_edible", "caerula_arbor:baselayer_abyssal", "caerula_arbor:cracker_abyssal", "caerula_arbor:guide_abyssal", "caerula_arbor:predator_abyssal", "caerula_arbor:splasher_abyssal", "caerula_arbor:umbrella_abyssal");
        addValues("golems", "caerula_arbor:chitin_golem", "caerula_arbor:spike_chest", "caerula_arbor:complex_chitin_golem", "caerula_arbor:last_knight_and_horse", "caerula_arbor:the_last_knight", "caerula_arbor:flamarine_statue", "caerula_arbor:flamarine_golem", "caerula_arbor:moist_dragon_breath");
        addValues("homo_sapiens", "#caerula_arbor:inquisition", "caerula_arbor:apocata", "caerula_arbor:gunmu");
        addValues("hunters", "caerula_arbor:skadi", "caerula_arbor:ulpians", "caerula_arbor:gladiia", "caerula_arbor:specter", "caerula_arbor:specter_doll");
        addValues("ignore_migration", "caerula_arbor:oceanized_warden", "caerula_arbor:oceanized_wardenis", "caerula_arbor:izumik", "caerula_arbor:izumik_offspring", "caerula_arbor:oceanized_wither", "caerula_arbor:martus", "caerula_arbor:tide_chimera", "caerula_arbor:moist_dragon_breath", "caerula_arbor:moist_ender_crystal");
        addValues("immue_to_inst_sanity", "caerula_arbor:oceanized_witch");
        addValues("immue_to_nethersea_brand", "#caerula_arbor:oceanoffspring", "#caerula_arbor:golems", "caerula_arbor:little_helper", "caerula_arbor:al_1_s_helper", "caerula_arbor:flamarine_statue", "caerula_arbor:flamarine_golem", "caerula_arbor:qunyou_wanted_isharmla");
        addValues("inquisition", "#caerula_arbor:warriors", "#caerula_arbor:phalax", "caerula_arbor:tribunal_healer", "caerula_arbor:irene", "caerula_arbor:saint_carmen");
        addValues("is_humanside", "#caerula_arbor:hunters", "#caerula_arbor:inquisition", "caerula_arbor:gladiia_whirl", "caerula_arbor:chitin_golem", "caerula_arbor:complex_chitin_golem", "iron_golem", "snow_golem", "villager", "caerula_arbor:last_knight_and_horse", "caerula_arbor:the_last_knight", "#caerula_arbor:oceanpet");
        addValues("izumik_discovers", "caerula_arbor:bone_fish", "caerula_arbor:cracker_abyssal", "zombie", "zombie_villager", "zombified_piglin", "drowned", "enderman", "silverfish", "elder_guardian", "guardian", "caerula_arbor:flee_fish", "blaze", "creeper", "caerula_arbor:first_to_talk", "phantom", "cave_spider", "spider", "llama", "shulker", "skeleton", "wither_skeleton", "magma_cube", "caerula_arbor:route_fractal", "caerula_arbor:oceanized_cow", "caerula_arbor:oceanized_dog", "caerula_arbor:oceanized_horse", "caerula_arbor:oceanized_pig", "caerula_arbor:oceanized_piglin", "caerula_arbor:oceanized_pillager", "caerula_arbor:oceanized_ravager", "caerula_arbor:oceanized_sheep", "caerula_arbor:oceanized_villager", "caerula_arbor:oceanized_vindicator", "caerula_arbor:oceanized_wolf", "caerula_arbor:oceanized_witch", "caerula_arbor:oceanized_enderman", "caerula_arbor:oceanized_spider", "caerula_arbor:oceanized_brute", "caerula_arbor:oceanized_cat", "caerula_arbor:oceanized_evoker", "caerula_arbor:oceanized_wardenis", "caerula_arbor:oceanized_fox", "caerula_arbor:oceanized_polar_bear", "caerula_arbor:izumik_offspring", "caerula_arbor:lingering_fractal", "caerula_arbor:oceanize_rabbit", "caerula_arbor:compassion_prayer", "caerula_arbor:thirster", "caerula_arbor:nethersea_slime", "caerula_arbor:oceanized_chicken");
        addValues("marinemobs", "caerula_arbor:collector_prokaryote", "caerula_arbor:bone_fish", "caerula_arbor:apostle_prokaryote", "caerula_arbor:floater_prokaryote", "caerula_arbor:accumulator_prokaryote", "caerula_arbor:accumulator_clone", "caerula_arbor:feeder_prokaryote", "caerula_arbor:nucleic_maleficent", "caerula_arbor:depositer_prokaryote", "caerula_arbor:nautilus_headhunter");
        addValues("no_join_whirl", "glow_item_frame", "item_display", "item_frame", "zombie", "boat", "chest_boat", "minecart", "chest_minecart", "command_block_minecart", "furnace_minecart", "hopper_minecart", "spawner_minecart", "tnt_minecart", "caerula_arbor:gladiia_whirl", "caerula_arbor:al_1_s_helper", "caerula_arbor:little_helper", "caerula_arbor:isharmla_tear", "caerula_arbor:qunyou_wanted_isharmla");
        addValues("oceanelite", "caerula_arbor:baselayer_abyssal", "caerula_arbor:cracker_abyssal", "caerula_arbor:creeper_fish", "caerula_arbor:first_to_talk", "caerula_arbor:flee_fish", "caerula_arbor:guide_abyssal", "caerula_arbor:pregnant_fish", "caerula_arbor:puncture_fish", "caerula_arbor:reaper_fish", "caerula_arbor:umbrella_abyssal", "caerula_arbor:mega_chest", "caerula_arbor:apostle_prokaryote", "caerula_arbor:chest_fish", "caerula_arbor:oceanized_vindicator", "caerula_arbor:oceanized_enderman", "caerula_arbor:oceanized_ravager", "caerula_arbor:izumik_offspring", "caerula_arbor:oceanized_evoker", "caerula_arbor:the_abandoned", "caerula_arbor:nucleic_maleficent", "caerula_arbor:tidutant_rock_spider", "caerula_arbor:scream_chest_fish", "caerula_arbor:oceanized_shulker");
        addValues("oceanoffspring", "caerula_arbor:baselayer_abyssal", "caerula_arbor:creeper_fish", "caerula_arbor:fly_fish", "caerula_arbor:puncture_fish", "caerula_arbor:reaper_fish", "caerula_arbor:run_fish", "caerula_arbor:shooter_fish", "caerula_arbor:slider_fish", "caerula_arbor:super_slider", "caerula_arbor:predator_abyssal", "caerula_arbor:guide_abyssal", "caerula_arbor:splasher_abyssal", "caerula_arbor:umbrella_abyssal", "caerula_arbor:cracker_abyssal", "caerula_arbor:collector_prokaryote", "caerula_arbor:fake_offspring", "caerula_arbor:flee_fish", "caerula_arbor:pregnant_fish", "caerula_arbor:route_shaper", "caerula_arbor:route_fractal", "caerula_arbor:first_to_talk", "caerula_arbor:chiseler_fish", "caerula_arbor:bone_fish", "caerula_arbor:reaper_pet", "caerula_arbor:bishop_fish", "caerula_arbor:sons", "caerula_arbor:tide_bishop", "caerula_arbor:tide_deathrepeller", "caerula_arbor:mega_chest", "caerula_arbor:floater_prokaryote", "caerula_arbor:apostle_prokaryote", "caerula_arbor:highmore", "caerula_arbor:accumulator_prokaryote", "caerula_arbor:feeder_prokaryote", "caerula_arbor:chest_fish", "caerula_arbor:oceanized_villager", "caerula_arbor:oceanized_vindicator", "caerula_arbor:oceanized_pillager", "caerula_arbor:depositer_prokaryote", "caerula_arbor:oceanized_pig", "caerula_arbor:accumulator_clone", "caerula_arbor:oceanized_sheep", "caerula_arbor:oceanized_cow", "caerula_arbor:oceanized_horse", "caerula_arbor:oceanized_piglin", "caerula_arbor:oceanized_brute", "caerula_arbor:oceanized_spider", "caerula_arbor:oceanized_enderman", "caerula_arbor:oceanized_dog", "caerula_arbor:oceanized_wolf", "caerula_arbor:oceanized_ravager", "caerula_arbor:oceanized_witch", "caerula_arbor:izumik_offspring", "caerula_arbor:izumik", "caerula_arbor:oceanized_evoker", "caerula_arbor:the_abandoned", "caerula_arbor:martus", "caerula_arbor:oceanized_warden", "caerula_arbor:divicellular_go", "caerula_arbor:oceanized_cat", "caerula_arbor:super_big_cat", "caerula_arbor:oceanized_wardenis", "caerula_arbor:nucleic_maleficent", "caerula_arbor:oceanized_wither", "caerula_arbor:oceanized_witheria", "caerula_arbor:rocinante", "caerula_arbor:oceanized_fox", "caerula_arbor:tidutant_excrescence", "caerula_arbor:oceanized_polar_bear", "caerula_arbor:tidutant_rock_spider", "caerula_arbor:endspeaker", "caerula_arbor:lingering_pathshaper", "caerula_arbor:lingering_fractal", "caerula_arbor:tide_chimera", "caerula_arbor:skadi_corrupted", "caerula_arbor:oceanize_rabbit", "caerula_arbor:oceanized_illusioner", "caerula_arbor:ocean_illusion", "caerula_arbor:nautilus_headhunter", "caerula_arbor:oceanized_vex", "caerula_arbor:isharmla", "caerula_arbor:isharmla_tear", "caerula_arbor:compassion_prayer", "caerula_arbor:oceanized_enderina", "caerula_arbor:moist_ender_crystal", "caerula_arbor:thirster", "caerula_arbor:absorber_limb", "caerula_arbor:scream_chest_fish", "caerula_arbor:oceanized_chicken", "caerula_arbor:nethersea_slime", "caerula_arbor:oceanized_shulker");
        addValues("oceanpet", "caerula_arbor:reaper_pet", "caerula_arbor:oceanized_dog", "caerula_arbor:rocinante");
        addValues("oceanspawn", "caerula_arbor:fake_offspring", "caerula_arbor:route_fractal", "caerula_arbor:sons", "caerula_arbor:accumulator_clone", "caerula_arbor:chest_fish", "caerula_arbor:oceanized_villager", "caerula_arbor:oceanized_vindicator", "caerula_arbor:oceanized_pillager", "caerula_arbor:oceanized_pig", "caerula_arbor:oceanized_sheep", "caerula_arbor:oceanized_cow", "caerula_arbor:oceanized_horse", "caerula_arbor:oceanized_piglin", "caerula_arbor:oceanized_spider", "caerula_arbor:oceanized_enderman", "caerula_arbor:oceanized_ravager", "caerula_arbor:oceanized_witch", "caerula_arbor:izumik_offspring", "caerula_arbor:oceanized_evoker", "caerula_arbor:the_abandoned", "caerula_arbor:divicellular_go", "caerula_arbor:oceanized_cat", "caerula_arbor:oceanized_fox", "caerula_arbor:tidutant_excrescence", "caerula_arbor:oceanized_polar_bear", "caerula_arbor:tidutant_rock_spider", "caerula_arbor:lingering_fractal", "caerula_arbor:oceanize_rabbit", "caerula_arbor:oceanized_illusioner", "caerula_arbor:ocean_illusion", "caerula_arbor:nautilus_headhunter", "caerula_arbor:oceanized_vex", "caerula_arbor:isharmla_tear", "caerula_arbor:moist_ender_crystal", "caerula_arbor:absorber_limb", "caerula_arbor:scream_chest_fish", "caerula_arbor:oceanized_chicken", "caerula_arbor:nethersea_slime", "caerula_arbor:oceanized_shulker");
        addValues("phalax", "caerula_arbor:correctional_phalax_vanguard", "caerula_arbor:correctional_phalanxy_infantry");
        addValues("portable", "caerula_arbor:the_abandoned", "#caerula_arbor:homo_sapiens", "#caerula_arbor:hunters");
        addValues("sea_friend", "glow_squid", "squid", "elder_guardian", "guardian", "axolotl", "panda", "dolphin", "tadpole", "pufferfish", "creeper", "ghast", "turtle", "tropical_fish", "salmon", "cod", "caerula_arbor:apocata", "caerula_arbor:little_helper", "caerula_arbor:al_1_s_helper", "armor_stand", "caerula_arbor:moist_dragon_breath", "caerula_arbor:spike_chest");
        addValues("skip_migration", "caerula_arbor:oceanized_wither", "caerula_arbor:tide_chimera", "caerula_arbor:moist_dragon_breath", "caerula_arbor:moist_ender_crystal");
        addValues("warriors", "caerula_arbor:junior_warrior_priest", "caerula_arbor:warrior_priest");
        addValues("with_low_sanity_modifier", "#caerula_arbor:inquisition");
        addValues("with_lower_sanity_modifier", "#caerula_arbor:oceanoffspring");
        addValues("with_lowest_sanity_modifier", "#caerula_arbor:oceanelite", "warden");
        addValues("with_lowest_smaller_sanity_modifier", "#forge:bosses", "#caerula_arbor:hunters");
        addValues("with_lowest_smallest_sanity_modifier", "iron_golem", "caerula_arbor:chitin_golem", "caerula_arbor:the_last_knight", "caerula_arbor:last_knight_and_horse", "caerula_arbor:complex_chitin_golem", "caerula_arbor:flamarine_statue", "caerula_arbor:flamarine_golem");
        addValues("with_zero_sanity_modifier", "caerula_arbor:gunmu", "caerula_arbor:al_1_s_helper", "caerula_arbor:little_helper", "caerula_arbor:izumik", "caerula_arbor:qunyou_wanted_isharmla", "caerula_arbor:isharmla_tear");
    }
}
