package com.apocalypse.caerulaarbor.datagen.tags;

import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.PackOutput;
import net.minecraft.world.item.Item;
import net.minecraftforge.common.data.ExistingFileHelper;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.concurrent.CompletableFuture;

/**
 * 生成物品标签数据，包括本模组、forge 和 minecraft 命名空间
 */
public class ItemTagsProvider extends TagsProvider.RegistryTagsProvider<Item> {
    public ItemTagsProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider,
                            @Nullable ExistingFileHelper existingFileHelper) {
        super(output, Registries.ITEM, lookupProvider, existingFileHelper);
    }

    @Override
    protected void addTags(HolderLookup.@NotNull Provider provider) {
        addValues("animus", "caerula_arbor:caerula_heart", "caerula_arbor:incandescent_anima", "caerula_arbor:leviathan_animus", "caerula_arbor:moist_dragon_heart");
        addValues("any_coral", "minecraft:dead_tube_coral_block", "minecraft:dead_brain_coral_block", "minecraft:dead_bubble_coral_block", "minecraft:dead_fire_coral_block", "minecraft:dead_horn_coral_block", "minecraft:tube_coral_block", "minecraft:brain_coral_block", "minecraft:bubble_coral_block", "minecraft:fire_coral_block", "minecraft:horn_coral_block", "minecraft:dead_tube_coral", "minecraft:dead_brain_coral", "minecraft:dead_bubble_coral", "minecraft:dead_fire_coral", "minecraft:dead_horn_coral", "minecraft:tube_coral", "minecraft:brain_coral", "minecraft:bubble_coral", "minecraft:fire_coral", "minecraft:horn_coral", "minecraft:dead_tube_coral_fan", "minecraft:dead_brain_coral_fan", "minecraft:dead_bubble_coral_fan", "minecraft:dead_fire_coral_fan", "minecraft:dead_horn_coral_fan", "minecraft:tube_coral_fan", "minecraft:brain_coral_fan", "minecraft:bubble_coral_fan", "minecraft:fire_coral_fan", "minecraft:horn_coral_fan");
        addValues("archfiend_relics", "caerula_arbor:archfiends_artifact", "caerula_arbor:archfiends_flag", "caerula_arbor:archfiends_bed", "caerula_arbor:royal_fate");
        addValues("common_relics", "caerula_arbor:aromatic_coffee", "caerula_arbor:solo_music_box", "caerula_arbor:redstone_iris_flower", "caerula_arbor:odd_flute", "caerula_arbor:voyage_of_gold", "caerula_arbor:piglin_diary", "caerula_arbor:toponym_textology", "caerula_arbor:kettle", "caerula_arbor:allay_sculpture", "caerula_arbor:bat_bed", "caerula_arbor:omni_key", "caerula_arbor:score", "caerula_arbor:rescission", "caerula_arbor:smelly_hemostatic");
        addValues("cream_sword", "caerula_arbor:trailed_wooden_sword", "caerula_arbor:trailed_stone_sword", "caerula_arbor:trailed_iron_sword", "caerula_arbor:trailed_diamond_sword", "caerula_arbor:trailed_netherite_sword", "caerula_arbor:trailed_golden_sword");
        addValues("cursed", "caerula_arbor:relic_curse_emelight", "caerula_arbor:relic_cursed_glowbody", "caerula_arbor:relic_cursed_research", "caerula_arbor:caerula_heart");
        addValues("enchantable/nethersea_walker", "#forge:armor/boots");
        addValues("enchantable/sanity", "#minecraft:enchantable/weapon", "#minecraft:swords", "#minecraft:axes");
        addValues("enchantable/sanity_defend", "#minecraft:trimmable_armor", "#forge:armors", "#forge:armor/leggings", "#forge:armor/boots", "#forge:armor/helmets", "#forge:armor/chestplates");
        addValues("enchantable/seaborn_killer", "#minecraft:axes", "#minecraft:swords", "caerula_arbor:unambiguous_direction", "caerula_arbor:unfinished_beauty", "caerula_arbor:wavecleaver", "#minecraft:enchantable/weapon");
        addValues("endspeaker_chapter", "caerula_arbor:dictationless_chapter", "caerula_arbor:dictation_chapter");
        addValues("fish_food", "caerula_arbor:sea_trail_mor", "caerula_arbor:ocean_fibre", "caerula_arbor:cooked_mor", "caerula_arbor:broken_cell_cluster", "caerula_arbor:cell_cluster", "caerula_arbor:caramel_mor", "caerula_arbor:ocean_peduncle", "caerula_arbor:elite_peduncle", "caerula_arbor:cooked_fibre", "caerula_arbor:cooked_broken_cell_cluster", "caerula_arbor:cooked_cell_cluster", "caerula_arbor:cooked_peduncle", "caerula_arbor:fake_egg", "caerula_arbor:real_egg", "caerula_arbor:cooked_fakeegg", "caerula_arbor:collector_meat", "caerula_arbor:cooked_collector", "caerula_arbor:claw", "caerula_arbor:cooked_claw");
        addValues("gene", "caerula_arbor:dna_reaper", "caerula_arbor:hunter_gene", "caerula_arbor:dna_horse", "caerula_arbor:rocinante_injector", "caerula_arbor:hunter_gene_skadi", "caerula_arbor:hunter_gene_ulpians", "caerula_arbor:hunter_gene_gladiia", "caerula_arbor:hunter_gene_specter", "caerula_arbor:nurture_gene_set", "caerula_arbor:gene_sample_normal", "caerula_arbor:gene_sample_upgraded", "caerula_arbor:gene_sample_superb");
        addValues("hand_relics", "caerula_arbor:hand_of_thorns", "caerula_arbor:hand_of_strangle", "caerula_arbor:hand_of_fertiliy", "caerula_arbor:hand_of_speed", "caerula_arbor:hand_of_barren", "caerula_arbor:hand_of_spotless", "caerula_arbor:hand_of_firework", "caerula_arbor:hand_of_engrave", "caerula_arbor:hand_sword");
        addValues("king_relics", "caerula_arbor:relic_crown", "caerula_arbor:kings_armour", "caerula_arbor:kings_spear", "caerula_arbor:kings_extension", "caerula_arbor:kings_crystal");
        addValues("knight_equipment", "caerula_arbor:iron_sword_of_knight_corpus", "caerula_arbor:long_sword_of_knight_corpus", "caerula_arbor:knight_iron_helmet", "caerula_arbor:knight_iron_chestplate", "caerula_arbor:knight_iron_leggings", "caerula_arbor:knight_iron_boots");
        addValues("moist_item", "caerula_arbor:moist_echo_shard", "caerula_arbor:moist_star", "caerula_arbor:water_logged_pearl", "caerula_arbor:moist_crystal_item", "caerula_arbor:moist_dragon_heart");
        addValues("nethersea_logs", "caerula_arbor:nethersea_wood", "caerula_arbor:stripped_nethersea_wood", "caerula_arbor:trail_log", "caerula_arbor:stripped_trail_log");
        addValues("nethersea_protective", "caerula_arbor:trailrite_axe", "caerula_arbor:trailrite_sword", "caerula_arbor:trailrite_pickaxe", "caerula_arbor:trailrite_hoe", "caerula_arbor:trailrite_shovel", "caerula_arbor:trail_mop");
        addValues("relic_advanced", "#caerula_arbor:king_relics", "#caerula_arbor:archfiend_relics", "caerula_arbor:survivor_contract", "caerula_arbor:chitin_knife", "caerula_arbor:unripe_yearning", "caerula_arbor:crimson_treaty", "#caerula_arbor:hand_relics");
        addValues("relic_generic", "#caerula_arbor:hand_relics", "#caerula_arbor:archfiend_relics", "#caerula_arbor:king_relics", "caerula_arbor:survivor_contract", "caerula_arbor:crimson_treaty", "caerula_arbor:bowl_seagrass", "caerula_arbor:golden_storm", "caerula_arbor:coffee_candy", "caerula_arbor:canned_cherry", "caerula_arbor:rainbow_candy", "caerula_arbor:aromatic_coffee", "caerula_arbor:solo_music_box", "caerula_arbor:redstone_iris_flower", "caerula_arbor:odd_flute", "caerula_arbor:voyage_of_gold", "caerula_arbor:piglin_diary", "caerula_arbor:toponym_textology", "caerula_arbor:kettle", "caerula_arbor:chitin_knife", "caerula_arbor:allay_sculpture", "caerula_arbor:bat_bed", "caerula_arbor:proof_of_longevity", "caerula_arbor:omni_key", "caerula_arbor:score", "caerula_arbor:rescission", "caerula_arbor:guardian_stare", "caerula_arbor:unripe_yearning", "caerula_arbor:meat_can", "caerula_arbor:smelly_hemostatic");
        addValues("seaborn_loots", "caerula_arbor:ocean_phloem", "caerula_arbor:ocean_fibre", "caerula_arbor:ocean_eye", "caerula_arbor:ocean_crystal", "caerula_arbor:ocean_cutin", "caerula_arbor:ocean_chitin", "#caerula_arbor:fish_food", "#caerula_arbor:moist_item", "caerula_arbor:heteropic_piece", "caerula_arbor:broken_ocean_cell", "caerula_arbor:broken_cell_cluster", "caerula_arbor:ocean_cell", "caerula_arbor:cell_cluster");
        addValues("self_mendable", "caerula_arbor:complex_chitin_sword", "caerula_arbor:complex_chitin_pickaxe", "caerula_arbor:complex_chitin_axe", "caerula_arbor:complex_chitin_shovel", "caerula_arbor:complex_chitin_hoe", "caerula_arbor:legendary_spear", "caerula_arbor:trailed_wooden_sword", "caerula_arbor:trailed_stone_sword", "caerula_arbor:trailed_iron_sword", "caerula_arbor:trailed_diamond_sword", "caerula_arbor:trailed_netherite_sword", "caerula_arbor:trailed_golden_sword", "caerula_arbor:phloem_bow", "caerula_arbor:trailrite_axe", "caerula_arbor:trailrite_sword", "caerula_arbor:path_inaugurator", "caerula_arbor:complex_chitin_bow");
        addForgeValues("armor/boots", "caerula_arbor:chitin_armor_boots", "caerula_arbor:sealeather_boots", "caerula_arbor:complexchitin_armor_boots", "minecraft:leather_boots", "minecraft:chainmail_boots", "minecraft:iron_boots", "minecraft:golden_boots", "minecraft:diamond_boots", "minecraft:netherite_boots", "caerula_arbor:trailrite_armor_boots", "caerula_arbor:sealeather_chitin_boots", "caerula_arbor:knight_iron_boots");
        addForgeValues("armor/chestplates", "caerula_arbor:chitin_armor_chestplate", "caerula_arbor:sealeather_chestplate", "caerula_arbor:complexchitin_armor_chestplate", "caerula_arbor:wearable_chest_chestplate", "minecraft:leather_chestplate", "minecraft:chainmail_chestplate", "minecraft:iron_chestplate", "minecraft:golden_chestplate", "minecraft:diamond_chestplate", "minecraft:netherite_chestplate", "caerula_arbor:sealeather_chitin_chestplate", "caerula_arbor:trailrite_armor_chestplate", "caerula_arbor:knight_iron_chestplate");
        addForgeValues("armor/helmets", "caerula_arbor:chitin_armor_helmet", "caerula_arbor:sealeather_helmet", "caerula_arbor:complexchitin_armor_helmet", "caerula_arbor:wearable_crown_helmet", "minecraft:leather_helmet", "minecraft:chainmail_helmet", "minecraft:turtle_helmet", "minecraft:iron_helmet", "minecraft:golden_helmet", "minecraft:diamond_helmet", "minecraft:netherite_helmet", "caerula_arbor:sealeather_chitin_helmet", "caerula_arbor:trailrite_armor_helmet", "caerula_arbor:knight_iron_helmet");
        addForgeValues("armor/leggings", "caerula_arbor:chitin_armor_leggings", "caerula_arbor:sealeather_leggings", "caerula_arbor:complexchitin_armor_leggings", "minecraft:leather_leggings", "minecraft:chainmail_leggings", "minecraft:iron_leggings", "minecraft:golden_leggings", "minecraft:diamond_leggings", "minecraft:netherite_leggings", "caerula_arbor:sealeather_chitin_leggings", "caerula_arbor:trailrite_armor_leggings", "caerula_arbor:knight_iron_leggings");
        addForgeValues("armors", "caerula_arbor:chitin_armor_helmet", "caerula_arbor:chitin_armor_chestplate", "caerula_arbor:chitin_armor_leggings", "caerula_arbor:chitin_armor_boots", "caerula_arbor:sealeather_helmet", "caerula_arbor:sealeather_chestplate", "caerula_arbor:sealeather_leggings", "caerula_arbor:sealeather_boots", "caerula_arbor:complexchitin_armor_helmet", "caerula_arbor:complexchitin_armor_chestplate", "caerula_arbor:complexchitin_armor_leggings", "caerula_arbor:complexchitin_armor_boots", "minecraft:diamond_helmet", "minecraft:diamond_chestplate", "minecraft:diamond_leggings", "minecraft:diamond_boots", "minecraft:leather_helmet", "minecraft:leather_chestplate", "minecraft:leather_leggings", "minecraft:leather_boots", "minecraft:chainmail_helmet", "minecraft:chainmail_chestplate", "minecraft:chainmail_leggings", "minecraft:chainmail_boots", "minecraft:iron_helmet", "minecraft:iron_chestplate", "minecraft:iron_leggings", "minecraft:iron_boots", "minecraft:netherite_helmet", "minecraft:netherite_chestplate", "minecraft:netherite_leggings", "minecraft:netherite_boots", "#forge:armor/leggings", "#forge:armor/chestplates", "#forge:armor/boots", "#forge:armor/helmets", "caerula_arbor:trailrite_armor_helmet", "caerula_arbor:trailrite_armor_chestplate", "caerula_arbor:trailrite_armor_leggings", "caerula_arbor:trailrite_armor_boots", "caerula_arbor:knight_iron_helmet", "caerula_arbor:knight_iron_chestplate", "caerula_arbor:knight_iron_leggings", "caerula_arbor:knight_iron_boots");
        addForgeValues("fences", "caerula_arbor:trail_planks_fence");
        addForgeValues("fences/wooden", "caerula_arbor:trail_planks_fence");
        addForgeValues("ingots", "caerula_arbor:redstone_ingot", "caerula_arbor:trailrite");
        addForgeValues("meats", "caerula_arbor:ocean_fibre", "caerula_arbor:cooked_fibre", "caerula_arbor:ocean_peduncle", "caerula_arbor:elite_peduncle", "caerula_arbor:cooked_peduncle", "caerula_arbor:collector_meat", "caerula_arbor:cooked_collector", "#minecraft:meat");
        addForgeValues("storage_blocks", "caerula_arbor:chitin_block", "caerula_arbor:ocean_crystal_block", "caerula_arbor:complex_chitin_block", "caerula_arbor:trailrite_block", "caerula_arbor:heteropic_block");
        addForgeValues("storage_blocks/complex_chitin", "caerula_arbor:complex_chitin_block");
        addForgeValues("storage_blocks/heteropic", "caerula_arbor:heteropic_block");
        addForgeValues("storage_blocks/ocean_chitin", "caerula_arbor:chitin_block");
        addForgeValues("storage_blocks/ocean_crystal", "caerula_arbor:ocean_crystal_block");
        addForgeValues("storage_blocks/trailrite", "caerula_arbor:trailrite_block");
        addForgeValues("tools/bows", "caerula_arbor:phloem_bow", "caerula_arbor:tide_wand", "caerula_arbor:chitin_bow", "caerula_arbor:tidelinked_wand", "caerula_arbor:dragon_wand", "caerula_arbor:complex_chitin_bow", "caerula_arbor:trailrite_bow");
        addForgeValues("tools/crossbows", "caerula_arbor:dragon_wand");
        addForgeValues("tools/hoes", "caerula_arbor:chitin_hoe", "caerula_arbor:hoe_ocean_crystal", "caerula_arbor:complex_chitin_hoe", "caerula_arbor:path_inaugurator", "caerula_arbor:trailrite_hoe", "minecraft:wooden_hoe", "minecraft:stone_hoe", "minecraft:iron_hoe", "minecraft:golden_hoe", "minecraft:diamond_hoe", "minecraft:netherite_hoe");

        addMinecraftValues("axes", "caerula_arbor:trailrite_axe", "caerula_arbor:complex_chitin_axe", "caerula_arbor:axe_ocean_crystal", "caerula_arbor:chitin_axe", "caerula_arbor:path_inaugurator", "caerula_arbor:circular_saw", "caerula_arbor:unfinished_beauty");
        addMinecraftValues("base_stone_overworld", "minecraft:stone", "minecraft:granite", "minecraft:diorite", "minecraft:andesite");
        addMinecraftValues("bookshelf_books", "caerula_arbor:survivor_contract", "caerula_arbor:piglin_diary", "caerula_arbor:toponym_textology", "caerula_arbor:martus_book", "caerula_arbor:dictationless_chapter", "caerula_arbor:relic_cursed_research", "caerula_arbor:dictation_chapter");
        addMinecraftValues("buttons", "caerula_arbor:trail_button", "caerula_arbor:trail_plank_button");
        addMinecraftValues("enchantable/sharp_weapon", "caerula_arbor:legendary_spear", "caerula_arbor:wavecleaver", "caerula_arbor:chitin_shovel", "caerula_arbor:block_spear", "caerula_arbor:sword_ocean_crystal", "caerula_arbor:chitin_axe", "caerula_arbor:chitin_sword", "caerula_arbor:axe_ocean_crystal", "caerula_arbor:complex_chitin_sword", "caerula_arbor:complex_chitin_axe", "caerula_arbor:trailed_wooden_sword", "caerula_arbor:trailed_stone_sword", "caerula_arbor:trailed_iron_sword", "caerula_arbor:trailed_diamond_sword", "caerula_arbor:trailed_netherite_sword", "caerula_arbor:trailed_golden_sword", "caerula_arbor:trailrite_axe", "caerula_arbor:trailrite_sword", "#minecraft:swords", "#minecraft:axes");
        addMinecraftValues("enchantable/sword", "#minecraft:swords", "caerula_arbor:legendary_spear", "caerula_arbor:wavecleaver");
        addMinecraftValues("enchantable/weapon", "caerula_arbor:the_spear", "caerula_arbor:sword_ocean_crystal", "caerula_arbor:chitin_sword", "caerula_arbor:complex_chitin_sword", "caerula_arbor:legendary_spear", "caerula_arbor:wavecleaver");
        addMinecraftValues("fences", "caerula_arbor:trail_planks_fence");
        addMinecraftValues("flowers", "caerula_arbor:trail_mushroom");
        addMinecraftValues("fox_food", "caerula_arbor:fluore_berries", "caerula_arbor:radiant_berries", "caerula_arbor:canned_cherry");
        addMinecraftValues("fruits", "minecraft:apple", "minecraft:golden_apple", "minecraft:enchanted_golden_apple", "minecraft:melon_slice", "minecraft:sweet_berries", "minecraft:glow_berries", "minecraft:glistering_melon_slice");
        addMinecraftValues("hoes", "caerula_arbor:trailrite_hoe", "caerula_arbor:complex_chitin_hoe", "caerula_arbor:hoe_ocean_crystal", "caerula_arbor:chitin_hoe", "caerula_arbor:path_inaugurator");
        addMinecraftValues("logs", "caerula_arbor:trail_log", "caerula_arbor:stripped_trail_log", "caerula_arbor:nethersea_wood", "caerula_arbor:stripped_nethersea_wood");
        addMinecraftValues("meat", "minecraft:cooked_porkchop", "minecraft:cooked_beef", "minecraft:cooked_chicken", "minecraft:cooked_rabbit", "minecraft:cooked_mutton", "minecraft:cod", "minecraft:salmon", "minecraft:tropical_fish", "minecraft:pufferfish", "minecraft:cooked_cod", "minecraft:cooked_salmon");
        addMinecraftValues("music_discs", "caerula_arbor:record_isharmla", "caerula_arbor:record_deepness", "caerula_arbor:record_undertides", "caerula_arbor:record_path_ahead", "caerula_arbor:record_endospore", "caerula_arbor:record_whisper", "caerula_arbor:bloody_record", "caerula_arbor:score");
        addMinecraftValues("pickaxes", "caerula_arbor:trailrite_pickaxe", "caerula_arbor:hand_anchor", "caerula_arbor:trail_mop", "caerula_arbor:complex_chitin_pickaxe", "caerula_arbor:pickaxe_ocean_crystal", "caerula_arbor:chitin_pickaxe");
        addMinecraftValues("piglin_loved", "caerula_arbor:trailed_golden_sword", "caerula_arbor:trail_golden_apple", "caerula_arbor:voyage_of_gold");
        addMinecraftValues("planks", "caerula_arbor:trail_plank");
        addMinecraftValues("sal_viento_deco", "caerula_arbor:saltwind_sandstone", "caerula_arbor:chiseled_saltwind_sandstone", "caerula_arbor:smooth_saltwind_sandatone", "caerula_arbor:saltwind_column", "caerula_arbor:saltwind_brick", "caerula_arbor:saltwind_smooth_brick");
        addMinecraftValues("shovels", "caerula_arbor:trailrite_shovel", "caerula_arbor:complex_chitin_shovel", "caerula_arbor:shovel_ocean_crystal", "caerula_arbor:chitin_shovel");
        addMinecraftValues("small_flowers", "caerula_arbor:trail_mushroom");
        addMinecraftValues("stone_buttons", "caerula_arbor:trail_button");
        addMinecraftValues("swords", "caerula_arbor:skadi_sword", "caerula_arbor:aegir_sword", "caerula_arbor:broken_sea", "caerula_arbor:aegir_lancet", "caerula_arbor:apocata_sword", "caerula_arbor:lanc_xiao", "caerula_arbor:long_sword_of_knight_corpus", "caerula_arbor:iron_sword_of_knight_corpus", "caerula_arbor:trailrite_sword", "caerula_arbor:trailed_golden_sword", "caerula_arbor:trailed_netherite_sword", "caerula_arbor:trailed_diamond_sword", "caerula_arbor:trailed_iron_sword", "caerula_arbor:trailed_stone_sword", "caerula_arbor:trailed_wooden_sword", "caerula_arbor:complex_chitin_sword", "caerula_arbor:chitin_sword", "caerula_arbor:sword_ocean_crystal", "caerula_arbor:the_spear", "caerula_arbor:legendary_spear");
        addMinecraftValues("tools", "caerula_arbor:the_spear", "caerula_arbor:sword_ocean_crystal", "caerula_arbor:chitin_pickaxe", "caerula_arbor:pickaxe_ocean_crystal", "caerula_arbor:complex_chitin_pickaxe", "caerula_arbor:trailrite_pickaxe", "caerula_arbor:chitin_axe", "caerula_arbor:axe_ocean_crystal", "caerula_arbor:complex_chitin_axe", "caerula_arbor:trailrite_axe", "caerula_arbor:chitin_sword", "caerula_arbor:complex_chitin_sword", "caerula_arbor:trailed_wooden_sword", "caerula_arbor:trailed_stone_sword", "caerula_arbor:trailed_iron_sword", "caerula_arbor:trailed_diamond_sword", "caerula_arbor:trailed_netherite_sword", "caerula_arbor:trailed_golden_sword", "caerula_arbor:trailrite_sword", "caerula_arbor:iron_sword_of_knight_corpus", "caerula_arbor:long_sword_of_knight_corpus", "caerula_arbor:apocata_sword", "caerula_arbor:aegir_sword", "caerula_arbor:skadi_sword", "caerula_arbor:chitin_shovel", "caerula_arbor:shovel_ocean_crystal", "caerula_arbor:complex_chitin_shovel", "caerula_arbor:trailrite_shovel", "caerula_arbor:chitin_hoe", "caerula_arbor:hoe_ocean_crystal", "caerula_arbor:complex_chitin_hoe", "caerula_arbor:trailrite_hoe", "caerula_arbor:tide_wand", "caerula_arbor:tidelinked_wand", "caerula_arbor:highmore_scythe", "caerula_arbor:circular_saw", "caerula_arbor:aegir_lancet", "caerula_arbor:unambiguous_direction", "caerula_arbor:broken_sea", "caerula_arbor:wavecleaver", "caerula_arbor:unfinished_beauty");
        addMinecraftValues("trim_templates", "caerula_arbor:ocean_trim_template", "caerula_arbor:hunter_gene", "caerula_arbor:hunter_gene_skadi", "caerula_arbor:hunter_gene_ulpians", "caerula_arbor:hunter_gene_gladiia", "caerula_arbor:hunter_gene_specter", "caerula_arbor:tide_hunet_template", "caerula_arbor:flamarine_upgrade_template");
        addMinecraftValues("trimmable_armor", "caerula_arbor:chitin_armor_helmet", "caerula_arbor:chitin_armor_chestplate", "caerula_arbor:chitin_armor_leggings", "caerula_arbor:chitin_armor_boots");
        addMinecraftValues("tulip", "minecraft:red_tulip", "minecraft:orange_tulip", "minecraft:white_tulip", "minecraft:pink_tulip");
        addMinecraftValues("wooden_buttons", "caerula_arbor:trail_plank_button");
        addMinecraftValues("wooden_fences", "caerula_arbor:trail_planks_fence");
        addMinecraftValues("wooden_pressure_plates", "caerula_arbor:trail_plank_pressure_plate");
        addMinecraftValues("wooden_slabs", "caerula_arbor:trail_plank_slab");
        addMinecraftValues("wooden_stairs", "caerula_arbor:trail_plank_stair");
    }
}
